CREATE TABLE IF NOT EXISTS `RECOMPENSAS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `RECOMPENSA` varchar(200) NOT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__DISTRIBUICAO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `NOME` varchar(250) NOT NULL,
  `ATIVO` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__NIVEIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RECOMPENSA_CODE` bigint(25) NOT NULL,
  `RECONPENSA_TIPO_CODE` bigint(25) NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `NIVEL` int(11) NOT NULL,
  `CALCULO` int(11) DEFAULT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  `CRIADO_DATA` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `REL_NIVEIS_RECONPENSA_CODE` (`RECOMPENSA_CODE`),
  KEY `REL_NIVEIS_CALCULO_CODE` (`CALCULO`),
  KEY `NIVEL` (`NIVEL`),
  KEY `REL_NIVEIS_RECONPENSA_TIPO_CODE` (`RECONPENSA_TIPO_CODE`),
  CONSTRAINT `REL_NIVEIS_CALCULO_CODE` FOREIGN KEY (`CALCULO`) REFERENCES `RECOMPENSAS__UNIDADE_CALCULO` (`CODE`),
  CONSTRAINT `REL_NIVEIS_RECONPENSA_CODE` FOREIGN KEY (`RECOMPENSA_CODE`) REFERENCES `RECOMPENSAS` (`CODE`),
  CONSTRAINT `REL_NIVEIS_RECONPENSA_TIPO_CODE` FOREIGN KEY (`RECONPENSA_TIPO_CODE`) REFERENCES `RECOMPENSAS__TIPO` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8mb4;


/*!40000 ALTER TABLE `RECOMPENSAS__NIVEIS` DISABLE KEYS */;
INSERT INTO `RECOMPENSAS__NIVEIS` (`ID`, `RECOMPENSA_CODE`, `RECONPENSA_TIPO_CODE`, `VALOR`, `NIVEL`, `CALCULO`, `EXCLUIDO`, `CRIADO_DATA`) VALUES
	(59, 124583124718240, 148581203770433, 4.00, 2, 1, 0, '2022-07-31 15:41:55'),
	(60, 124583124718240, 148581203770433, 1.00, 1, 1, 0, '2022-07-31 15:41:59'),
	(61, 124583124718240, 148581203770433, 2.00, 4, 1, 0, '2022-07-31 15:42:01'),
	(62, 124583124718240, 148581203770433, 1.00, 3, 1, 0, '2022-10-13 22:34:22');
/*!40000 ALTER TABLE `RECOMPENSAS__NIVEIS` ENABLE KEYS */;



CREATE TABLE IF NOT EXISTS `RECOMPENSAS__ORIGEM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL DEFAULT 0,
  `ORIGEM` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

/*!40000 ALTER TABLE `RECOMPENSAS__ORIGEM` DISABLE KEYS */;
INSERT INTO `RECOMPENSAS__ORIGEM` (`ID`, `CODE`, `ORIGEM`) VALUES
	(1, 0, 'EMPRESA'),
	(2, 1, 'DE QUEM PAGA '),
	(3, 2, 'DE QUEM RECEBE');
/*!40000 ALTER TABLE `RECOMPENSAS__ORIGEM` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__POR_GRADUACAO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_GRAD` bigint(26) NOT NULL,
  `CODE_TIPO` bigint(26) NOT NULL,
  `ACTION` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `REL_RECOMPENSA_TO_CODE_GRADUACAO` (`CODE_GRAD`),
  KEY `REL_RECOMPENSA_TO_TIPO_RECOMPENSAS` (`CODE_TIPO`),
  CONSTRAINT `REL_RECOMPENSA_TO_CODE_GRADUACAO` FOREIGN KEY (`CODE_GRAD`) REFERENCES `PLANOS__GRADUACOES` (`CODE`),
  CONSTRAINT `REL_RECOMPENSA_TO_TIPO_RECOMPENSAS` FOREIGN KEY (`CODE_TIPO`) REFERENCES `RECOMPENSAS__TIPO` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=504 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__REGISTRO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER_ORIGEM` bigint(25) DEFAULT NULL COMMENT 'USUARIO QUE DISPAROU A RECOMPENSA',
  `UID_USER` bigint(25) DEFAULT NULL,
  `RECOMPENSA_CODE` bigint(25) DEFAULT NULL,
  `RECONPENSA_TIPO_CODE` bigint(25) DEFAULT NULL,
  `NIVEL` int(11) DEFAULT NULL,
  `TOTAL` double(18,2) NOT NULL,
  `DATA_HORA` timestamp NOT NULL DEFAULT current_timestamp(),
  `OBSERVACAO` varchar(500) NOT NULL COMMENT 'CASO SEJA INSERIDO MANUALMENTE\r\n',
  `RESPONSAVEL` bigint(25) DEFAULT NULL COMMENT 'RESPONSÁVEL PELA INSERÇÃO MANUAL',
  `PENDENTE` tinyint(1) DEFAULT 1,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `REL_REGISTRO_RECONPENSA_CODE` (`RECOMPENSA_CODE`),
  KEY `REL_REGISTRO_USER` (`UID_USER`),
  KEY `REL_REGISTRO_RESPONSAVEL` (`RESPONSAVEL`),
  KEY `REL_REGISTRO_RECONPENSA_TIPO_CODE` (`RECONPENSA_TIPO_CODE`),
  KEY `REL_REGISTRO_RECONPENSA_NIVEL` (`NIVEL`),
  KEY `REL_REGISTRO_USER_ORIGEM` (`UID_USER_ORIGEM`),
  CONSTRAINT `REL_REGISTRO_RECONPENSA_CODE` FOREIGN KEY (`RECOMPENSA_CODE`) REFERENCES `RECOMPENSAS` (`CODE`),
  CONSTRAINT `REL_REGISTRO_RECONPENSA_TIPO_CODE` FOREIGN KEY (`RECONPENSA_TIPO_CODE`) REFERENCES `RECOMPENSAS__TIPO` (`CODE`),
  CONSTRAINT `REL_REGISTRO_RESPONSAVEL` FOREIGN KEY (`RESPONSAVEL`) REFERENCES `USUARIOS` (`UID`),
  CONSTRAINT `REL_REGISTRO_USER` FOREIGN KEY (`UID_USER`) REFERENCES `USUARIOS` (`UID`),
  CONSTRAINT `REL_REGISTRO_USER_ORIGEM` FOREIGN KEY (`UID_USER_ORIGEM`) REFERENCES `USUARIOS` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `RECOMPENSAS__TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `ORIGEM` int(11) NOT NULL DEFAULT 0,
  `RECOMPENSA_CODE` bigint(25) DEFAULT NULL,
  `TIPO` varchar(300) NOT NULL,
  `TIPO_DISTRIBUICAO` int(11) DEFAULT 1,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  `BINARIO` tinyint(1) NOT NULL DEFAULT 0,
  `COMPRA_LOJA` tinyint(1) NOT NULL DEFAULT 0,
  `CADASTRO` tinyint(1) NOT NULL DEFAULT 0,
  `FINANCEIRO` tinyint(1) NOT NULL DEFAULT 0,
  `ATIVACAO` tinyint(1) NOT NULL DEFAULT 0,
  `RENOVACAO` tinyint(1) NOT NULL DEFAULT 0,
  `PENDENTE` tinyint(1) NOT NULL DEFAULT 1,
  `RECEBE_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `RECEBE_NAO_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `PAGA_NAO_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `PAGA_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `PAI_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `PAI_NAO_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `VALOR` decimal(18,2) DEFAULT NULL,
  `TIPO_CALCULO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE_2` (`CODE`),
  KEY `CODE` (`CODE`),
  KEY `REL_TIPO_RECONPENSA_CODE` (`RECOMPENSA_CODE`),
  KEY `REL_TIPO__RECONPENSA_DISTRIBUICAO` (`TIPO_DISTRIBUICAO`),
  KEY `REL_TIPO__RECONPENSA_CALCULO` (`TIPO_CALCULO`),
  CONSTRAINT `REL_TIPO_RECONPENSA_CODE` FOREIGN KEY (`RECOMPENSA_CODE`) REFERENCES `RECOMPENSAS` (`CODE`),
  CONSTRAINT `REL_TIPO__RECONPENSA_CALCULO` FOREIGN KEY (`TIPO_CALCULO`) REFERENCES `RECOMPENSAS__UNIDADE_CALCULO` (`CODE`),
  CONSTRAINT `REL_TIPO__RECONPENSA_DISTRIBUICAO` FOREIGN KEY (`TIPO_DISTRIBUICAO`) REFERENCES `RECOMPENSAS__DISTRIBUICAO` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS `RECOMPENSAS__UNIDADE_CALCULO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `NOME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

/*!40000 ALTER TABLE `RECOMPENSAS__UNIDADE_CALCULO` DISABLE KEYS */;
INSERT INTO `RECOMPENSAS__UNIDADE_CALCULO` (`ID`, `CODE`, `NOME`) VALUES
	(1, 1, 'Porcentagem'),
	(2, 2, 'Fixo'),
	(3, 3, 'Dividido');
/*!40000 ALTER TABLE `RECOMPENSAS__UNIDADE_CALCULO` ENABLE KEYS */;
