CREATE TABLE IF NOT EXISTS `PLANOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `PLANO` varchar(300) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `PLANOS__GRADUACOES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `POSICAO` int(11) NOT NULL,
  `CODE` bigint(25) NOT NULL,
  `CODE_PLANO` bigint(25) NOT NULL,
  `GRADUACAO` varchar(200) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `REDE_TOTAL` int(11) NOT NULL,
  `REDE_DIRETA` int(11) NOT NULL,
  `MATRIZ_FECHADA` tinyint(1) NOT NULL DEFAULT 0,
  `MATRIZ_PERNA_MENOR` int(11) NOT NULL,
  `EXCLUIDO` float NOT NULL,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `VALOR` decimal(18,2) NOT NULL DEFAULT 129.90,
  `RENOVACAO` int(1) NOT NULL DEFAULT 0,
  `PACOTE_RENTAL_COIN` bigint(25) DEFAULT NULL,
  `GETWAY_BTC` tinyint(1) NOT NULL DEFAULT 1,
  `GETWAY_PIX` tinyint(1) NOT NULL DEFAULT 1,
  `GETWAY_MP` tinyint(1) NOT NULL DEFAULT 1,
  `GETWAY_SALDO` tinyint(1) NOT NULL DEFAULT 0,
  `GETWAY_BOLETO` tinyint(1) NOT NULL DEFAULT 0,
  `GETWAY_CARTAO` tinyint(1) NOT NULL DEFAULT 0,
  `GETWAY_PEC` tinyint(1) NOT NULL DEFAULT 0,
  `QUALI_PAI` tinyint(1) NOT NULL DEFAULT 0,
  `QUALI_AVO` tinyint(1) NOT NULL DEFAULT 0,
  `QUALI_ORIGEM` tinyint(1) NOT NULL DEFAULT 0,
  `QUALI_PAI_ORIGEM` tinyint(1) NOT NULL DEFAULT 0,
  `QUALI_UPLINE` tinyint(1) NOT NULL DEFAULT 0,
  `NIVEL_QUALI_UPLINE` int(11) NOT NULL DEFAULT 1,
  `LISTA_NO_CADASTRO` tinyint(1) NOT NULL DEFAULT 0,
  `QTDD_EXPIRE` int(11) NOT NULL DEFAULT 30 COMMENT 'QTDD EM NUMEROS QUE EXPIRA O PLANO',
  `EXPIRE_TYPE` varchar(100) NOT NULL DEFAULT 'DAYS' COMMENT 'SECONDS, MINUTES, HOUR, DAY, WEEK, MONTH, YEAR',
  `PARALELOS` int(11) NOT NULL DEFAULT 1 COMMENT 'MÁXIMO DE INSTANCIAS POR USUARIO EM PARALELO',
  `VALOR_MULTA` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT 'VALOR ( FLOAT ) MONETARIO OU PERCENTUAL DA MULTA',
  `TIPO_MULTA` int(11) NOT NULL DEFAULT 1 COMMENT '1=% | 2=Fixo  ',
  `PERIODO_MULTA` int(11) NOT NULL DEFAULT 3 COMMENT '1=DIA, 2=SEMANA, 3=MÊS, 4=ANO\r\n',
  `BLOCK_EXPIRE` int(1) NOT NULL DEFAULT 0 COMMENT 'BLOQUEIA ACESSO DO USUARIO QD EXPIRA',
  `PERM_RENOVA` int(1) NOT NULL DEFAULT 0 COMMENT 'PERMITE RENOVAÇÃO',
  `MULTA_ATRASO` int(1) NOT NULL DEFAULT 0 COMMENT 'PERMITE MULTA POR ATRASO DO PAGAMENTO',
  PRIMARY KEY (`ID`),
  KEY `REL_GRADUACOES_PLANO` (`CODE_PLANO`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PLANOS__PLANOS_REDE_QUALIFICADORES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PLANO` bigint(25) NOT NULL,
  `ID_GRADUACAO` bigint(25) DEFAULT NULL,
  `QUALIFICADOR_PLANO` bigint(25) DEFAULT NULL,
  `QUALIFICADOR_GRADUACAO` bigint(25) DEFAULT NULL,
  `QTDD_REDE` int(11) DEFAULT NULL,
  `NIVEL` int(11) DEFAULT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `ID_GRADUACAO` (`ID_GRADUACAO`),
  KEY `QUALIFICADOR_PLANO` (`QUALIFICADOR_PLANO`),
  KEY `QUALIFICADOR_GRADUACAO` (`QUALIFICADOR_GRADUACAO`),
  KEY `REL_QUALIFICA_NIVEL` (`NIVEL`),
  KEY `ID_PLANO` (`ID_PLANO`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `PLANOS__PLANO_ATIVO_QUALIFICADOR` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PLANO` bigint(25) NOT NULL,
  `ID_GRADUACAO` bigint(25) DEFAULT NULL,
  `QUALIFICADOR_PLANO` bigint(25) DEFAULT NULL,
  `QUALIFICADOR_GRADUACAO` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_GRADUACAO` (`ID_GRADUACAO`),
  KEY `QUALIFICADOR_PLANO` (`QUALIFICADOR_PLANO`),
  KEY `QUALIFICADOR_GRADUACAO` (`QUALIFICADOR_GRADUACAO`),
  KEY `REL_PLANO_ATIVO_QUALIFICADOR_PLANO_CODE` (`ID_PLANO`),
  CONSTRAINT `REL_PLANO_ATIVO_PLANO_GRAD` FOREIGN KEY (`ID_GRADUACAO`) REFERENCES `PLANOS__GRADUACOES` (`CODE`),
  CONSTRAINT `REL_PLANO_ATIVO_QUALIFICADOR_ATUAL` FOREIGN KEY (`QUALIFICADOR_PLANO`) REFERENCES `PLANOS` (`CODE`),
  CONSTRAINT `REL_PLANO_ATIVO_QUALIFICADOR_PLANO_CODE` FOREIGN KEY (`ID_PLANO`) REFERENCES `PLANOS` (`CODE`),
  CONSTRAINT `REL_PLANO_ATIVO_QUALIFICADOR_PLANO_GRAD` FOREIGN KEY (`QUALIFICADOR_GRADUACAO`) REFERENCES `PLANOS__GRADUACOES` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=182 DEFAULT CHARSET=utf8mb4;




CREATE TABLE IF NOT EXISTS `PLANOS__RECOMPENSA_QUALIFICADORES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PLANO_CODE` bigint(25) NOT NULL,
  `GRADUACAO_CODE` bigint(25) NOT NULL,
  `RECOMPENSA_CODE` bigint(25) DEFAULT NULL,
  `RECOMPENSA_TIPO_CODE` bigint(25) DEFAULT NULL,
  `VALOR_MINIMO` double(18,2) DEFAULT NULL,
  `QTDD_REDE` int(11) NOT NULL,
  `DIAS` int(11) NOT NULL,
  `NIVEL` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PLANOS__RECOMPENSA_QUALIFICADOR_NIVEL` (`NIVEL`),
  KEY `REL_RECOMPENSA_QUALI_PLANO_CODE` (`PLANO_CODE`),
  KEY `REL_RECOMPENSA_QUALI_GRAD_CODE` (`GRADUACAO_CODE`),
  KEY `REL_RECOMPENSA_QUALI_RECOMPENSA_CODE` (`RECOMPENSA_CODE`),
  KEY `REL_RECOMPENSA_QUALI_RECOMPENSA_TIPO_CODE` (`RECOMPENSA_TIPO_CODE`),
  
  CONSTRAINT `REL_RECOMPENSA_QUALI_GRAD_CODE` FOREIGN KEY (`GRADUACAO_CODE`) REFERENCES `PLANOS__GRADUACOES` (`CODE`),
  CONSTRAINT `REL_RECOMPENSA_QUALI_PLANO_CODE` FOREIGN KEY (`PLANO_CODE`) REFERENCES `PLANOS` (`CODE`),
  CONSTRAINT `REL_RECOMPENSA_QUALI_RECOMPENSA_CODE` FOREIGN KEY (`RECOMPENSA_CODE`) REFERENCES `RECOMPENSAS` (`CODE`),
  CONSTRAINT `REL_RECOMPENSA_QUALI_RECOMPENSA_TIPO_CODE` FOREIGN KEY (`RECOMPENSA_TIPO_CODE`) REFERENCES `RECOMPENSAS__TIPO` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS `PLANOS__USUARIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `UID_USER` bigint(25) NOT NULL,
  `CODE_PLANO` bigint(25) DEFAULT NULL,
  `CODE_GRADUACAO` bigint(25) NOT NULL,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `PERIODO_VIGENTE` timestamp NOT NULL DEFAULT current_timestamp(),
  `VENCIMENTO` datetime DEFAULT NULL,
  `EXPIRA_EM` datetime DEFAULT NULL,
  `PAGO_EM` datetime DEFAULT NULL,
  `UID_FATURA` varchar(50) DEFAULT NULL COMMENT 'UID FATURA EM ABERTO. QUANDO PAGAR, FICA COMO NULL\r\n',
  `ATIVO` int(1) NOT NULL DEFAULT 1,
  `EXCLUIDO` tinyint(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `ID` (`ID`),
  KEY `REL_PLANOS__USUARIOS_PLANO` (`CODE_PLANO`),
  KEY `REL_PLANOS__USUARIOS` (`UID_USER`),
  KEY `REL_PLANOS__USUARIOS_GRADUACAO` (`CODE_GRADUACAO`),
  KEY `UID_FATURA` (`UID_FATURA`),
  CONSTRAINT `REL_PLANO_UIDGRAD` FOREIGN KEY (`CODE_GRADUACAO`) REFERENCES `PLANOS__GRADUACOES` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `REL_PLANO_UIDPLANO` FOREIGN KEY (`CODE_PLANO`) REFERENCES `PLANOS` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `REL_PLANO_UIDUSER` FOREIGN KEY (`UID_USER`) REFERENCES `USUARIOS` (`UID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=64 DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `PLANOS__VOLUME_MATRIZ` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VOLUME` decimal(18,2) DEFAULT NULL,
  `MATRIZ` int(11) DEFAULT NULL,
  `CODE_PLANO` bigint(25) DEFAULT NULL,
  `CODE_GRADUACAO` bigint(25) DEFAULT NULL,
  `DIAS` int(11) NOT NULL,
  `NIVEL` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4;
