-- PROCEDURE: SP_GET_CICLOS_USUARIO;
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_GET_CICLOS_USUARIO`(IN UID_USER_PARAM BIGINT)
BEGIN
    SELECT
        AJUDA__USER_NIVEL.CICLO_COMPLETO,
        CICLO.UID_CICLO,
        AJUDA__USER_NIVEL.UID_USER,
        AJUDA__USER_NIVEL.NIVEL,
        AJUDA__USER_NIVEL.LUGAR_FILA,
        AJUDA__NIVEIS.VALOR_ENTRADA,
        (AJUDA__NIVEIS.VALOR_ENTRADA * AJUDA__NIVEIS.MULTIPLICA_FATOR) as META,
        SUM(CICLO.VALOR) AS TOTAL
    FROM
        AJUDA__CICLO CICLO
        LEFT JOIN
        AJUDA__USER_NIVEL ON AJUDA__USER_NIVEL.UID_CICLO=CICLO.UID_CICLO
        LEFT JOIN
        AJUDA__NIVEIS ON AJUDA__NIVEIS.NIVEL=AJUDA__USER_NIVEL.NIVEL
    WHERE 
        AJUDA__USER_NIVEL.UID_USER = UID_USER_PARAM
    GROUP BY 
        CICLO.UID_CICLO
    ORDER BY 
        AJUDA__USER_NIVEL.CICLO_COMPLETO, AJUDA__USER_NIVEL.LUGAR_FILA;
END;
