SET foreign_key_checks = 0;
CREATE TABLE IF NOT EXISTS `FINANCEIRO__MOVIMENTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `DE_QUEM` bigint(25) DEFAULT NULL,
  `PARA_QUEM` bigint(25) DEFAULT NULL,
  `VALOR` decimal(18,2) DEFAULT NULL,
  `JUSTIFICATIVA` varchar(500) DEFAULT NULL,
  `USER_VALIDADOR` bigint(25) DEFAULT NULL,
  `STATUS` int(11) DEFAULT 0,
  `TIPO` int(11) DEFAULT 0,
  `LINK_PAG` varchar(500) DEFAULT NULL,
  `UID_CARRINHO` bigint(25) DEFAULT NULL,
  `CRIADO_EM` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `MODIFICADO_EM` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FINANCEIRO__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `STATUS` varchar(200) NOT NULL,
  `DESCRICAO` text NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=95 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FINANCEIRO__TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(4) DEFAULT NULL,
  `TYPE` varchar(400) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `UID_PAI` bigint(25) DEFAULT NULL,
  `TIPO` int(11) NOT NULL,
  `NOME` varchar(300) NOT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `CEP` varchar(50) NOT NULL,
  `UF` varchar(4) NOT NULL,
  `CIDADE` varchar(150) NOT NULL,
  `COMPLEMENTO` varchar(300) NOT NULL,
  `NUMERO` int(6) NOT NULL,
  `LOGRADOURO` varchar(500) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `UID` (`UID`),
  KEY `REL_FRANQUIA_TIPO` (`TIPO`),
  KEY `REL_FRANQUIA_STATUS` (`STATUS`),
  KEY `REL_FRANQUIA_UID_MATRIZ` (`UID_PAI`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS__ESTOQUE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO` int(11) DEFAULT NULL,
  `ID_FRANQUIA` int(11) DEFAULT NULL,
  `QUANTIDADE` int(11) DEFAULT NULL,
  `VALOR_UNITARIO_COMPRA` decimal(18,2) DEFAULT NULL,
  `VALOR_UNITARIO_VENDA` decimal(18,2) DEFAULT NULL,
  `DATA_COMPRA` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS__LINIK_USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) NOT NULL,
  `UID_FRANQUIA` bigint(25) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `REL_FRANQUIA_LINK_FRANQUIA` (`UID_FRANQUIA`),
  KEY `UID_USER` (`UID_USER`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `STATUS` varchar(100) NOT NULL,
  `DESCRICAO` varchar(500) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS__TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(300) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS__TIPO_VINCULO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `VINCULO` varchar(200) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GALERIAS__GALERIAS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `UID_PLUGIN` bigint(25) DEFAULT NULL COMMENT 'REFERENCIA DO PLUGIN',
  `TITULO` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `REL_GALERIAS_PLUGIN` (`UID_PLUGIN`),
  KEY `UID` (`UID`),
  CONSTRAINT `REL_GALERIAS_PLUGIN` FOREIGN KEY (`UID_PLUGIN`) REFERENCES `GALERIAS__PLUGIN` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GALERIAS__IMAGENS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `UID_PLUGIN` bigint(25) DEFAULT NULL,
  `UID_GALERIA` bigint(25) DEFAULT NULL,
  `FILENAME` varchar(500) DEFAULT NULL COMMENT 'NOME DO ARQUIVO',
  `ORIGINAL_NAME` varchar(500) DEFAULT NULL COMMENT 'NOME ORIGINAL DO ARQUIVO',
  `MIME` varchar(300) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT '',
  `DESCRICAO` varchar(255) DEFAULT '',
  `PESO` int(11) DEFAULT NULL,
  `50x50` varchar(255) DEFAULT NULL,
  `100x100` varchar(255) DEFAULT NULL,
  `300x300` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY ` GALERIAS__IMAGENS_PLUGIN` (`UID_PLUGIN`),
  KEY `GALERIAS__IMAGENS_GALERIAS` (`UID_GALERIA`),
  CONSTRAINT ` GALERIAS__IMAGENS_PLUGIN` FOREIGN KEY (`UID_PLUGIN`) REFERENCES `GALERIAS__PLUGIN` (`UID`),
  CONSTRAINT `GALERIAS__IMAGENS_GALERIAS` FOREIGN KEY (`UID_GALERIA`) REFERENCES `GALERIAS__GALERIAS` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GALERIAS__PLUGIN` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `SLUG` varchar(255) DEFAULT NULL,
  `MULTIPLAS` tinyint(1) DEFAULT 1,
  `TAMANHO_THUMB` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UID_2` (`UID`),
  KEY `UID` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MIDIA__BANNER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PLUGIN` int(11) DEFAULT NULL,
  `LINK` varchar(300) DEFAULT NULL,
  `TARGET` set('_Self','_Blank') DEFAULT '_Self',
  `ANALITYCS` tinyint(1) NOT NULL DEFAULT 0,
  `CLICKTAG` varchar(300) DEFAULT NULL,
  `TITULO` varchar(300) DEFAULT NULL,
  `DESCRICAO` varchar(700) DEFAULT NULL,
  `STATUS` int(11) DEFAULT 4,
  `INICIA` datetime DEFAULT NULL,
  `TERMINA` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `REL_BANNER_PLUGIN` (`ID_PLUGIN`),
  KEY `REL_BANNER_STATUS` (`STATUS`),
  CONSTRAINT `REL_MIDIA_BANNER__PLUGIN` FOREIGN KEY (`ID_PLUGIN`) REFERENCES `MIDIA__PLUGIN` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=72 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MIDIA__FILES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_BANNER` int(11) NOT NULL,
  `ID_PLUGIN` int(11) NOT NULL,
  `NOME_ORIGINAL` varchar(400) NOT NULL,
  `PATH` varchar(400) NOT NULL,
  `FILENAME` varchar(300) NOT NULL,
  `MEDIA_QUERY` int(5) NOT NULL,
  `SIZE` varchar(50) NOT NULL,
  `TYPE` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `REL_FILE_PLUGIN` (`ID_PLUGIN`),
  KEY `REL_FILE_BANNER` (`ID_BANNER`),
  CONSTRAINT `REL_FILES_UID_MIDIA_BANNER` FOREIGN KEY (`ID_BANNER`) REFERENCES `MIDIA__BANNER` (`ID`),
  CONSTRAINT `REL_FILES_UID_MIDIA_PLUGIN` FOREIGN KEY (`ID_PLUGIN`) REFERENCES `MIDIA__PLUGIN` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=291 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MIDIA__PLUGIN` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(200) NOT NULL,
  `DESCRICAO` varchar(300) NOT NULL,
  `SLUG` varchar(200) NOT NULL,
  `RESPONSIVO` tinyint(1) NOT NULL DEFAULT 1,
  `MULTIPLOS` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  KEY `SLUG` (`SLUG`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MIDIA__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `NEWSLETTER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(300) DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `NOTIFICACOES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) NOT NULL,
  `UID_EMPREENDIMENTO` bigint(25) NOT NULL,
  `REMETENTE` bigint(25) NOT NULL,
  `PARAMS` text DEFAULT NULL,
  `TEMPLATE` int(3) DEFAULT NULL,
  `TITULO` varchar(200) NOT NULL,
  `MENSAGEM` text NOT NULL,
  `VISUALIZADO` tinyint(1) NOT NULL DEFAULT 0,
  `CRIADO_EM` datetime NOT NULL DEFAULT current_timestamp(),
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `DESTINO` (`UID_USER`),
  KEY `REMETENTE` (`REMETENTE`),
  KEY `TEMPLATE` (`TEMPLATE`),
  CONSTRAINT `DESTINO` FOREIGN KEY (`UID_USER`) REFERENCES `USUARIOS` (`UID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `REMETENTE` FOREIGN KEY (`REMETENTE`) REFERENCES `USUARIOS` (`UID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `TEMPLATE` FOREIGN KEY (`TEMPLATE`) REFERENCES `NOTIFICACOES_TEMPLATES` (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `NOTIFICACOES__TEMPLATES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(400) NOT NULL,
  `CODE` int(3) NOT NULL,
  `TEMPLATE` text NOT NULL,
  `NOME_VAR` varchar(300) NOT NULL,
  `BALAO_TOPO` text NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `NOME` varchar(200) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `OLD_VALOR` decimal(18,2) NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `STATUS` int(11) DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE_2` (`CODE`),
  KEY `REL_PROD_STATUS` (`STATUS`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__ADICIONAIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADICIONAL` varchar(300) NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `EXCLUIDO` int(1) DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__CARRINHO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO` int(11) DEFAULT 1,
  `UID_FRANQUIA` bigint(25) DEFAULT NULL,
  `UID_USER` bigint(25) DEFAULT NULL,
  `UID_PRODUTO` int(11) DEFAULT NULL,
  `ID_VARIACAO` int(11) DEFAULT NULL,
  `QTDD` int(11) NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `REGRA` int(11) NOT NULL,
  `ADICIONADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `REL_PRODUTO__CARRINHO_TIPO` (`TIPO`),
  KEY `REL_PRODUTO__CARRINHO_USER` (`UID_USER`),
  CONSTRAINT `REL_PRODUTO__CARRINHO_TIPO` FOREIGN KEY (`TIPO`) REFERENCES `PRODUTO__TIPO` (`CODE`),
  CONSTRAINT `REL_PRODUTO__CARRINHO_USER` FOREIGN KEY (`UID_USER`) REFERENCES `USUARIOS` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=401 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__CARRINHO_ADICIONAIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_FRANQUIA` bigint(25) NOT NULL,
  `UID_USER` bigint(25) NOT NULL,
  `ID_ITEM_CARRINHO` int(11) NOT NULL,
  `ID_PRODUTO` int(11) NOT NULL,
  `ID_VARIACAO` int(11) NOT NULL,
  `ID_ADICIONAL` int(11) NOT NULL,
  `QTDD` int(11) NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `AVATAR` varchar(300) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=136 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__CATEGORIAS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_FRANQUIA` bigint(25) NOT NULL,
  `UID_CATPAI` int(11) DEFAULT 0,
  `CATEGORIA` varchar(500) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__IMAGENS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PROD` int(11) NOT NULL,
  `ID_VARIACAO` int(11) NOT NULL,
  `ID_ADICIONAL` int(11) NOT NULL,
  `PATH` varchar(500) NOT NULL,
  `HASH` varchar(40) NOT NULL,
  `FILE` varchar(400) NOT NULL,
  `ORIGINAL_NOME` varchar(500) NOT NULL,
  `SIZE` varchar(200) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__LINK_ADICIONAIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO` int(11) NOT NULL,
  `ID_ADICIONAL` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__LINK_CAT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_FRANQUIA` bigint(11) NOT NULL,
  `UID_PROD` bigint(25) NOT NULL,
  `UID_CAT` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `STATUS` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(300) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__VARIACOES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_PRODUTO` int(11) NOT NULL,
  `COR` varchar(10) NOT NULL DEFAULT '#FFFFFF',
  `VARIACAO` varchar(250) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `STATUS` int(11) DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `QUEMSOMOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SESSAO` varchar(255) NOT NULL,
  `TITULO` varchar(255) NOT NULL,
  `TEXTO` text NOT NULL,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `QUEMSOMOS__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `SESSAO` varchar(255) NOT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `TEXTO` text DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__LGPD` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTEUDO` text NOT NULL,
  `ACTIVE` int(11) DEFAULT 1,
  `CREATED` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__LIMIT_ACCESS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ASSINATURA` varchar(100) NOT NULL,
  `DATA_HORA` timestamp NOT NULL DEFAULT current_timestamp(),
  `CONGELA_ATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=121 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__REGRAS_DE_TAXAS_E_BONUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VIGENTE` tinyint(1) NOT NULL,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `TICKS_CLUB` float NOT NULL,
  `MEMBROS` float NOT NULL,
  `PRODUTOR` float NOT NULL,
  `REDE` float NOT NULL,
  `VIP` float NOT NULL,
  `MERECIMENTO` float NOT NULL,
  `APOS_META` float NOT NULL,
  `ALCANCE` float NOT NULL,
  `ALCANCE_1` float NOT NULL,
  `ALCANCE_2` float NOT NULL,
  `ALCANCE_3` float NOT NULL,
  `1_NIVEL` float NOT NULL,
  `2_NIVEL` float NOT NULL,
  `3_NIVEL` float NOT NULL,
  `4_NIVEL` float NOT NULL,
  `5_NIVEL` float NOT NULL,
  `6_NIVEL` float NOT NULL,
  `7_NIVEL` float NOT NULL,
  `8_NIVEL` float NOT NULL,
  `TAXA_SAQUE` float NOT NULL,
  `TAXA_RECARGA` float NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID` (`ID`),
  KEY `CRIADO_EM` (`CRIADO_EM`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__REGRAS_PCT_COMISSAO_REVENDA` (
  `UID` int(11) NOT NULL AUTO_INCREMENT,
  `NIVEL` int(11) NOT NULL,
  `PCT` int(11) NOT NULL,
  PRIMARY KEY (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__TOKEN_ACCESS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HASH` varchar(280) DEFAULT NULL,
  `JSON` text DEFAULT NULL,
  `TIPO` int(11) NOT NULL,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `EXPIRE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `HASH` (`HASH`),
  KEY `REL_TOKEN_ACCESS_TYPE` (`TIPO`)
) ENGINE=InnoDB AUTO_INCREMENT=261 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__TYPE_TOKEN_ACCESS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `TIPO` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__VERSION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VERSION` float NOT NULL,
  `LABEL` varchar(500) NOT NULL,
  `RESET` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IDIOMA` enum('pt','en','es') DEFAULT 'pt',
  `FOOTER` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `HEADER` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `TIPO_ATUACAO` int(1) DEFAULT NULL COMMENT '1 = SERVIÇO\r\n2 = DOCUMENTAÇÃO',
  `FW_LANG` varchar(5) DEFAULT 'pt',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO_CONSULTORIA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) DEFAULT '',
  `DESCRICAO` varchar(255) DEFAULT '',
  `FW_LANG` varchar(5) DEFAULT 'pt',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO_PRODUTOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) DEFAULT '',
  `DESCRICAO` varchar(255) DEFAULT '',
  `FW_LANG` varchar(5) DEFAULT 'pt',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `TIPO_ATUACAO` int(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__CONTATO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TOP_TITLE` varchar(244) NOT NULL,
  `TITULO_FORM` varchar(255) DEFAULT NULL,
  `ADRESS_TITLE` varchar(255) DEFAULT NULL,
  `ADRESS_TEXT` varchar(255) DEFAULT NULL,
  `HORARIOS_TITLE` varchar(255) DEFAULT NULL,
  `HORARIOS_TEXT` varchar(255) DEFAULT NULL,
  `EMAILS_TITLE` varchar(255) DEFAULT NULL,
  `EMAILS_TEXT` varchar(255) DEFAULT NULL,
  `TEXTO_BOTAO` varchar(244) DEFAULT NULL,
  `PLACEHOLDER_NOME` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_EMAIL` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_TELEFONE` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_ASSUNTO` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_TEXTO` varchar(255) DEFAULT NULL,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__CONTATO__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `TOP_TITLE` varchar(244) DEFAULT NULL,
  `TITULO_FORM` varchar(255) DEFAULT NULL,
  `ADRESS_TITLE` varchar(255) DEFAULT NULL,
  `ADRESS_TEXT` varchar(255) DEFAULT NULL,
  `HORARIOS_TITLE` varchar(255) DEFAULT NULL,
  `HORARIOS_TEXT` varchar(255) DEFAULT NULL,
  `EMAILS_TITLE` varchar(255) DEFAULT NULL,
  `EMAILS_TEXT` varchar(255) DEFAULT NULL,
  `TEXTO_BOTAO` varchar(244) DEFAULT NULL,
  `PLACEHOLDER_NOME` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_EMAIL` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_TELEFONE` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_ASSUNTO` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_TEXTO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__HOME` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `OUTRAS_SOLUCOES` varchar(256) DEFAULT NULL,
  `OUTRAS_SOLUCOES_TXT` text DEFAULT NULL,
  `ANOS_EXP_NUM` int(11) NOT NULL DEFAULT 0,
  `ANOS_EXP_TXT` varchar(256) DEFAULT NULL,
  `ANOS_EXP_DESC` text DEFAULT NULL,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__HOME__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `OUTRAS_SOLUCOES` varchar(256) DEFAULT NULL,
  `OUTRAS_SOLUCOES_TXT` text DEFAULT NULL,
  `ANOS_EXP_NUM` int(11) DEFAULT NULL,
  `ANOS_EXP_TXT` varchar(256) DEFAULT NULL,
  `ANOS_EXP_DESC` text DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__SOBRE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SESSAO` varchar(255) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `CONTEUDO` text DEFAULT NULL,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__SOBRE__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `SESSAO` varchar(255) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `CONTEUDO` text DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__STATIC` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MENU_LABEL_HOME` varchar(100) DEFAULT NULL,
  `MENU_LABEL_EMPRESA` varchar(100) DEFAULT NULL,
  `MENU_LABEL_ATUACAO` varchar(100) DEFAULT NULL,
  `MENU_LABEL_DOC` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CLIENTES` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CASES` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CONTATO` varchar(100) DEFAULT NULL,
  `MENU_LINK_HOME` varchar(250) DEFAULT NULL,
  `MENU_LINK_EMPRESA` varchar(250) DEFAULT NULL,
  `MENU_LINK_ATUACAO` varchar(250) DEFAULT NULL,
  `MENU_LINK_DOC` varchar(250) DEFAULT NULL,
  `MENU_LINK_CLIENTES` varchar(250) DEFAULT NULL,
  `MENU_LINK_CASES` varchar(250) DEFAULT NULL,
  `MENU_LINK_CONTATO` varchar(250) DEFAULT NULL,
  `MENU_LABEL_ATUACAO_DOC` varchar(255) DEFAULT '',
  `MENU_LINK_ATUACAO_DOC` varchar(255) DEFAULT '',
  `MENU_LABEL_ATUACAO_PROD` varchar(255) DEFAULT '',
  `MENU_LINK_ATUACAO_PROD` varchar(255) DEFAULT '',
  `MENU_LABEL_ATUACAO_CONS` varchar(255) DEFAULT '',
  `MENU_LINK_ATUACAO_CONS` varchar(255) DEFAULT '',
  `HEADER_NEWSLETTER_TITULO` varchar(250) DEFAULT NULL,
  `HEADER_NEWSLETTER_DESC` varchar(250) DEFAULT NULL,
  `HEADER_PLACEHOLDER` varchar(250) DEFAULT NULL,
  `HEADER_ABOUT_TITULO` varchar(250) DEFAULT NULL,
  `HEADER_ABOUT_DESC` varchar(250) DEFAULT NULL,
  `HEADER_TELEFONE` varchar(250) DEFAULT NULL,
  `HEADER_ENDERECO` varchar(250) DEFAULT NULL,
  `HEADER_NEWSLETTER_BUTTON` varchar(250) DEFAULT NULL,
  `HEADER_COPYRIGHT` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_TITULO` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_DESC` varchar(250) DEFAULT NULL,
  `FOOTER_PLACEHOLDER` varchar(250) DEFAULT NULL,
  `FOOTER_ABOUT_TITULO` varchar(250) DEFAULT NULL,
  `FOOTER_ABOUT_DESC` varchar(250) DEFAULT NULL,
  `FOOTER_TELEFONE` varchar(250) DEFAULT NULL,
  `FOOTER_ENDERECO` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_BUTTON` varchar(250) DEFAULT NULL,
  `FOOTER_COPYRIGHT` varchar(250) DEFAULT NULL,
  `FOOTER_LINK_COPYRIGHT` varchar(250) DEFAULT NULL,
  `TITULO_AREAS` varchar(255) DEFAULT NULL,
  `TITULO_CLIENTES` varchar(255) DEFAULT '',
  `TITULO_ATUACAO_CONSULT` varchar(255) DEFAULT '',
  `TITULO_ATUACAO_DOC` varchar(255) DEFAULT '',
  `TITULO_ATUACAO_PROD` varchar(255) DEFAULT '',
  `TITULO_SOBRE_NOS` varchar(255) DEFAULT '',
  `TITULO_CONTATOS` varchar(255) DEFAULT '',
  `FW_LANG` varchar(5) DEFAULT 'pt',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__STATIC__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `MENU_LABEL_HOME` varchar(100) DEFAULT NULL,
  `MENU_LABEL_EMPRESA` varchar(100) DEFAULT NULL,
  `MENU_LABEL_ATUACAO` varchar(100) DEFAULT NULL,
  `MENU_LABEL_DOC` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CLIENTES` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CASES` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CONTATO` varchar(100) DEFAULT NULL,
  `MENU_LINK_HOME` varchar(250) DEFAULT NULL,
  `MENU_LINK_EMPRESA` varchar(250) DEFAULT NULL,
  `MENU_LINK_ATUACAO` varchar(250) DEFAULT NULL,
  `MENU_LINK_DOC` varchar(250) DEFAULT NULL,
  `MENU_LINK_CLIENTES` varchar(250) DEFAULT NULL,
  `MENU_LINK_CASES` varchar(250) DEFAULT NULL,
  `MENU_LINK_CONTATO` varchar(250) DEFAULT NULL,
  `MENU_LABEL_ATUACAO_DOC` varchar(255) DEFAULT NULL,
  `MENU_LINK_ATUACAO_DOC` varchar(255) DEFAULT NULL,
  `MENU_LABEL_ATUACAO_PROD` varchar(255) DEFAULT NULL,
  `MENU_LINK_ATUACAO_PROD` varchar(255) DEFAULT NULL,
  `MENU_LABEL_ATUACAO_CONS` varchar(255) DEFAULT NULL,
  `MENU_LINK_ATUACAO_CONS` varchar(255) DEFAULT NULL,
  `HEADER_NEWSLETTER_TITULO` varchar(250) DEFAULT NULL,
  `HEADER_NEWSLETTER_DESC` varchar(250) DEFAULT NULL,
  `HEADER_PLACEHOLDER` varchar(250) DEFAULT NULL,
  `HEADER_ABOUT_TITULO` varchar(250) DEFAULT NULL,
  `HEADER_ABOUT_DESC` varchar(250) DEFAULT NULL,
  `HEADER_TELEFONE` varchar(250) DEFAULT NULL,
  `HEADER_ENDERECO` varchar(250) DEFAULT NULL,
  `HEADER_NEWSLETTER_BUTTON` varchar(250) DEFAULT NULL,
  `HEADER_COPYRIGHT` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_TITULO` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_DESC` varchar(250) DEFAULT NULL,
  `FOOTER_PLACEHOLDER` varchar(250) DEFAULT NULL,
  `FOOTER_ABOUT_TITULO` varchar(250) DEFAULT NULL,
  `FOOTER_ABOUT_DESC` varchar(250) DEFAULT NULL,
  `FOOTER_TELEFONE` varchar(250) DEFAULT NULL,
  `FOOTER_ENDERECO` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_BUTTON` varchar(250) DEFAULT NULL,
  `FOOTER_COPYRIGHT` varchar(250) DEFAULT NULL,
  `FOOTER_LINK_COPYRIGHT` varchar(250) DEFAULT NULL,
  `TITULO_AREAS` varchar(255) DEFAULT NULL,
  `TITULO_CLIENTES` varchar(255) DEFAULT NULL,
  `TITULO_ATUACAO_CONSULT` varchar(255) DEFAULT NULL,
  `TITULO_ATUACAO_DOC` varchar(255) DEFAULT NULL,
  `TITULO_ATUACAO_PROD` varchar(255) DEFAULT NULL,
  `TITULO_SOBRE_NOS` varchar(255) DEFAULT NULL,
  `TITULO_CONTATOS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `TIPO_PROFILE` int(11) DEFAULT 0,
  `LEVEL_PERMISSION` int(11) DEFAULT NULL,
  `FIRSTACCESS` tinyint(1) NOT NULL DEFAULT 1,
  `UID_EMPRESA` int(11) DEFAULT NULL,
  `STATUS` int(10) DEFAULT 0,
  `BLACKLIST` tinyint(1) NOT NULL DEFAULT 0,
  `NOME` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `LOGIN` varchar(50) DEFAULT NULL,
  `SENHA` varchar(256) DEFAULT NULL,
  `SALT` varchar(100) NOT NULL,
  `NOVA_SENHA` varchar(300) DEFAULT NULL,
  `TIPO_DOCUMENTO` int(11) DEFAULT NULL,
  `TIPO_PESSOA` int(11) DEFAULT NULL,
  `2FA` varchar(256) DEFAULT NULL,
  `2FA_ACTIVE` tinyint(1) NOT NULL DEFAULT 0,
  `EMAIL_VALIDADO` tinyint(1) NOT NULL DEFAULT 0,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `UID` (`UID`),
  KEY `REL_TIPO_PESSOA` (`TIPO_PESSOA`),
  KEY `REL_TIPO_DOC` (`TIPO_DOCUMENTO`),
  KEY `REL_USER_STATUS` (`STATUS`),
  KEY `REL_USER_TIPO_PROFILE` (`TIPO_PROFILE`),
  CONSTRAINT `REL_TIPO_DOC` FOREIGN KEY (`TIPO_DOCUMENTO`) REFERENCES `USUARIOS__TIPO_DOCUMENTO` (`CODE`),
  CONSTRAINT `REL_TIPO_PESSOA` FOREIGN KEY (`TIPO_PESSOA`) REFERENCES `USUARIOS__TIPO_PESSOA` (`CODE`),
  CONSTRAINT `REL_USER_STATUS` FOREIGN KEY (`STATUS`) REFERENCES `USUARIOS__STATUS` (`CODE`),
  CONSTRAINT `REL_USER_TIPO_PROFILE` FOREIGN KEY (`TIPO_PROFILE`) REFERENCES `USUARIOS__TIPO_PROFILE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=211 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__DADOS_PROJETO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) DEFAULT NULL,
  `CPF` varchar(50) DEFAULT NULL,
  `RG` varchar(50) DEFAULT NULL,
  `LISTA_UPLOAD` text DEFAULT NULL,
  `DESCRICAO` varchar(300) DEFAULT NULL,
  `ATENDIDO_IMOBILIARIA` varchar(300) DEFAULT NULL,
  `CORRETOR_NOME` varchar(300) DEFAULT NULL,
  `INSTAGRAM` varchar(300) DEFAULT NULL,
  `NACIONALIDADE` varchar(50) DEFAULT NULL,
  `PERFIL_INVESTIDOR` varchar(50) DEFAULT NULL,
  `PROFISSAO` varchar(100) DEFAULT NULL,
  `REGIME_BENS` varchar(50) DEFAULT NULL,
  `RENDA_ATE` varchar(50) DEFAULT NULL,
  `RENDA_DE` varchar(50) DEFAULT NULL,
  `TIPO_CONTA_TRADICIONAL` int(1) DEFAULT 0,
  `TIPO_CONTA_DIGITAL` int(1) DEFAULT 0,
  `TIPO_CONTA_EXCHANGE` int(1) DEFAULT 0,
  `UNIDADE` varchar(200) DEFAULT NULL,
  `VEICULO_REPASSE` varchar(5) DEFAULT NULL,
  `TELEFONE` varchar(50) DEFAULT NULL,
  `WHATSAPP` varchar(50) DEFAULT NULL,
  `DATA_INSERT` timestamp NOT NULL DEFAULT current_timestamp(),
  `OBS` text DEFAULT NULL,
  `LOGRADOURO` varchar(300) DEFAULT NULL,
  `CIDADE` varchar(100) DEFAULT NULL,
  `ESTADO` varchar(50) DEFAULT NULL,
  `CEP` varchar(50) DEFAULT NULL,
  `NUMERO` varchar(50) DEFAULT NULL,
  `COMPLEMENTO` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `REL_UUSER_DATA_ID_USER` (`UID_USER`),
  CONSTRAINT `REL_UUSER_DATA_ID_USER` FOREIGN KEY (`UID_USER`) REFERENCES `USUARIOS` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=665 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__DISPOSITIVOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) NOT NULL,
  `ASSINATURA` varchar(256) DEFAULT NULL,
  `JSON_RESPONSE` text DEFAULT NULL,
  `AUTORIZADO` int(1) NOT NULL DEFAULT 0,
  `CONGELA_ATE` datetime DEFAULT NULL,
  `MODO_SEGURO` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=161 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(10) NOT NULL,
  `TITULO` varchar(100) NOT NULL,
  `DESCRICAO` varchar(300) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__TIPO_DOCUMENTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__TIPO_PESSOA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__TIPO_PROFILE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `NOME` varchar(300) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__VINCULO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USUARIO_A` bigint(25) DEFAULT NULL COMMENT 'segue | de quem | paga | pai',
  `USUARIO_B` bigint(25) DEFAULT NULL COMMENT 'seguido | pra quem | recebe | filho',
  `REFERENCIA` varchar(100) DEFAULT NULL,
  `TIPO` int(11) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `INDICE_REFERENCIA` (`REFERENCIA`),
  KEY `USUARIO_A` (`USUARIO_A`),
  KEY `USUARIO_B` (`USUARIO_B`),
  KEY `REL-USER-VINCULO__TIPO` (`TIPO`),
  CONSTRAINT `REL-USER-VINCULO__TIPO` FOREIGN KEY (`TIPO`) REFERENCES `USUARIOS__VINCULO_TIPO` (`CODE`),
  CONSTRAINT `REL-USER-VINCULO__USER-A` FOREIGN KEY (`USUARIO_A`) REFERENCES `USUARIOS` (`UID`),
  CONSTRAINT `REL-USER-VINCULO__USER-B` FOREIGN KEY (`USUARIO_B`) REFERENCES `USUARIOS` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__VINCULO_TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(200) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

SET foreign_key_checks = 1;