-- EVENTO: EXPIRA_TOKEN_ACCESS

CREATE DEFINER=`app`@`146.190.115.50` EVENT `EXPIRA_TOKEN_ACCESS` ON SCHEDULE EVERY 10 SECOND STARTS '2023-12-13 00:05:59' 
ON COMPLETION NOT PRESERVE ENABLE DO DELETE FROM SYSTEM__TOKEN_ACCESS WHERE EXPIRE < NOW() OR EXPIRE IS NULL;


-- EVENTO: LIMPA_SYSTEM__LIMIT_ACCESS

CREATE DEFINER=`app`@`146.190.115.50` EVENT `LIMPA_SYSTEM__LIMIT_ACCESS` ON SCHEDULE EVERY 30 SECOND STARTS '2023-12-13 00:05:59' ON COMPLETION NOT PRESERVE ENABLE DO DELETE FROM SYSTEM__LIMIT_ACCESS 
WHERE ((DATA_HORA < DATE_SUB(NOW(), INTERVAL 2 HOUR) AND CONGELA_ATE IS NULL) OR(CONGELA_ATE < DATE_SUB(NOW(), INTERVAL 2 HOUR)));
