-- TRIGGER: UID_GALERIAS;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID_GALERIAS` BEFORE INSERT ON `GALERIAS__GALERIAS` FOR EACH ROW SET new.UID=FLOOR(RAND()*9007199254740991)+1;

-- TRIGGER: UID_GALERIAS_IMAGES;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID_GALERIAS_IMAGES` BEFORE INSERT ON `GALERIAS__IMAGENS` FOR EACH ROW SET new.UID=FLOOR(RAND()*9007199254740991)+1;

-- TRIGGER: UID_PLUGIN_GALERIAS;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID_PLUGIN_GALERIAS` BEFORE INSERT ON `GALERIAS__PLUGIN`
FOR EACH ROW SET new.UID=FLOOR(RAND()*9007199254740991)+1;

-- TRIGGER: UPDATE__QUEMSOMOS;
CREATE DEFINER=`root`@`localhost` TRIGGER `UPDATE__QUEMSOMOS` AFTER UPDATE ON `QUEMSOMOS` FOR EACH ROW BEGIN
		    DECLARE record_count INT;
			SET @permitir_atualizacao = 1;
			SET @record_count = ( SELECT COUNT(*) FROM QUEMSOMOS__TRANSLATE WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG );
			IF  @record_count > 0 THEN 
				UPDATE QUEMSOMOS__TRANSLATE SET 
						SESSAO=IF(OLD.SESSAO!=NEW.SESSAO, NEW.SESSAO, SESSAO),
                        TITULO=IF(OLD.TITULO!=NEW.TITULO, NEW.TITULO, TITULO),
					 	TEXTO=IF(OLD.TEXTO!=NEW.TEXTO, NEW.TEXTO, TEXTO)
				WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG; 
			ELSE
				INSERT INTO QUEMSOMOS__TRANSLATE ( SESSAO,TITULO,TEXTO, ID_FW_PAI, FW_LANG) VALUES (NEW.SESSAO, NEW.TITULO,NEW.TEXTO,NEW.ID, NEW.FW_LANG);
			END IF; 

		END;

-- TRIGGER: INSERT__TEMPLATE__AREAS_ATUACAO;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__AREAS_ATUACAO AFTER INSERT ON TEMPLATE__AREAS_ATUACAO
		FOR EACH ROW BEGIN
			SET @permitir_atualizacao= 1;
			INSERT INTO TEMPLATE__AREAS_ATUACAO__TRANSLATE (TITULO,DESCRICAO,TIPO_ATUACAO, ID_FW_PAI, FW_LANG) VALUES (NEW.TITULO,NEW.DESCRICAO,NEW.TIPO_ATUACAO, NEW.ID, 'pt');
			INSERT INTO TEMPLATE__AREAS_ATUACAO__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'en');
			INSERT INTO TEMPLATE__AREAS_ATUACAO__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'es');
	END;

-- TRIGGER: UPDATE__TEMPLATE__AREAS_ATUACAO;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__AREAS_ATUACAO AFTER UPDATE ON TEMPLATE__AREAS_ATUACAO FOR EACH ROW		BEGIN
		    DECLARE record_count INT;
			SET @permitir_atualizacao = 1;
			SET @record_count = ( SELECT COUNT(*) FROM TEMPLATE__AREAS_ATUACAO__TRANSLATE WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG );
			IF  @record_count > 0 THEN 
				UPDATE TEMPLATE__AREAS_ATUACAO__TRANSLATE SET 
						TITULO=IF(OLD.TITULO!=NEW.TITULO, NEW.TITULO, TITULO),
					 	DESCRICAO=IF(OLD.DESCRICAO!=NEW.DESCRICAO, NEW.DESCRICAO, DESCRICAO),
					 	TIPO_ATUACAO=IF(OLD.TIPO_ATUACAO!=NEW.TIPO_ATUACAO, NEW.TIPO_ATUACAO, TIPO_ATUACAO)
				WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__AREAS_ATUACAO__TRANSLATE ( TITULO,DESCRICAO,TIPO_ATUACAO, ID_FW_PAI, FW_LANG) VALUES ( NEW.TITULO,NEW.DESCRICAO,NEW.TIPO_ATUACAO,NEW.ID, NEW.FW_LANG);
			END IF; 

		END;

-- TRIGGER: DELETE__TEMPLATE__AREAS_ATUACAO;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__AREAS_ATUACAO AFTER DELETE ON TEMPLATE__AREAS_ATUACAO FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__AREAS_ATUACAO__TRANSLATE WHERE ID_FW_PAI=OLD.ID; 
	END;

-- TRIGGER: INSERT__TEMPLATE__AREAS_ATUACAO_CONSULTORIA;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__AREAS_ATUACAO_CONSULTORIA AFTER INSERT ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA
		FOR EACH ROW BEGIN
			SET @permitir_atualizacao= 1;
			INSERT INTO TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE (TITULO,DESCRICAO, ID_FW_PAI, FW_LANG) VALUES (NEW.TITULO,NEW.DESCRICAO, NEW.ID, 'pt');
			INSERT INTO TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'en');
			INSERT INTO TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'es');
	END;

-- TRIGGER: UPDATE__TEMPLATE__AREAS_ATUACAO_CONSULTORIA;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__AREAS_ATUACAO_CONSULTORIA AFTER UPDATE ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA FOR EACH ROW		BEGIN
		    DECLARE record_count INT;
			SET @permitir_atualizacao = 1;
			SET @record_count = ( SELECT COUNT(*) FROM TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG );
			IF  @record_count > 0 THEN 
				UPDATE TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE SET 
						TITULO=IF(OLD.TITULO!=NEW.TITULO, NEW.TITULO, TITULO),
					 	DESCRICAO=IF(OLD.DESCRICAO!=NEW.DESCRICAO, NEW.DESCRICAO, DESCRICAO)
				WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE ( TITULO,DESCRICAO, ID_FW_PAI, FW_LANG) VALUES ( NEW.TITULO,NEW.DESCRICAO,NEW.ID, NEW.FW_LANG);
			END IF; 

		END;

-- TRIGGER: DELETE__TEMPLATE__AREAS_ATUACAO_CONSULTORIA;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__AREAS_ATUACAO_CONSULTORIA AFTER DELETE ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE WHERE ID_FW_PAI=OLD.ID; 
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: INSERT__TEMPLATE__AREAS_ATUACAO_PRODUTOS;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__AREAS_ATUACAO_PRODUTOS AFTER INSERT ON TEMPLATE__AREAS_ATUACAO_PRODUTOS
		FOR EACH ROW BEGIN
			SET @permitir_atualizacao= 1;
			INSERT INTO TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE (TITULO,DESCRICAO, ID_FW_PAI, FW_LANG) VALUES (NEW.TITULO,NEW.DESCRICAO, NEW.ID, 'pt');
			INSERT INTO TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'en');
			INSERT INTO TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'es');
	END;

-- TRIGGER: UPDATE__TEMPLATE__AREAS_ATUACAO_PRODUTOS;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__AREAS_ATUACAO_PRODUTOS AFTER UPDATE ON TEMPLATE__AREAS_ATUACAO_PRODUTOS FOR EACH ROW		BEGIN
		    DECLARE record_count INT;
			SET @permitir_atualizacao = 1;
			SET @record_count = ( SELECT COUNT(*) FROM TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG );
			IF  @record_count > 0 THEN 
				UPDATE TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE SET 
						TITULO=IF(OLD.TITULO!=NEW.TITULO, NEW.TITULO, TITULO),
					 	DESCRICAO=IF(OLD.DESCRICAO!=NEW.DESCRICAO, NEW.DESCRICAO, DESCRICAO)
				WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE ( TITULO,DESCRICAO, ID_FW_PAI, FW_LANG) VALUES ( NEW.TITULO,NEW.DESCRICAO,NEW.ID, NEW.FW_LANG);
			END IF; 

		END;

-- TRIGGER: DELETE__TEMPLATE__AREAS_ATUACAO_PRODUTOS;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__AREAS_ATUACAO_PRODUTOS AFTER DELETE ON TEMPLATE__AREAS_ATUACAO_PRODUTOS FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE WHERE ID_FW_PAI=OLD.ID; 
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__AREAS_ATUACAO__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__AREAS_ATUACAO__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__AREAS_ATUACAO__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: INSERT__TEMPLATE__CONTATO;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__CONTATO AFTER INSERT ON TEMPLATE__CONTATO
		FOR EACH ROW BEGIN
			SET @permitir_atualizacao= 1;
			INSERT INTO TEMPLATE__CONTATO__TRANSLATE (TOP_TITLE,TITULO_FORM,ADRESS_TITLE,ADRESS_TEXT,HORARIOS_TITLE,HORARIOS_TEXT,EMAILS_TITLE,EMAILS_TEXT,TEXTO_BOTAO,PLACEHOLDER_NOME,PLACEHOLDER_EMAIL,PLACEHOLDER_TELEFONE,PLACEHOLDER_ASSUNTO,PLACEHOLDER_TEXTO, ID_FW_PAI, FW_LANG) VALUES (NEW.TOP_TITLE,NEW.TITULO_FORM,NEW.ADRESS_TITLE,NEW.ADRESS_TEXT,NEW.HORARIOS_TITLE,NEW.HORARIOS_TEXT,NEW.EMAILS_TITLE,NEW.EMAILS_TEXT,NEW.TEXTO_BOTAO,NEW.PLACEHOLDER_NOME,NEW.PLACEHOLDER_EMAIL,NEW.PLACEHOLDER_TELEFONE,NEW.PLACEHOLDER_ASSUNTO,NEW.PLACEHOLDER_TEXTO, NEW.ID, 'pt');
			INSERT INTO TEMPLATE__CONTATO__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'en');
			INSERT INTO TEMPLATE__CONTATO__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'es');
	END;

-- TRIGGER: UPDATE__TEMPLATE__CONTATO;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__CONTATO AFTER UPDATE ON TEMPLATE__CONTATO FOR EACH ROW		BEGIN
		    DECLARE record_count INT;
			SET @permitir_atualizacao = 1;
			SET @record_count = ( SELECT COUNT(*) FROM TEMPLATE__CONTATO__TRANSLATE WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG );
			IF  @record_count > 0 THEN 
				UPDATE TEMPLATE__CONTATO__TRANSLATE SET 
						TOP_TITLE=IF(OLD.TOP_TITLE!=NEW.TOP_TITLE, NEW.TOP_TITLE, TOP_TITLE),
					 	TITULO_FORM=IF(OLD.TITULO_FORM!=NEW.TITULO_FORM, NEW.TITULO_FORM, TITULO_FORM),
					 	ADRESS_TITLE=IF(OLD.ADRESS_TITLE!=NEW.ADRESS_TITLE, NEW.ADRESS_TITLE, ADRESS_TITLE),
					 	ADRESS_TEXT=IF(OLD.ADRESS_TEXT!=NEW.ADRESS_TEXT, NEW.ADRESS_TEXT, ADRESS_TEXT),
					 	HORARIOS_TITLE=IF(OLD.HORARIOS_TITLE!=NEW.HORARIOS_TITLE, NEW.HORARIOS_TITLE, HORARIOS_TITLE),
					 	HORARIOS_TEXT=IF(OLD.HORARIOS_TEXT!=NEW.HORARIOS_TEXT, NEW.HORARIOS_TEXT, HORARIOS_TEXT),
					 	EMAILS_TITLE=IF(OLD.EMAILS_TITLE!=NEW.EMAILS_TITLE, NEW.EMAILS_TITLE, EMAILS_TITLE),
					 	EMAILS_TEXT=IF(OLD.EMAILS_TEXT!=NEW.EMAILS_TEXT, NEW.EMAILS_TEXT, EMAILS_TEXT),
					 	TEXTO_BOTAO=IF(OLD.TEXTO_BOTAO!=NEW.TEXTO_BOTAO, NEW.TEXTO_BOTAO, TEXTO_BOTAO),
					 	PLACEHOLDER_NOME=IF(OLD.PLACEHOLDER_NOME!=NEW.PLACEHOLDER_NOME, NEW.PLACEHOLDER_NOME, PLACEHOLDER_NOME),
					 	PLACEHOLDER_EMAIL=IF(OLD.PLACEHOLDER_EMAIL!=NEW.PLACEHOLDER_EMAIL, NEW.PLACEHOLDER_EMAIL, PLACEHOLDER_EMAIL),
					 	PLACEHOLDER_TELEFONE=IF(OLD.PLACEHOLDER_TELEFONE!=NEW.PLACEHOLDER_TELEFONE, NEW.PLACEHOLDER_TELEFONE, PLACEHOLDER_TELEFONE),
					 	PLACEHOLDER_ASSUNTO=IF(OLD.PLACEHOLDER_ASSUNTO!=NEW.PLACEHOLDER_ASSUNTO, NEW.PLACEHOLDER_ASSUNTO, PLACEHOLDER_ASSUNTO),
					 	PLACEHOLDER_TEXTO=IF(OLD.PLACEHOLDER_TEXTO!=NEW.PLACEHOLDER_TEXTO, NEW.PLACEHOLDER_TEXTO, PLACEHOLDER_TEXTO)
				WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__CONTATO__TRANSLATE ( TOP_TITLE,TITULO_FORM,ADRESS_TITLE,ADRESS_TEXT,HORARIOS_TITLE,HORARIOS_TEXT,EMAILS_TITLE,EMAILS_TEXT,TEXTO_BOTAO,PLACEHOLDER_NOME,PLACEHOLDER_EMAIL,PLACEHOLDER_TELEFONE,PLACEHOLDER_ASSUNTO,PLACEHOLDER_TEXTO, ID_FW_PAI, FW_LANG) VALUES ( NEW.TOP_TITLE,NEW.TITULO_FORM,NEW.ADRESS_TITLE,NEW.ADRESS_TEXT,NEW.HORARIOS_TITLE,NEW.HORARIOS_TEXT,NEW.EMAILS_TITLE,NEW.EMAILS_TEXT,NEW.TEXTO_BOTAO,NEW.PLACEHOLDER_NOME,NEW.PLACEHOLDER_EMAIL,NEW.PLACEHOLDER_TELEFONE,NEW.PLACEHOLDER_ASSUNTO,NEW.PLACEHOLDER_TEXTO,NEW.ID, NEW.FW_LANG);
			END IF; 

		END;

-- TRIGGER: DELETE__TEMPLATE__CONTATO;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__CONTATO AFTER DELETE ON TEMPLATE__CONTATO FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__CONTATO__TRANSLATE WHERE ID_FW_PAI=OLD.ID; 
	END;

-- TRIGGER: TEMPLATE__CONTATO__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__CONTATO__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__CONTATO__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__CONTATO__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__CONTATO__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__CONTATO__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__CONTATO__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__CONTATO__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__CONTATO__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: INSERT__TEMPLATE__HOME;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__HOME AFTER INSERT ON TEMPLATE__HOME
		FOR EACH ROW BEGIN
			SET @permitir_atualizacao= 1;
			INSERT INTO TEMPLATE__HOME__TRANSLATE (OUTRAS_SOLUCOES,OUTRAS_SOLUCOES_TXT,ANOS_EXP_NUM,ANOS_EXP_TXT,ANOS_EXP_DESC, ID_FW_PAI, FW_LANG) VALUES (NEW.OUTRAS_SOLUCOES,NEW.OUTRAS_SOLUCOES_TXT,NEW.ANOS_EXP_NUM,NEW.ANOS_EXP_TXT,NEW.ANOS_EXP_DESC, NEW.ID, 'pt');
			INSERT INTO TEMPLATE__HOME__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'en');
			INSERT INTO TEMPLATE__HOME__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'es');
	END;

-- TRIGGER: UPDATE__TEMPLATE__HOME;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__HOME AFTER UPDATE ON TEMPLATE__HOME FOR EACH ROW		BEGIN
		    DECLARE record_count INT;
			SET @permitir_atualizacao = 1;
			SET @record_count = ( SELECT COUNT(*) FROM TEMPLATE__HOME__TRANSLATE WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG );
			IF  @record_count > 0 THEN 
				UPDATE TEMPLATE__HOME__TRANSLATE SET 
						OUTRAS_SOLUCOES=IF(OLD.OUTRAS_SOLUCOES!=NEW.OUTRAS_SOLUCOES, NEW.OUTRAS_SOLUCOES, OUTRAS_SOLUCOES),
					 	OUTRAS_SOLUCOES_TXT=IF(OLD.OUTRAS_SOLUCOES_TXT!=NEW.OUTRAS_SOLUCOES_TXT, NEW.OUTRAS_SOLUCOES_TXT, OUTRAS_SOLUCOES_TXT),
					 	ANOS_EXP_NUM=IF(OLD.ANOS_EXP_NUM!=NEW.ANOS_EXP_NUM, NEW.ANOS_EXP_NUM, ANOS_EXP_NUM),
					 	ANOS_EXP_TXT=IF(OLD.ANOS_EXP_TXT!=NEW.ANOS_EXP_TXT, NEW.ANOS_EXP_TXT, ANOS_EXP_TXT),
					 	ANOS_EXP_DESC=IF(OLD.ANOS_EXP_DESC!=NEW.ANOS_EXP_DESC, NEW.ANOS_EXP_DESC, ANOS_EXP_DESC)
				WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__HOME__TRANSLATE ( OUTRAS_SOLUCOES,OUTRAS_SOLUCOES_TXT,ANOS_EXP_NUM,ANOS_EXP_TXT,ANOS_EXP_DESC, ID_FW_PAI, FW_LANG) VALUES ( NEW.OUTRAS_SOLUCOES,NEW.OUTRAS_SOLUCOES_TXT,NEW.ANOS_EXP_NUM,NEW.ANOS_EXP_TXT,NEW.ANOS_EXP_DESC,NEW.ID, NEW.FW_LANG);
			END IF; 

		END;

-- TRIGGER: DELETE__TEMPLATE__HOME;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__HOME AFTER DELETE ON TEMPLATE__HOME FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__HOME__TRANSLATE WHERE ID_FW_PAI=OLD.ID; 
	END;

-- TRIGGER: TEMPLATE__HOME__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__HOME__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__HOME__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__HOME__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__HOME__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__HOME__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__HOME__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__HOME__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__HOME__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: INSERT__TEMPLATE__SOBRE;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__SOBRE AFTER INSERT ON TEMPLATE__SOBRE
		FOR EACH ROW BEGIN
			SET @permitir_atualizacao= 1;
			INSERT INTO TEMPLATE__SOBRE__TRANSLATE (SESSAO,TITULO,CONTEUDO, ID_FW_PAI, FW_LANG) VALUES (NEW.SESSAO,NEW.TITULO,NEW.CONTEUDO, NEW.ID, 'pt');
			INSERT INTO TEMPLATE__SOBRE__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'en');
			INSERT INTO TEMPLATE__SOBRE__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'es');
	END;

-- TRIGGER: UPDATE__TEMPLATE__SOBRE;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__SOBRE AFTER UPDATE ON TEMPLATE__SOBRE FOR EACH ROW		BEGIN
		    DECLARE record_count INT;
			SET @permitir_atualizacao = 1;
			SET @record_count = ( SELECT COUNT(*) FROM TEMPLATE__SOBRE__TRANSLATE WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG );
			IF  @record_count > 0 THEN 
				UPDATE TEMPLATE__SOBRE__TRANSLATE SET 
						SESSAO=IF(OLD.SESSAO!=NEW.SESSAO, NEW.SESSAO, SESSAO),
					 	TITULO=IF(OLD.TITULO!=NEW.TITULO, NEW.TITULO, TITULO),
					 	CONTEUDO=IF(OLD.CONTEUDO!=NEW.CONTEUDO, NEW.CONTEUDO, CONTEUDO)
				WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__SOBRE__TRANSLATE ( SESSAO,TITULO,CONTEUDO, ID_FW_PAI, FW_LANG) VALUES ( NEW.SESSAO,NEW.TITULO,NEW.CONTEUDO,NEW.ID, NEW.FW_LANG);
			END IF; 

		END;

-- TRIGGER: DELETE__TEMPLATE__SOBRE;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__SOBRE AFTER DELETE ON TEMPLATE__SOBRE FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__SOBRE__TRANSLATE WHERE ID_FW_PAI=OLD.ID; 
	END;

-- TRIGGER: TEMPLATE__SOBRE__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__SOBRE__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__SOBRE__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__SOBRE__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__SOBRE__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__SOBRE__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__SOBRE__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__SOBRE__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__SOBRE__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: INSERT__TEMPLATE__STATIC;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__STATIC AFTER INSERT ON TEMPLATE__STATIC
		FOR EACH ROW BEGIN
			SET @permitir_atualizacao= 1;
			INSERT INTO TEMPLATE__STATIC__TRANSLATE (MENU_LABEL_HOME,MENU_LABEL_EMPRESA,MENU_LABEL_ATUACAO,MENU_LABEL_DOC,MENU_LABEL_CLIENTES,MENU_LABEL_CASES,MENU_LABEL_CONTATO,MENU_LINK_HOME,MENU_LINK_EMPRESA,MENU_LINK_ATUACAO,MENU_LINK_DOC,MENU_LINK_CLIENTES,MENU_LINK_CASES,MENU_LINK_CONTATO,MENU_LABEL_ATUACAO_DOC,MENU_LINK_ATUACAO_DOC,MENU_LABEL_ATUACAO_PROD,MENU_LINK_ATUACAO_PROD,MENU_LABEL_ATUACAO_CONS,MENU_LINK_ATUACAO_CONS,HEADER_NEWSLETTER_TITULO,HEADER_NEWSLETTER_DESC,HEADER_PLACEHOLDER,HEADER_ABOUT_TITULO,HEADER_ABOUT_DESC,HEADER_TELEFONE,HEADER_ENDERECO,HEADER_NEWSLETTER_BUTTON,HEADER_COPYRIGHT,FOOTER_NEWSLETTER_TITULO,FOOTER_NEWSLETTER_DESC,FOOTER_PLACEHOLDER,FOOTER_ABOUT_TITULO,FOOTER_ABOUT_DESC,FOOTER_TELEFONE,FOOTER_ENDERECO,FOOTER_NEWSLETTER_BUTTON,FOOTER_COPYRIGHT,FOOTER_LINK_COPYRIGHT,TITULO_AREAS,TITULO_CLIENTES,TITULO_ATUACAO_CONSULT,TITULO_ATUACAO_DOC,TITULO_ATUACAO_PROD,TITULO_SOBRE_NOS,TITULO_CONTATOS, ID_FW_PAI, FW_LANG) VALUES (NEW.MENU_LABEL_HOME,NEW.MENU_LABEL_EMPRESA,NEW.MENU_LABEL_ATUACAO,NEW.MENU_LABEL_DOC,NEW.MENU_LABEL_CLIENTES,NEW.MENU_LABEL_CASES,NEW.MENU_LABEL_CONTATO,NEW.MENU_LINK_HOME,NEW.MENU_LINK_EMPRESA,NEW.MENU_LINK_ATUACAO,NEW.MENU_LINK_DOC,NEW.MENU_LINK_CLIENTES,NEW.MENU_LINK_CASES,NEW.MENU_LINK_CONTATO,NEW.MENU_LABEL_ATUACAO_DOC,NEW.MENU_LINK_ATUACAO_DOC,NEW.MENU_LABEL_ATUACAO_PROD,NEW.MENU_LINK_ATUACAO_PROD,NEW.MENU_LABEL_ATUACAO_CONS,NEW.MENU_LINK_ATUACAO_CONS,NEW.HEADER_NEWSLETTER_TITULO,NEW.HEADER_NEWSLETTER_DESC,NEW.HEADER_PLACEHOLDER,NEW.HEADER_ABOUT_TITULO,NEW.HEADER_ABOUT_DESC,NEW.HEADER_TELEFONE,NEW.HEADER_ENDERECO,NEW.HEADER_NEWSLETTER_BUTTON,NEW.HEADER_COPYRIGHT,NEW.FOOTER_NEWSLETTER_TITULO,NEW.FOOTER_NEWSLETTER_DESC,NEW.FOOTER_PLACEHOLDER,NEW.FOOTER_ABOUT_TITULO,NEW.FOOTER_ABOUT_DESC,NEW.FOOTER_TELEFONE,NEW.FOOTER_ENDERECO,NEW.FOOTER_NEWSLETTER_BUTTON,NEW.FOOTER_COPYRIGHT,NEW.FOOTER_LINK_COPYRIGHT,NEW.TITULO_AREAS,NEW.TITULO_CLIENTES,NEW.TITULO_ATUACAO_CONSULT,NEW.TITULO_ATUACAO_DOC,NEW.TITULO_ATUACAO_PROD,NEW.TITULO_SOBRE_NOS,NEW.TITULO_CONTATOS, NEW.ID, 'pt');
			INSERT INTO TEMPLATE__STATIC__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'en');
			INSERT INTO TEMPLATE__STATIC__TRANSLATE (ID_FW_PAI, FW_LANG) VALUES (NEW.ID, 'es');
	END;

-- TRIGGER: UPDATE__TEMPLATE__STATIC;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__STATIC AFTER UPDATE ON TEMPLATE__STATIC FOR EACH ROW		BEGIN
		    DECLARE record_count INT;
			SET @permitir_atualizacao = 1;
			SET @record_count = ( SELECT COUNT(*) FROM TEMPLATE__STATIC__TRANSLATE WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG );
			IF  @record_count > 0 THEN 
				UPDATE TEMPLATE__STATIC__TRANSLATE SET 
						MENU_LABEL_HOME=IF(OLD.MENU_LABEL_HOME!=NEW.MENU_LABEL_HOME, NEW.MENU_LABEL_HOME, MENU_LABEL_HOME),
					 	MENU_LABEL_EMPRESA=IF(OLD.MENU_LABEL_EMPRESA!=NEW.MENU_LABEL_EMPRESA, NEW.MENU_LABEL_EMPRESA, MENU_LABEL_EMPRESA),
					 	MENU_LABEL_ATUACAO=IF(OLD.MENU_LABEL_ATUACAO!=NEW.MENU_LABEL_ATUACAO, NEW.MENU_LABEL_ATUACAO, MENU_LABEL_ATUACAO),
					 	MENU_LABEL_DOC=IF(OLD.MENU_LABEL_DOC!=NEW.MENU_LABEL_DOC, NEW.MENU_LABEL_DOC, MENU_LABEL_DOC),
					 	MENU_LABEL_CLIENTES=IF(OLD.MENU_LABEL_CLIENTES!=NEW.MENU_LABEL_CLIENTES, NEW.MENU_LABEL_CLIENTES, MENU_LABEL_CLIENTES),
					 	MENU_LABEL_CASES=IF(OLD.MENU_LABEL_CASES!=NEW.MENU_LABEL_CASES, NEW.MENU_LABEL_CASES, MENU_LABEL_CASES),
					 	MENU_LABEL_CONTATO=IF(OLD.MENU_LABEL_CONTATO!=NEW.MENU_LABEL_CONTATO, NEW.MENU_LABEL_CONTATO, MENU_LABEL_CONTATO),
					 	MENU_LINK_HOME=IF(OLD.MENU_LINK_HOME!=NEW.MENU_LINK_HOME, NEW.MENU_LINK_HOME, MENU_LINK_HOME),
					 	MENU_LINK_EMPRESA=IF(OLD.MENU_LINK_EMPRESA!=NEW.MENU_LINK_EMPRESA, NEW.MENU_LINK_EMPRESA, MENU_LINK_EMPRESA),
					 	MENU_LINK_ATUACAO=IF(OLD.MENU_LINK_ATUACAO!=NEW.MENU_LINK_ATUACAO, NEW.MENU_LINK_ATUACAO, MENU_LINK_ATUACAO),
					 	MENU_LINK_DOC=IF(OLD.MENU_LINK_DOC!=NEW.MENU_LINK_DOC, NEW.MENU_LINK_DOC, MENU_LINK_DOC),
					 	MENU_LINK_CLIENTES=IF(OLD.MENU_LINK_CLIENTES!=NEW.MENU_LINK_CLIENTES, NEW.MENU_LINK_CLIENTES, MENU_LINK_CLIENTES),
					 	MENU_LINK_CASES=IF(OLD.MENU_LINK_CASES!=NEW.MENU_LINK_CASES, NEW.MENU_LINK_CASES, MENU_LINK_CASES),
					 	MENU_LINK_CONTATO=IF(OLD.MENU_LINK_CONTATO!=NEW.MENU_LINK_CONTATO, NEW.MENU_LINK_CONTATO, MENU_LINK_CONTATO),
					 	MENU_LABEL_ATUACAO_DOC=IF(OLD.MENU_LABEL_ATUACAO_DOC!=NEW.MENU_LABEL_ATUACAO_DOC, NEW.MENU_LABEL_ATUACAO_DOC, MENU_LABEL_ATUACAO_DOC),
					 	MENU_LINK_ATUACAO_DOC=IF(OLD.MENU_LINK_ATUACAO_DOC!=NEW.MENU_LINK_ATUACAO_DOC, NEW.MENU_LINK_ATUACAO_DOC, MENU_LINK_ATUACAO_DOC),
					 	MENU_LABEL_ATUACAO_PROD=IF(OLD.MENU_LABEL_ATUACAO_PROD!=NEW.MENU_LABEL_ATUACAO_PROD, NEW.MENU_LABEL_ATUACAO_PROD, MENU_LABEL_ATUACAO_PROD),
					 	MENU_LINK_ATUACAO_PROD=IF(OLD.MENU_LINK_ATUACAO_PROD!=NEW.MENU_LINK_ATUACAO_PROD, NEW.MENU_LINK_ATUACAO_PROD, MENU_LINK_ATUACAO_PROD),
					 	MENU_LABEL_ATUACAO_CONS=IF(OLD.MENU_LABEL_ATUACAO_CONS!=NEW.MENU_LABEL_ATUACAO_CONS, NEW.MENU_LABEL_ATUACAO_CONS, MENU_LABEL_ATUACAO_CONS),
					 	MENU_LINK_ATUACAO_CONS=IF(OLD.MENU_LINK_ATUACAO_CONS!=NEW.MENU_LINK_ATUACAO_CONS, NEW.MENU_LINK_ATUACAO_CONS, MENU_LINK_ATUACAO_CONS),
					 	HEADER_NEWSLETTER_TITULO=IF(OLD.HEADER_NEWSLETTER_TITULO!=NEW.HEADER_NEWSLETTER_TITULO, NEW.HEADER_NEWSLETTER_TITULO, HEADER_NEWSLETTER_TITULO),
					 	HEADER_NEWSLETTER_DESC=IF(OLD.HEADER_NEWSLETTER_DESC!=NEW.HEADER_NEWSLETTER_DESC, NEW.HEADER_NEWSLETTER_DESC, HEADER_NEWSLETTER_DESC),
					 	HEADER_PLACEHOLDER=IF(OLD.HEADER_PLACEHOLDER!=NEW.HEADER_PLACEHOLDER, NEW.HEADER_PLACEHOLDER, HEADER_PLACEHOLDER),
					 	HEADER_ABOUT_TITULO=IF(OLD.HEADER_ABOUT_TITULO!=NEW.HEADER_ABOUT_TITULO, NEW.HEADER_ABOUT_TITULO, HEADER_ABOUT_TITULO),
					 	HEADER_ABOUT_DESC=IF(OLD.HEADER_ABOUT_DESC!=NEW.HEADER_ABOUT_DESC, NEW.HEADER_ABOUT_DESC, HEADER_ABOUT_DESC),
					 	HEADER_TELEFONE=IF(OLD.HEADER_TELEFONE!=NEW.HEADER_TELEFONE, NEW.HEADER_TELEFONE, HEADER_TELEFONE),
					 	HEADER_ENDERECO=IF(OLD.HEADER_ENDERECO!=NEW.HEADER_ENDERECO, NEW.HEADER_ENDERECO, HEADER_ENDERECO),
					 	HEADER_NEWSLETTER_BUTTON=IF(OLD.HEADER_NEWSLETTER_BUTTON!=NEW.HEADER_NEWSLETTER_BUTTON, NEW.HEADER_NEWSLETTER_BUTTON, HEADER_NEWSLETTER_BUTTON),
					 	HEADER_COPYRIGHT=IF(OLD.HEADER_COPYRIGHT!=NEW.HEADER_COPYRIGHT, NEW.HEADER_COPYRIGHT, HEADER_COPYRIGHT),
					 	FOOTER_NEWSLETTER_TITULO=IF(OLD.FOOTER_NEWSLETTER_TITULO!=NEW.FOOTER_NEWSLETTER_TITULO, NEW.FOOTER_NEWSLETTER_TITULO, FOOTER_NEWSLETTER_TITULO),
					 	FOOTER_NEWSLETTER_DESC=IF(OLD.FOOTER_NEWSLETTER_DESC!=NEW.FOOTER_NEWSLETTER_DESC, NEW.FOOTER_NEWSLETTER_DESC, FOOTER_NEWSLETTER_DESC),
					 	FOOTER_PLACEHOLDER=IF(OLD.FOOTER_PLACEHOLDER!=NEW.FOOTER_PLACEHOLDER, NEW.FOOTER_PLACEHOLDER, FOOTER_PLACEHOLDER),
					 	FOOTER_ABOUT_TITULO=IF(OLD.FOOTER_ABOUT_TITULO!=NEW.FOOTER_ABOUT_TITULO, NEW.FOOTER_ABOUT_TITULO, FOOTER_ABOUT_TITULO),
					 	FOOTER_ABOUT_DESC=IF(OLD.FOOTER_ABOUT_DESC!=NEW.FOOTER_ABOUT_DESC, NEW.FOOTER_ABOUT_DESC, FOOTER_ABOUT_DESC),
					 	FOOTER_TELEFONE=IF(OLD.FOOTER_TELEFONE!=NEW.FOOTER_TELEFONE, NEW.FOOTER_TELEFONE, FOOTER_TELEFONE),
					 	FOOTER_ENDERECO=IF(OLD.FOOTER_ENDERECO!=NEW.FOOTER_ENDERECO, NEW.FOOTER_ENDERECO, FOOTER_ENDERECO),
					 	FOOTER_NEWSLETTER_BUTTON=IF(OLD.FOOTER_NEWSLETTER_BUTTON!=NEW.FOOTER_NEWSLETTER_BUTTON, NEW.FOOTER_NEWSLETTER_BUTTON, FOOTER_NEWSLETTER_BUTTON),
					 	FOOTER_COPYRIGHT=IF(OLD.FOOTER_COPYRIGHT!=NEW.FOOTER_COPYRIGHT, NEW.FOOTER_COPYRIGHT, FOOTER_COPYRIGHT),
					 	FOOTER_LINK_COPYRIGHT=IF(OLD.FOOTER_LINK_COPYRIGHT!=NEW.FOOTER_LINK_COPYRIGHT, NEW.FOOTER_LINK_COPYRIGHT, FOOTER_LINK_COPYRIGHT),
					 	TITULO_AREAS=IF(OLD.TITULO_AREAS!=NEW.TITULO_AREAS, NEW.TITULO_AREAS, TITULO_AREAS),
					 	TITULO_CLIENTES=IF(OLD.TITULO_CLIENTES!=NEW.TITULO_CLIENTES, NEW.TITULO_CLIENTES, TITULO_CLIENTES),
					 	TITULO_ATUACAO_CONSULT=IF(OLD.TITULO_ATUACAO_CONSULT!=NEW.TITULO_ATUACAO_CONSULT, NEW.TITULO_ATUACAO_CONSULT, TITULO_ATUACAO_CONSULT),
					 	TITULO_ATUACAO_DOC=IF(OLD.TITULO_ATUACAO_DOC!=NEW.TITULO_ATUACAO_DOC, NEW.TITULO_ATUACAO_DOC, TITULO_ATUACAO_DOC),
					 	TITULO_ATUACAO_PROD=IF(OLD.TITULO_ATUACAO_PROD!=NEW.TITULO_ATUACAO_PROD, NEW.TITULO_ATUACAO_PROD, TITULO_ATUACAO_PROD),
					 	TITULO_SOBRE_NOS=IF(OLD.TITULO_SOBRE_NOS!=NEW.TITULO_SOBRE_NOS, NEW.TITULO_SOBRE_NOS, TITULO_SOBRE_NOS),
					 	TITULO_CONTATOS=IF(OLD.TITULO_CONTATOS!=NEW.TITULO_CONTATOS, NEW.TITULO_CONTATOS, TITULO_CONTATOS)
				WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__STATIC__TRANSLATE ( MENU_LABEL_HOME,MENU_LABEL_EMPRESA,MENU_LABEL_ATUACAO,MENU_LABEL_DOC,MENU_LABEL_CLIENTES,MENU_LABEL_CASES,MENU_LABEL_CONTATO,MENU_LINK_HOME,MENU_LINK_EMPRESA,MENU_LINK_ATUACAO,MENU_LINK_DOC,MENU_LINK_CLIENTES,MENU_LINK_CASES,MENU_LINK_CONTATO,MENU_LABEL_ATUACAO_DOC,MENU_LINK_ATUACAO_DOC,MENU_LABEL_ATUACAO_PROD,MENU_LINK_ATUACAO_PROD,MENU_LABEL_ATUACAO_CONS,MENU_LINK_ATUACAO_CONS,HEADER_NEWSLETTER_TITULO,HEADER_NEWSLETTER_DESC,HEADER_PLACEHOLDER,HEADER_ABOUT_TITULO,HEADER_ABOUT_DESC,HEADER_TELEFONE,HEADER_ENDERECO,HEADER_NEWSLETTER_BUTTON,HEADER_COPYRIGHT,FOOTER_NEWSLETTER_TITULO,FOOTER_NEWSLETTER_DESC,FOOTER_PLACEHOLDER,FOOTER_ABOUT_TITULO,FOOTER_ABOUT_DESC,FOOTER_TELEFONE,FOOTER_ENDERECO,FOOTER_NEWSLETTER_BUTTON,FOOTER_COPYRIGHT,FOOTER_LINK_COPYRIGHT,TITULO_AREAS,TITULO_CLIENTES,TITULO_ATUACAO_CONSULT,TITULO_ATUACAO_DOC,TITULO_ATUACAO_PROD,TITULO_SOBRE_NOS,TITULO_CONTATOS, ID_FW_PAI, FW_LANG) VALUES ( NEW.MENU_LABEL_HOME,NEW.MENU_LABEL_EMPRESA,NEW.MENU_LABEL_ATUACAO,NEW.MENU_LABEL_DOC,NEW.MENU_LABEL_CLIENTES,NEW.MENU_LABEL_CASES,NEW.MENU_LABEL_CONTATO,NEW.MENU_LINK_HOME,NEW.MENU_LINK_EMPRESA,NEW.MENU_LINK_ATUACAO,NEW.MENU_LINK_DOC,NEW.MENU_LINK_CLIENTES,NEW.MENU_LINK_CASES,NEW.MENU_LINK_CONTATO,NEW.MENU_LABEL_ATUACAO_DOC,NEW.MENU_LINK_ATUACAO_DOC,NEW.MENU_LABEL_ATUACAO_PROD,NEW.MENU_LINK_ATUACAO_PROD,NEW.MENU_LABEL_ATUACAO_CONS,NEW.MENU_LINK_ATUACAO_CONS,NEW.HEADER_NEWSLETTER_TITULO,NEW.HEADER_NEWSLETTER_DESC,NEW.HEADER_PLACEHOLDER,NEW.HEADER_ABOUT_TITULO,NEW.HEADER_ABOUT_DESC,NEW.HEADER_TELEFONE,NEW.HEADER_ENDERECO,NEW.HEADER_NEWSLETTER_BUTTON,NEW.HEADER_COPYRIGHT,NEW.FOOTER_NEWSLETTER_TITULO,NEW.FOOTER_NEWSLETTER_DESC,NEW.FOOTER_PLACEHOLDER,NEW.FOOTER_ABOUT_TITULO,NEW.FOOTER_ABOUT_DESC,NEW.FOOTER_TELEFONE,NEW.FOOTER_ENDERECO,NEW.FOOTER_NEWSLETTER_BUTTON,NEW.FOOTER_COPYRIGHT,NEW.FOOTER_LINK_COPYRIGHT,NEW.TITULO_AREAS,NEW.TITULO_CLIENTES,NEW.TITULO_ATUACAO_CONSULT,NEW.TITULO_ATUACAO_DOC,NEW.TITULO_ATUACAO_PROD,NEW.TITULO_SOBRE_NOS,NEW.TITULO_CONTATOS,NEW.ID, NEW.FW_LANG);
			END IF; 

		END;

-- TRIGGER: DELETE__TEMPLATE__STATIC;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__STATIC AFTER DELETE ON TEMPLATE__STATIC FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__STATIC__TRANSLATE WHERE ID_FW_PAI=OLD.ID; 
	END;

-- TRIGGER: TEMPLATE__STATIC__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__STATIC__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__STATIC__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__STATIC__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__STATIC__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__STATIC__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__STATIC__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__STATIC__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__STATIC__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: UID_USUARIOS;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID_USUARIOS` BEFORE INSERT ON `USUARIOS`
FOR EACH ROW SET new.UID=FLOOR(RAND()*9007199254740991)+1;

-- TRIGGER: INSERE_USUARIO_DADOS_PROJETO;
CREATE DEFINER=`root`@`localhost` TRIGGER `INSERE_USUARIO_DADOS_PROJETO` AFTER INSERT ON `USUARIOS`
FOR EACH ROW INSERT INTO USUARIOS__DADOS_PROJETO (UID_USER) VALUES (new.UID);

-- TRIGGER: DELETE_USUARIO_DADOS_PROJETO;
CREATE DEFINER=`root`@`localhost` TRIGGER `DELETE_USUARIO_DADOS_PROJETO` AFTER DELETE ON `USUARIOS`
FOR EACH ROW  DELETE FROM USUARIOS__DADOS_PROJETO WHERE UID_USER = OLD.UID;
