SET foreign_key_checks = 0;
CREATE TABLE IF NOT EXISTS `BLOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `PREVIA` varchar(300) DEFAULT NULL,
  `DESCRICAO` text DEFAULT NULL,
  `IMAGEM` varchar(255) DEFAULT '',
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FW_UID_LANG` (`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=67 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BLOG__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  `UID` bigint(25) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `PREVIA` varchar(300) DEFAULT NULL,
  `DESCRICAO` text DEFAULT NULL,
  `IMAGEM` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_FW_LANG` (`FW_LANG`,`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=103 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BOOK__FORMATOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `NOME` varchar(255) NOT NULL,
  `LARGURA` float NOT NULL,
  `ALTURA` float NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BOOK__PDFS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` int(11) NOT NULL,
  `UID_PROJECT` int(11) NOT NULL,
  `FILENAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BOOK__PROJECTS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `UID_USER` bigint(25) DEFAULT NULL,
  `TITULO` varchar(255) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `FORMATO` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `BOOK__PROJECT_TYPE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(150) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CONFIGS` (
  `WHATSAPP` varchar(255) DEFAULT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FONE` varchar(255) DEFAULT '',
  `LINKEDIN` varchar(255) DEFAULT '',
  `EMAIL` varchar(255) DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CURSOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) NOT NULL,
  `NOME` varchar(400) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `DESTAQUE_TOPO` varchar(200) DEFAULT NULL,
  `PIN` varchar(200) DEFAULT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CURSOS__AULAS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `CODE_MODULO` bigint(25) DEFAULT NULL,
  `CODE_CURSO` bigint(25) DEFAULT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`),
  KEY `REL_CURSOS__AULA_CURSO` (`CODE_CURSO`),
  KEY `REL_CURSOS__AULA_MODULO` (`CODE_MODULO`),
  CONSTRAINT `REL_CURSOS__AULA_CURSO` FOREIGN KEY (`CODE_CURSO`) REFERENCES `CURSOS` (`CODE`),
  CONSTRAINT `REL_CURSOS__AULA_MODULO` FOREIGN KEY (`CODE_MODULO`) REFERENCES `CURSOS__MODULOS` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CURSOS__MATERIAL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) NOT NULL,
  `CODE_AULA` bigint(25) NOT NULL,
  `CODE_MODULO` bigint(25) NOT NULL,
  `CODE_CURSO` bigint(25) NOT NULL,
  `NOME` varchar(300) NOT NULL,
  `ARQUIVO` varchar(500) NOT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`),
  KEY `CODE_AULA` (`CODE_AULA`),
  KEY `CODE_MODULO` (`CODE_MODULO`),
  KEY `CODE_CURSO` (`CODE_CURSO`),
  CONSTRAINT `REL_CURSOS__MATERIAL_AULA` FOREIGN KEY (`CODE_AULA`) REFERENCES `CURSOS__AULAS` (`CODE`),
  CONSTRAINT `REL_CURSOS__MATERIAL_CURSO` FOREIGN KEY (`CODE_CURSO`) REFERENCES `CURSOS` (`CODE`),
  CONSTRAINT `REL_CURSOS__MATERIAL_MODULO` FOREIGN KEY (`CODE_MODULO`) REFERENCES `CURSOS__MODULOS` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CURSOS__MATRICULA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `UID_USER` bigint(25) NOT NULL,
  `CODE_CURSO` bigint(25) NOT NULL,
  `DATA_ADESAO` date NOT NULL DEFAULT current_timestamp(),
  `DATA_RENOVACAO` date NOT NULL DEFAULT current_timestamp(),
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`),
  KEY `REL_CURSOS__MATRICULA_CURSO` (`CODE_CURSO`),
  KEY `UID_USER` (`UID_USER`),
  CONSTRAINT `REL_CURSOS__MATRICULA_CURSO` FOREIGN KEY (`CODE_CURSO`) REFERENCES `CURSOS` (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CURSOS__MODULOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `CODE_CURSO` bigint(25) DEFAULT NULL,
  `NOME` varchar(400) DEFAULT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`),
  KEY `REL_CURSOS__MODULO_CURSO` (`CODE_CURSO`),
  CONSTRAINT `REL_CURSOS__MODULO_CURSO` FOREIGN KEY (`CODE_CURSO`) REFERENCES `CURSOS` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FINANCEIRO__MOVIMENTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `DE_QUEM` bigint(25) DEFAULT NULL,
  `PARA_QUEM` bigint(25) DEFAULT NULL,
  `VALOR` decimal(18,2) DEFAULT NULL,
  `JUSTIFICATIVA` varchar(500) DEFAULT NULL,
  `USER_VALIDADOR` bigint(25) DEFAULT NULL,
  `STATUS` int(11) DEFAULT 0,
  `TIPO` int(11) DEFAULT 0,
  `LINK_PAG` varchar(500) DEFAULT NULL,
  `UID_CARRINHO` bigint(25) DEFAULT NULL,
  `CRIADO_EM` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `MODIFICADO_EM` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FINANCEIRO__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `STATUS` varchar(200) NOT NULL,
  `DESCRICAO` text NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=95 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FINANCEIRO__TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(4) DEFAULT NULL,
  `TYPE` varchar(400) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `UID_PAI` bigint(25) DEFAULT NULL,
  `TIPO` int(11) NOT NULL,
  `NOME` varchar(300) NOT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `CEP` varchar(50) NOT NULL,
  `UF` varchar(4) NOT NULL,
  `CIDADE` varchar(150) NOT NULL,
  `COMPLEMENTO` varchar(300) NOT NULL,
  `NUMERO` int(6) NOT NULL,
  `LOGRADOURO` varchar(500) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `UID` (`UID`),
  KEY `REL_FRANQUIA_TIPO` (`TIPO`),
  KEY `REL_FRANQUIA_STATUS` (`STATUS`),
  KEY `REL_FRANQUIA_UID_MATRIZ` (`UID_PAI`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS__ESTOQUE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_FRANQUIA` bigint(25) DEFAULT NULL,
  `ID_PRODUTO` bigint(25) DEFAULT NULL,
  `QUANTIDADE` int(11) DEFAULT NULL,
  `VALOR_UNITARIO_COMPRA` decimal(18,2) DEFAULT NULL,
  `VALOR_UNITARIO_VENDA` decimal(18,2) DEFAULT NULL,
  `DATA_COMPRA` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS__LINIK_USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) NOT NULL,
  `UID_FRANQUIA` bigint(25) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `REL_FRANQUIA_LINK_FRANQUIA` (`UID_FRANQUIA`),
  KEY `UID_USER` (`UID_USER`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `STATUS` varchar(100) NOT NULL,
  `DESCRICAO` varchar(500) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS__TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(300) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `FRANQUIAS__TIPO_VINCULO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `VINCULO` varchar(200) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GALERIAS__GALERIAS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `UID_PLUGIN` bigint(25) DEFAULT NULL COMMENT 'REFERENCIA DO PLUGIN',
  `TITULO` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `REL_GALERIAS_PLUGIN` (`UID_PLUGIN`),
  KEY `UID` (`UID`),
  CONSTRAINT `REL_GALERIAS_PLUGIN` FOREIGN KEY (`UID_PLUGIN`) REFERENCES `GALERIAS__PLUGIN` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GALERIAS__IMAGENS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `UID_PLUGIN` bigint(25) DEFAULT NULL,
  `UID_GALERIA` bigint(25) DEFAULT NULL,
  `FILENAME` varchar(500) DEFAULT NULL COMMENT 'NOME DO ARQUIVO',
  `ORIGINAL_NAME` varchar(500) DEFAULT NULL COMMENT 'NOME ORIGINAL DO ARQUIVO',
  `MIME` varchar(300) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT '',
  `DESCRICAO` varchar(255) DEFAULT '',
  `PESO` int(11) DEFAULT NULL,
  `50x50` varchar(255) DEFAULT NULL,
  `100x100` varchar(255) DEFAULT NULL,
  `300x300` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY ` GALERIAS__IMAGENS_PLUGIN` (`UID_PLUGIN`),
  KEY `GALERIAS__IMAGENS_GALERIAS` (`UID_GALERIA`),
  CONSTRAINT ` GALERIAS__IMAGENS_PLUGIN` FOREIGN KEY (`UID_PLUGIN`) REFERENCES `GALERIAS__PLUGIN` (`UID`),
  CONSTRAINT `GALERIAS__IMAGENS_GALERIAS` FOREIGN KEY (`UID_GALERIA`) REFERENCES `GALERIAS__GALERIAS` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=122 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GALERIAS__PLUGIN` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `SLUG` varchar(255) DEFAULT NULL,
  `MULTIPLAS` tinyint(1) DEFAULT 1,
  `TAMANHO_THUMB` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UID_2` (`UID`),
  KEY `UID` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GEO__CIDADES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `NOME` varchar(255) DEFAULT NULL,
  `UF` int(2) DEFAULT NULL,
  `IBGE` int(7) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`),
  KEY `REL_CIDADE_UFs` (`UF`),
  CONSTRAINT `REL_CIDADE_UFs` FOREIGN KEY (`UF`) REFERENCES `GEO__UF` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=5596 DEFAULT CHARSET=utf8mb4 COMMENT='Municipios das Unidades Federativas';

CREATE TABLE IF NOT EXISTS `GEO__PAIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `NOME` varchar(60) DEFAULT NULL,
  `NOME_PT` varchar(60) DEFAULT NULL,
  `SIGLA` varchar(5) DEFAULT NULL,
  `BACEN` int(5) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE_2` (`CODE`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=255 DEFAULT CHARSET=utf8mb4 COMMENT='Países e Nações';

CREATE TABLE IF NOT EXISTS `GEO__UF` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `NOME` varchar(75) DEFAULT NULL,
  `UF` varchar(3) DEFAULT NULL,
  `IBGE` int(2) DEFAULT NULL,
  `PAIS` int(3) DEFAULT NULL,
  `DDD` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE_2` (`CODE`),
  KEY `CODE` (`CODE`),
  KEY `PAIS` (`PAIS`),
  CONSTRAINT `REL_UF_PAIS` FOREIGN KEY (`PAIS`) REFERENCES `GEO__PAIS` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COMMENT='LISTA DE TODOS OS ESTADOS';

CREATE TABLE IF NOT EXISTS `KITS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(300) DEFAULT NULL,
  `DESCRICAO` varchar(500) DEFAULT NULL,
  `DESCONTO_PCT` decimal(18,2) DEFAULT NULL,
  `VALOR_FECHADO` decimal(18,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MIDIA__BANNER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PLUGIN` int(11) DEFAULT NULL,
  `LINK` varchar(300) DEFAULT NULL,
  `TARGET` set('_Self','_Blank') DEFAULT '_Self',
  `ANALITYCS` tinyint(1) NOT NULL DEFAULT 0,
  `CLICKTAG` varchar(300) DEFAULT NULL,
  `TITULO` varchar(300) DEFAULT NULL,
  `DESCRICAO` varchar(700) DEFAULT NULL,
  `STATUS` int(11) DEFAULT 4,
  `INICIA` datetime DEFAULT NULL,
  `TERMINA` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `REL_BANNER_PLUGIN` (`ID_PLUGIN`),
  KEY `REL_BANNER_STATUS` (`STATUS`),
  CONSTRAINT `REL_MIDIA_BANNER__PLUGIN` FOREIGN KEY (`ID_PLUGIN`) REFERENCES `MIDIA__PLUGIN` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=85 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MIDIA__FILES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_BANNER` int(11) NOT NULL,
  `ID_PLUGIN` int(11) NOT NULL,
  `NOME_ORIGINAL` varchar(400) NOT NULL,
  `PATH` varchar(400) NOT NULL,
  `FILENAME` varchar(300) NOT NULL,
  `MEDIA_QUERY` int(5) NOT NULL,
  `SIZE` varchar(50) NOT NULL,
  `TYPE` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `REL_FILE_PLUGIN` (`ID_PLUGIN`),
  KEY `REL_FILE_BANNER` (`ID_BANNER`),
  CONSTRAINT `REL_FILES_UID_MIDIA_BANNER` FOREIGN KEY (`ID_BANNER`) REFERENCES `MIDIA__BANNER` (`ID`),
  CONSTRAINT `REL_FILES_UID_MIDIA_PLUGIN` FOREIGN KEY (`ID_PLUGIN`) REFERENCES `MIDIA__PLUGIN` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=311 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MIDIA__PLUGIN` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(200) NOT NULL,
  `DESCRICAO` varchar(300) NOT NULL,
  `SLUG` varchar(200) NOT NULL,
  `RESPONSIVO` tinyint(1) NOT NULL DEFAULT 1,
  `MULTIPLOS` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  KEY `SLUG` (`SLUG`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MIDIA__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `NEWSLETTER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(300) DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `NOTIFICACOES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) NOT NULL,
  `UID_EMPREENDIMENTO` bigint(25) NOT NULL,
  `REMETENTE` bigint(25) NOT NULL,
  `PARAMS` text DEFAULT NULL,
  `TEMPLATE` int(3) DEFAULT NULL,
  `TITULO` varchar(200) NOT NULL,
  `MENSAGEM` text NOT NULL,
  `VISUALIZADO` tinyint(1) NOT NULL DEFAULT 0,
  `CRIADO_EM` datetime NOT NULL DEFAULT current_timestamp(),
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `DESTINO` (`UID_USER`),
  KEY `REMETENTE` (`REMETENTE`),
  KEY `TEMPLATE` (`TEMPLATE`),
  CONSTRAINT `DESTINO` FOREIGN KEY (`UID_USER`) REFERENCES `USUARIOS` (`UID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `REMETENTE` FOREIGN KEY (`REMETENTE`) REFERENCES `USUARIOS` (`UID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `TEMPLATE` FOREIGN KEY (`TEMPLATE`) REFERENCES `NOTIFICACOES_TEMPLATES` (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `NOTIFICACOES__TEMPLATES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(400) NOT NULL,
  `CODE` int(3) NOT NULL,
  `TEMPLATE` text NOT NULL,
  `NOME_VAR` varchar(300) NOT NULL,
  `BALAO_TOPO` text NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PLANOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `PLANO` varchar(300) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PLANOS__GRADUACOES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `POSICAO` int(11) NOT NULL,
  `CODE` bigint(25) NOT NULL,
  `CODE_PLANO` bigint(25) NOT NULL,
  `GRADUACAO` varchar(200) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `REDE_TOTAL` int(11) NOT NULL,
  `REDE_DIRETA` int(11) NOT NULL,
  `MATRIZ_FECHADA` tinyint(1) NOT NULL DEFAULT 0,
  `MATRIZ_PERNA_MENOR` int(11) NOT NULL,
  `EXCLUIDO` float NOT NULL,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `VALOR` decimal(18,2) NOT NULL DEFAULT 129.90,
  `RENOVACAO` int(1) NOT NULL DEFAULT 0,
  `PACOTE_RENTAL_COIN` bigint(25) DEFAULT NULL,
  `GETWAY_BTC` tinyint(1) NOT NULL DEFAULT 1,
  `GETWAY_PIX` tinyint(1) NOT NULL DEFAULT 1,
  `GETWAY_MP` tinyint(1) NOT NULL DEFAULT 1,
  `GETWAY_SALDO` tinyint(1) NOT NULL DEFAULT 0,
  `GETWAY_BOLETO` tinyint(1) NOT NULL DEFAULT 0,
  `GETWAY_CARTAO` tinyint(1) NOT NULL DEFAULT 0,
  `GETWAY_PEC` tinyint(1) NOT NULL DEFAULT 0,
  `QUALI_PAI` tinyint(1) NOT NULL DEFAULT 0,
  `QUALI_AVO` tinyint(1) NOT NULL DEFAULT 0,
  `QUALI_ORIGEM` tinyint(1) NOT NULL DEFAULT 0,
  `QUALI_PAI_ORIGEM` tinyint(1) NOT NULL DEFAULT 0,
  `QUALI_UPLINE` tinyint(1) NOT NULL DEFAULT 0,
  `NIVEL_QUALI_UPLINE` int(11) NOT NULL DEFAULT 1,
  `LISTA_NO_CADASTRO` tinyint(1) NOT NULL DEFAULT 0,
  `QTDD_EXPIRE` int(11) NOT NULL DEFAULT 30 COMMENT 'QTDD EM NUMEROS QUE EXPIRA O PLANO',
  `EXPIRE_TYPE` varchar(100) NOT NULL DEFAULT 'DAYS' COMMENT 'SECONDS, MINUTES, HOUR, DAY, WEEK, MONTH, YEAR',
  `PARALELOS` int(11) NOT NULL DEFAULT 1 COMMENT 'MÁXIMO DE INSTANCIAS POR USUARIO EM PARALELO',
  `VALOR_MULTA` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT 'VALOR ( FLOAT ) MONETARIO OU PERCENTUAL DA MULTA',
  `TIPO_MULTA` int(11) NOT NULL DEFAULT 1 COMMENT '1=% | 2=Fixo  ',
  `PERIODO_MULTA` int(11) NOT NULL DEFAULT 3 COMMENT '1=DIA, 2=SEMANA, 3=MÊS, 4=ANO\r\n',
  `BLOCK_EXPIRE` int(1) NOT NULL DEFAULT 0 COMMENT 'BLOQUEIA ACESSO DO USUARIO QD EXPIRA',
  `PERM_RENOVA` int(1) NOT NULL DEFAULT 0 COMMENT 'PERMITE RENOVAÇÃO',
  `MULTA_ATRASO` int(1) NOT NULL DEFAULT 0 COMMENT 'PERMITE MULTA POR ATRASO DO PAGAMENTO',
  PRIMARY KEY (`ID`),
  KEY `REL_GRADUACOES_PLANO` (`CODE_PLANO`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PLANOS__PLANOS_REDE_QUALIFICADORES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PLANO` bigint(25) NOT NULL,
  `ID_GRADUACAO` bigint(25) DEFAULT NULL,
  `QUALIFICADOR_PLANO` bigint(25) DEFAULT NULL,
  `QUALIFICADOR_GRADUACAO` bigint(25) DEFAULT NULL,
  `QTDD_REDE` int(11) DEFAULT NULL,
  `NIVEL` int(11) DEFAULT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `ID_GRADUACAO` (`ID_GRADUACAO`),
  KEY `QUALIFICADOR_PLANO` (`QUALIFICADOR_PLANO`),
  KEY `QUALIFICADOR_GRADUACAO` (`QUALIFICADOR_GRADUACAO`),
  KEY `REL_QUALIFICA_NIVEL` (`NIVEL`),
  KEY `ID_PLANO` (`ID_PLANO`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PLANOS__PLANO_ATIVO_QUALIFICADOR` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PLANO` bigint(25) NOT NULL,
  `ID_GRADUACAO` bigint(25) DEFAULT NULL,
  `QUALIFICADOR_PLANO` bigint(25) DEFAULT NULL,
  `QUALIFICADOR_GRADUACAO` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_GRADUACAO` (`ID_GRADUACAO`),
  KEY `QUALIFICADOR_PLANO` (`QUALIFICADOR_PLANO`),
  KEY `QUALIFICADOR_GRADUACAO` (`QUALIFICADOR_GRADUACAO`),
  KEY `REL_PLANO_ATIVO_QUALIFICADOR_PLANO_CODE` (`ID_PLANO`),
  CONSTRAINT `REL_PLANO_ATIVO_PLANO_GRAD` FOREIGN KEY (`ID_GRADUACAO`) REFERENCES `PLANOS__GRADUACOES` (`CODE`),
  CONSTRAINT `REL_PLANO_ATIVO_QUALIFICADOR_ATUAL` FOREIGN KEY (`QUALIFICADOR_PLANO`) REFERENCES `PLANOS` (`CODE`),
  CONSTRAINT `REL_PLANO_ATIVO_QUALIFICADOR_PLANO_CODE` FOREIGN KEY (`ID_PLANO`) REFERENCES `PLANOS` (`CODE`),
  CONSTRAINT `REL_PLANO_ATIVO_QUALIFICADOR_PLANO_GRAD` FOREIGN KEY (`QUALIFICADOR_GRADUACAO`) REFERENCES `PLANOS__GRADUACOES` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=182 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PLANOS__RECOMPENSA_QUALIFICADORES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PLANO_CODE` bigint(25) NOT NULL,
  `GRADUACAO_CODE` bigint(25) NOT NULL,
  `RECOMPENSA_CODE` bigint(25) DEFAULT NULL,
  `RECOMPENSA_TIPO_CODE` bigint(25) DEFAULT NULL,
  `VALOR_MINIMO` double(18,2) DEFAULT NULL,
  `QTDD_REDE` int(11) NOT NULL,
  `DIAS` int(11) NOT NULL,
  `NIVEL` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PLANOS__RECOMPENSA_QUALIFICADOR_NIVEL` (`NIVEL`),
  KEY `REL_RECOMPENSA_QUALI_PLANO_CODE` (`PLANO_CODE`),
  KEY `REL_RECOMPENSA_QUALI_GRAD_CODE` (`GRADUACAO_CODE`),
  KEY `REL_RECOMPENSA_QUALI_RECOMPENSA_CODE` (`RECOMPENSA_CODE`),
  KEY `REL_RECOMPENSA_QUALI_RECOMPENSA_TIPO_CODE` (`RECOMPENSA_TIPO_CODE`),
  CONSTRAINT `REL_RECOMPENSA_QUALI_GRAD_CODE` FOREIGN KEY (`GRADUACAO_CODE`) REFERENCES `PLANOS__GRADUACOES` (`CODE`),
  CONSTRAINT `REL_RECOMPENSA_QUALI_PLANO_CODE` FOREIGN KEY (`PLANO_CODE`) REFERENCES `PLANOS` (`CODE`),
  CONSTRAINT `REL_RECOMPENSA_QUALI_RECOMPENSA_CODE` FOREIGN KEY (`RECOMPENSA_CODE`) REFERENCES `RECOMPENSAS` (`CODE`),
  CONSTRAINT `REL_RECOMPENSA_QUALI_RECOMPENSA_TIPO_CODE` FOREIGN KEY (`RECOMPENSA_TIPO_CODE`) REFERENCES `RECOMPENSAS__TIPO` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PLANOS__USUARIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `UID_USER` bigint(25) NOT NULL,
  `CODE_PLANO` bigint(25) DEFAULT NULL,
  `CODE_GRADUACAO` bigint(25) NOT NULL,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `PERIODO_VIGENTE` timestamp NOT NULL DEFAULT current_timestamp(),
  `VENCIMENTO` datetime DEFAULT NULL,
  `EXPIRA_EM` datetime DEFAULT NULL,
  `PAGO_EM` datetime DEFAULT NULL,
  `UID_FATURA` varchar(50) DEFAULT NULL COMMENT 'UID FATURA EM ABERTO. QUANDO PAGAR, FICA COMO NULL\r\n',
  `ATIVO` int(1) NOT NULL DEFAULT 1,
  `EXCLUIDO` tinyint(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `ID` (`ID`),
  KEY `REL_PLANOS__USUARIOS_PLANO` (`CODE_PLANO`),
  KEY `REL_PLANOS__USUARIOS` (`UID_USER`),
  KEY `REL_PLANOS__USUARIOS_GRADUACAO` (`CODE_GRADUACAO`),
  KEY `UID_FATURA` (`UID_FATURA`),
  CONSTRAINT `REL_PLANO_UIDGRAD` FOREIGN KEY (`CODE_GRADUACAO`) REFERENCES `PLANOS__GRADUACOES` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `REL_PLANO_UIDPLANO` FOREIGN KEY (`CODE_PLANO`) REFERENCES `PLANOS` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `REL_PLANO_UIDUSER` FOREIGN KEY (`UID_USER`) REFERENCES `USUARIOS` (`UID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=64 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PLANOS__VOLUME_MATRIZ` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VOLUME` decimal(18,2) DEFAULT NULL,
  `MATRIZ` int(11) DEFAULT NULL,
  `CODE_PLANO` bigint(25) DEFAULT NULL,
  `CODE_GRADUACAO` bigint(25) DEFAULT NULL,
  `DIAS` int(11) NOT NULL,
  `NIVEL` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `CODE` bigint(25) DEFAULT NULL,
  `NOME` varchar(200) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `OLD_VALOR` decimal(18,2) NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `STATUS` int(11) DEFAULT 1,
  `KEYWORDS` text DEFAULT '',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE_2` (`CODE`),
  KEY `REL_PROD_STATUS` (`STATUS`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__ADICIONAIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADICIONAL` varchar(300) NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `EXCLUIDO` int(1) DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__CARRINHO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO` int(11) DEFAULT 1,
  `UID_FRANQUIA` bigint(25) DEFAULT NULL,
  `UID_USER` bigint(25) DEFAULT NULL,
  `UID_PRODUTO` int(11) DEFAULT NULL,
  `ID_VARIACAO` int(11) DEFAULT NULL,
  `CODE_ASSINATURA` bigint(25) DEFAULT NULL,
  `CODE_PLANO` bigint(25) DEFAULT NULL,
  `CODE_GRADUACAO` bigint(25) DEFAULT NULL,
  `QTDD` int(11) NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `REGRA` int(11) NOT NULL,
  `ADICIONADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `ATIVACAO_RENOVACAO` int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `REL_PRODUTO__CARRINHO_TIPO` (`TIPO`),
  KEY `REL_PRODUTO__CARRINHO_CODE_PLANO` (`CODE_PLANO`),
  KEY `REL_PRODUTO__CARRINHO_CODE_GRADUACAO` (`CODE_GRADUACAO`),
  KEY `REL_PRODUTO__CARRINHO_USER` (`UID_USER`),
  CONSTRAINT `REL_PRODUTO__CARRINHO_CODE_GRADUACAO` FOREIGN KEY (`CODE_GRADUACAO`) REFERENCES `PLANOS__GRADUACOES` (`CODE`),
  CONSTRAINT `REL_PRODUTO__CARRINHO_CODE_PLANO` FOREIGN KEY (`CODE_PLANO`) REFERENCES `PLANOS` (`CODE`),
  CONSTRAINT `REL_PRODUTO__CARRINHO_TIPO` FOREIGN KEY (`TIPO`) REFERENCES `PRODUTO__TIPO` (`CODE`),
  CONSTRAINT `REL_PRODUTO__CARRINHO_USER` FOREIGN KEY (`UID_USER`) REFERENCES `USUARIOS` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=401 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__CARRINHO_ADICIONAIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_FRANQUIA` bigint(25) NOT NULL,
  `UID_USER` bigint(25) NOT NULL,
  `ID_ITEM_CARRINHO` int(11) NOT NULL,
  `ID_PRODUTO` int(11) NOT NULL,
  `ID_VARIACAO` int(11) NOT NULL,
  `ID_ADICIONAL` int(11) NOT NULL,
  `QTDD` int(11) NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `AVATAR` varchar(300) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=136 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__CATEGORIAS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_FRANQUIA` bigint(25) NOT NULL,
  `UID_CATPAI` int(11) DEFAULT 0,
  `CATEGORIA` varchar(500) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__ESTOQUE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO` bigint(25) DEFAULT NULL,
  `QUANTIDADE` int(11) DEFAULT NULL,
  `DATA_ESTOQUE` date DEFAULT current_timestamp(),
  `VALIDADE` date DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__IMAGENS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PROD` int(11) NOT NULL,
  `ID_VARIACAO` int(11) NOT NULL,
  `ID_ADICIONAL` int(11) NOT NULL,
  `PATH` varchar(500) NOT NULL,
  `HASH` varchar(40) NOT NULL,
  `FILE` varchar(400) NOT NULL,
  `ORIGINAL_NOME` varchar(500) NOT NULL,
  `SIZE` varchar(200) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__KITS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(300) DEFAULT NULL,
  `DESCRICAO` varchar(500) DEFAULT NULL,
  `DESCONTO_PCT` decimal(18,2) DEFAULT NULL,
  `VALOR_FECHADO` decimal(18,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__LINK_ADICIONAIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO` int(11) NOT NULL,
  `ID_ADICIONAL` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__LINK_CAT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_FRANQUIA` bigint(11) NOT NULL,
  `UID_PROD` bigint(25) NOT NULL,
  `UID_CAT` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__LINK_PLANOS_GRADUACOES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PROD` int(11) NOT NULL,
  `ID_GRAD` bigint(25) NOT NULL,
  `MOSTRAR` int(1) NOT NULL DEFAULT 0,
  `ESCONDER` int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `REL_PLANOS_GRADUACOES_IDPROD` (`ID_PROD`),
  KEY `REL_PLANOS_GRADUACOES_IDGRAD` (`ID_GRAD`),
  CONSTRAINT `REL_PLANOS_GRADUACOES_IDGRAD` FOREIGN KEY (`ID_GRAD`) REFERENCES `PLANOS__GRADUACOES` (`CODE`),
  CONSTRAINT `REL_PLANOS_GRADUACOES_IDPROD` FOREIGN KEY (`ID_PROD`) REFERENCES `PRODUTO` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__LINK_RECOMPENSA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO` int(11) NOT NULL,
  `ID_TIPO_RECOMPENSA` bigint(25) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `REL_PROD_REC_PROD` (`ID_PRODUTO`),
  KEY `REL_PROD_REC_REC` (`ID_TIPO_RECOMPENSA`),
  CONSTRAINT `REL_PROD_REC_PROD` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID`),
  CONSTRAINT `REL_PROD_REC_REC` FOREIGN KEY (`ID_TIPO_RECOMPENSA`) REFERENCES `RECOMPENSAS__TIPO` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `STATUS` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(300) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__VARIACOES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_PRODUTO` int(11) NOT NULL,
  `COR` varchar(10) NOT NULL DEFAULT '#FFFFFF',
  `VARIACAO` varchar(250) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `STATUS` int(11) DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__VINCULO_KITS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_KIT` int(11) DEFAULT NULL,
  `ID_PRODUTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `UID_KIT` (`UID_KIT`),
  KEY `REL_KIT_PRODUTO` (`ID_PRODUTO`),
  CONSTRAINT `REL_KIT_PRODUTO` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID`),
  CONSTRAINT `REL_PRODUTO_KIT` FOREIGN KEY (`UID_KIT`) REFERENCES `KITS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUTO__VINCULO_PRODUTOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_PROD_A` bigint(25) DEFAULT NULL,
  `CODE_PROD_B` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `VINC_PROD_A` (`CODE_PROD_A`),
  KEY `VINC_PROD_B` (`CODE_PROD_B`),
  CONSTRAINT `VINC_PROD_A` FOREIGN KEY (`CODE_PROD_A`) REFERENCES `PRODUTO` (`CODE`),
  CONSTRAINT `VINC_PROD_B` FOREIGN KEY (`CODE_PROD_B`) REFERENCES `PRODUTO` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `QUEMSOMOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SESSAO` varchar(255) NOT NULL,
  `TITULO` varchar(255) NOT NULL,
  `TEXTO` text NOT NULL,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `QUEMSOMOS__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `SESSAO` varchar(255) NOT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `TEXTO` text DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `RECOMPENSA` varchar(200) NOT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__DISTRIBUICAO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `NOME` varchar(250) NOT NULL,
  `ATIVO` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__NIVEIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RECOMPENSA_CODE` bigint(25) NOT NULL,
  `RECONPENSA_TIPO_CODE` bigint(25) NOT NULL,
  `VALOR` decimal(18,2) NOT NULL,
  `NIVEL` int(11) NOT NULL,
  `CALCULO` int(11) DEFAULT NULL,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  `CRIADO_DATA` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `REL_NIVEIS_RECONPENSA_CODE` (`RECOMPENSA_CODE`),
  KEY `REL_NIVEIS_CALCULO_CODE` (`CALCULO`),
  KEY `NIVEL` (`NIVEL`),
  KEY `REL_NIVEIS_RECONPENSA_TIPO_CODE` (`RECONPENSA_TIPO_CODE`),
  CONSTRAINT `REL_NIVEIS_CALCULO_CODE` FOREIGN KEY (`CALCULO`) REFERENCES `RECOMPENSAS__UNIDADE_CALCULO` (`CODE`),
  CONSTRAINT `REL_NIVEIS_RECONPENSA_CODE` FOREIGN KEY (`RECOMPENSA_CODE`) REFERENCES `RECOMPENSAS` (`CODE`),
  CONSTRAINT `REL_NIVEIS_RECONPENSA_TIPO_CODE` FOREIGN KEY (`RECONPENSA_TIPO_CODE`) REFERENCES `RECOMPENSAS__TIPO` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__ORIGEM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL DEFAULT 0,
  `ORIGEM` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__POR_GRADUACAO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_GRAD` bigint(26) NOT NULL,
  `CODE_TIPO` bigint(26) NOT NULL,
  `ACTION` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `REL_RECOMPENSA_TO_CODE_GRADUACAO` (`CODE_GRAD`),
  KEY `REL_RECOMPENSA_TO_TIPO_RECOMPENSAS` (`CODE_TIPO`),
  CONSTRAINT `REL_RECOMPENSA_TO_CODE_GRADUACAO` FOREIGN KEY (`CODE_GRAD`) REFERENCES `PLANOS__GRADUACOES` (`CODE`),
  CONSTRAINT `REL_RECOMPENSA_TO_TIPO_RECOMPENSAS` FOREIGN KEY (`CODE_TIPO`) REFERENCES `RECOMPENSAS__TIPO` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=504 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__REGISTRO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER_ORIGEM` bigint(25) DEFAULT NULL COMMENT 'USUARIO QUE DISPAROU A RECOMPENSA',
  `UID_USER` bigint(25) DEFAULT NULL,
  `RECOMPENSA_CODE` bigint(25) DEFAULT NULL,
  `RECONPENSA_TIPO_CODE` bigint(25) DEFAULT NULL,
  `NIVEL` int(11) DEFAULT NULL,
  `TOTAL` double(18,2) NOT NULL,
  `DATA_HORA` timestamp NOT NULL DEFAULT current_timestamp(),
  `OBSERVACAO` varchar(500) NOT NULL COMMENT 'CASO SEJA INSERIDO MANUALMENTE\r\n',
  `RESPONSAVEL` bigint(25) DEFAULT NULL COMMENT 'RESPONSÁVEL PELA INSERÇÃO MANUAL',
  `PENDENTE` tinyint(1) DEFAULT 1,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `REL_REGISTRO_RECONPENSA_CODE` (`RECOMPENSA_CODE`),
  KEY `REL_REGISTRO_USER` (`UID_USER`),
  KEY `REL_REGISTRO_RESPONSAVEL` (`RESPONSAVEL`),
  KEY `REL_REGISTRO_RECONPENSA_TIPO_CODE` (`RECONPENSA_TIPO_CODE`),
  KEY `REL_REGISTRO_RECONPENSA_NIVEL` (`NIVEL`),
  KEY `REL_REGISTRO_USER_ORIGEM` (`UID_USER_ORIGEM`),
  CONSTRAINT `REL_REGISTRO_RECONPENSA_CODE` FOREIGN KEY (`RECOMPENSA_CODE`) REFERENCES `RECOMPENSAS` (`CODE`),
  CONSTRAINT `REL_REGISTRO_RECONPENSA_TIPO_CODE` FOREIGN KEY (`RECONPENSA_TIPO_CODE`) REFERENCES `RECOMPENSAS__TIPO` (`CODE`),
  CONSTRAINT `REL_REGISTRO_RESPONSAVEL` FOREIGN KEY (`RESPONSAVEL`) REFERENCES `USUARIOS` (`UID`),
  CONSTRAINT `REL_REGISTRO_USER` FOREIGN KEY (`UID_USER`) REFERENCES `USUARIOS` (`UID`),
  CONSTRAINT `REL_REGISTRO_USER_ORIGEM` FOREIGN KEY (`UID_USER_ORIGEM`) REFERENCES `USUARIOS` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` bigint(25) DEFAULT NULL,
  `ORIGEM` int(11) NOT NULL DEFAULT 0,
  `RECOMPENSA_CODE` bigint(25) DEFAULT NULL,
  `TIPO` varchar(300) NOT NULL,
  `TIPO_DISTRIBUICAO` int(11) DEFAULT 1,
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  `BINARIO` tinyint(1) NOT NULL DEFAULT 0,
  `COMPRA_LOJA` tinyint(1) NOT NULL DEFAULT 0,
  `CADASTRO` tinyint(1) NOT NULL DEFAULT 0,
  `FINANCEIRO` tinyint(1) NOT NULL DEFAULT 0,
  `ATIVACAO` tinyint(1) NOT NULL DEFAULT 0,
  `RENOVACAO` tinyint(1) NOT NULL DEFAULT 0,
  `PENDENTE` tinyint(1) NOT NULL DEFAULT 1,
  `RECEBE_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `RECEBE_NAO_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `PAGA_NAO_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `PAGA_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `PAI_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `PAI_NAO_QUALIFICADO` tinyint(1) NOT NULL DEFAULT 0,
  `VALOR` decimal(18,2) DEFAULT NULL,
  `TIPO_CALCULO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE_2` (`CODE`),
  KEY `CODE` (`CODE`),
  KEY `REL_TIPO_RECONPENSA_CODE` (`RECOMPENSA_CODE`),
  KEY `REL_TIPO__RECONPENSA_DISTRIBUICAO` (`TIPO_DISTRIBUICAO`),
  KEY `REL_TIPO__RECONPENSA_CALCULO` (`TIPO_CALCULO`),
  CONSTRAINT `REL_TIPO_RECONPENSA_CODE` FOREIGN KEY (`RECOMPENSA_CODE`) REFERENCES `RECOMPENSAS` (`CODE`),
  CONSTRAINT `REL_TIPO__RECONPENSA_CALCULO` FOREIGN KEY (`TIPO_CALCULO`) REFERENCES `RECOMPENSAS__UNIDADE_CALCULO` (`CODE`),
  CONSTRAINT `REL_TIPO__RECONPENSA_DISTRIBUICAO` FOREIGN KEY (`TIPO_DISTRIBUICAO`) REFERENCES `RECOMPENSAS__DISTRIBUICAO` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECOMPENSAS__UNIDADE_CALCULO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `NOME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SIGNALS__APIKEYS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) NOT NULL,
  `API_KEY` varchar(280) NOT NULL,
  `ID_ACCOUNT` bigint(25) NOT NULL,
  `COMPANY` varchar(255) NOT NULL,
  `ASSINOU _EM` datetime NOT NULL DEFAULT current_timestamp(),
  `RENOVADA_EM` datetime NOT NULL DEFAULT current_timestamp(),
  `EXPIRA_EM` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SIGNALS__CANAL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(100) NOT NULL,
  `CHANNEL_ID` varchar(200) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `REGEX` varchar(255) DEFAULT NULL,
  `PERFIL` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE` (`CODE`),
  KEY `CODE_2` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SIGNALS__COPYTRADER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `UID_USER` varchar(25) NOT NULL,
  `MAGIC_NUMBER` bigint(25) DEFAULT NULL,
  `TIPO_OP` int(1) NOT NULL DEFAULT 1 COMMENT '1:COMPRA,0:VENDE',
  `ATIVO` varchar(50) NOT NULL COMMENT 'SIGLA DO ATIVO',
  `ENTRADA` varchar(150) NOT NULL COMMENT 'VALOR DA ENTRADA',
  `SL` varchar(150) NOT NULL COMMENT 'STOP LOSS',
  `TP` varchar(250) NOT NULL COMMENT 'TAKE PROFIT',
  `EXECUTADO` int(1) NOT NULL DEFAULT 0 COMMENT '0:PENDENTE, 1:ABERTO, 2 FINALIZADO, 3 CANCELADO',
  `STEPS` int(2) NOT NULL DEFAULT 1 COMMENT 'TAMANHO DO GRID',
  `STATUS` int(1) NOT NULL DEFAULT 1,
  `DATA_LIMITE` datetime NOT NULL DEFAULT current_timestamp(),
  `TRAILING_STOP` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `UID` (`UID`),
  KEY `UID_USER` (`UID_USER`),
  KEY `MAGIC_NUMBER` (`MAGIC_NUMBER`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SIGNALS__COPYTRADER_ASSINATURA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) NOT NULL,
  `UID_TRADER` bigint(25) NOT NULL,
  `ACTIVE` int(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SIGNALS__COPYTRADER_GRID` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_SIGNAL` bigint(25) NOT NULL,
  `MAGIC_NUMBER` bigint(25) NOT NULL,
  `ENTRY` int(11) NOT NULL,
  `LOSS` int(11) NOT NULL,
  `PROFIT` varchar(100) DEFAULT NULL,
  `SL` varchar(100) DEFAULT NULL,
  `SYMBOL` varchar(100) DEFAULT NULL,
  `TP` varchar(100) DEFAULT NULL,
  `TS` varchar(100) DEFAULT NULL,
  `TYPE` varchar(100) DEFAULT NULL,
  `STATUS` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE_SIGNAL` (`CODE_SIGNAL`),
  KEY `MAGIC_NUMBER` (`MAGIC_NUMBER`)
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SIGNALS__LINK_USER_ACCOUNT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) NOT NULL,
  `ACCOUNT_NUMBER` bigint(25) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SIGNALS__TELEGRAM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CANAL` varchar(255) DEFAULT NULL,
  `ID_SINAL` varchar(255) NOT NULL,
  `MAGIC` bigint(25) NOT NULL,
  `CRIACAO` datetime NOT NULL,
  `MOEDA` varchar(255) NOT NULL,
  `TIPO` varchar(255) NOT NULL,
  `ENTRY` varchar(255) NOT NULL,
  `SL` varchar(30) NOT NULL,
  `TP` varchar(30) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_SINAL_2` (`ID_SINAL`),
  KEY `ID_SINAL` (`ID_SINAL`),
  KEY `ID_CANAL` (`ID_CANAL`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COMMENT='SINAIS DE CANAIS NO TELEGRAM';

CREATE TABLE IF NOT EXISTS `SIGNALS__TELEGRAM_SIGNATURE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) DEFAULT NULL,
  `CODE_CHANNEL` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SIGNALS__USER_TELEGRAM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CHAT` bigint(25) DEFAULT NULL,
  `ID_USER` bigint(25) DEFAULT NULL,
  `FIRST_NAME` varchar(255) DEFAULT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `USERNAME` varchar(255) DEFAULT NULL,
  `CELULAR` varchar(25) DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SUPORTE__ATENDIMENTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORIGEM` tinyint(1) DEFAULT 0,
  `UID_CHAMADO` bigint(25) DEFAULT NULL,
  `INDEX_EMAIL` int(11) DEFAULT NULL,
  `UID_RESPONSAVEL` bigint(25) DEFAULT NULL,
  `CODE_SETOR` int(11) DEFAULT NULL,
  `ASSUNTO` varchar(255) DEFAULT NULL,
  `TEXTO` text DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SUPORTE__CHAMADOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `STATUS` int(11) NOT NULL,
  `UID_SOLICITANTE` bigint(25) DEFAULT NULL,
  `CODE_SETOR` int(11) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` int(11) DEFAULT NULL,
  `OBS` text DEFAULT NULL,
  `DATA_CREATE` timestamp NOT NULL DEFAULT current_timestamp(),
  `DATA_UPDATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=191 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SUPORTE__CHAMADOS__ANEXOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FILENAME` varchar(255) DEFAULT NULL,
  `INDEX_EMAIL` bigint(25) DEFAULT NULL,
  `UID_CHAMADO` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SUPORTE__RESPONSAVEIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_RESPONSAVEL` bigint(25) DEFAULT NULL,
  `CODE_SETOR` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SUPORTE__SETORES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `SETOR` varchar(255) NOT NULL,
  `ATIVO` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SUPORTE__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `ATIVO` tinyint(1) NOT NULL DEFAULT 1,
  `ORDEM` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__LGPD` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTEUDO` text NOT NULL,
  `ACTIVE` int(11) DEFAULT 1,
  `CREATED` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__LIMIT_ACCESS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ASSINATURA` varchar(100) NOT NULL,
  `DATA_HORA` timestamp NOT NULL DEFAULT current_timestamp(),
  `CONGELA_ATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=121 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__REGRAS_DE_TAXAS_E_BONUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VIGENTE` tinyint(1) NOT NULL,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `TICKS_CLUB` float NOT NULL,
  `MEMBROS` float NOT NULL,
  `PRODUTOR` float NOT NULL,
  `REDE` float NOT NULL,
  `VIP` float NOT NULL,
  `MERECIMENTO` float NOT NULL,
  `APOS_META` float NOT NULL,
  `ALCANCE` float NOT NULL,
  `ALCANCE_1` float NOT NULL,
  `ALCANCE_2` float NOT NULL,
  `ALCANCE_3` float NOT NULL,
  `1_NIVEL` float NOT NULL,
  `2_NIVEL` float NOT NULL,
  `3_NIVEL` float NOT NULL,
  `4_NIVEL` float NOT NULL,
  `5_NIVEL` float NOT NULL,
  `6_NIVEL` float NOT NULL,
  `7_NIVEL` float NOT NULL,
  `8_NIVEL` float NOT NULL,
  `TAXA_SAQUE` float NOT NULL,
  `TAXA_RECARGA` float NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID` (`ID`),
  KEY `CRIADO_EM` (`CRIADO_EM`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__REGRAS_PCT_COMISSAO_REVENDA` (
  `UID` int(11) NOT NULL AUTO_INCREMENT,
  `NIVEL` int(11) NOT NULL,
  `PCT` int(11) NOT NULL,
  PRIMARY KEY (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__SMS_TOKEN` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TOKEN` int(11) NOT NULL,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `EXPIREDATA` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__TOKEN_ACCESS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HASH` varchar(280) DEFAULT NULL,
  `JSON` text DEFAULT NULL,
  `TIPO` int(11) NOT NULL,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `EXPIRE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `HASH` (`HASH`),
  KEY `REL_TOKEN_ACCESS_TYPE` (`TIPO`)
) ENGINE=InnoDB AUTO_INCREMENT=315 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__TYPE_TOKEN_ACCESS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `TIPO` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SYSTEM__VERSION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VERSION` float NOT NULL,
  `LABEL` varchar(500) NOT NULL,
  `RESET` tinyint(1) NOT NULL DEFAULT 1,
  `CHALLENGE` varchar(255) NOT NULL COMMENT 'UUID USADO NA BIOMETRIA',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=76 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IDIOMA` enum('pt','en','es') DEFAULT 'pt',
  `FOOTER` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `HEADER` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `TIPO_ATUACAO` int(1) DEFAULT NULL,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FW_UID_LANG` (`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO_CONSULTORIA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FW_UID_LANG` (`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_FW_LANG` (`FW_LANG`,`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO_PRODUTOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FW_UID_LANG` (`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_FW_LANG` (`FW_LANG`,`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__AREAS_ATUACAO__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `TIPO_ATUACAO` int(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_FW_LANG` (`FW_LANG`,`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__CONTATO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TOP_TITLE` varchar(244) DEFAULT NULL,
  `TITULO_FORM` varchar(255) DEFAULT NULL,
  `ADRESS_TITLE` varchar(255) DEFAULT NULL,
  `ADRESS_TEXT` varchar(255) DEFAULT NULL,
  `HORARIOS_TITLE` varchar(255) DEFAULT NULL,
  `HORARIOS_TEXT` varchar(255) DEFAULT NULL,
  `EMAILS_TITLE` varchar(255) DEFAULT NULL,
  `EMAILS_TEXT` varchar(255) DEFAULT NULL,
  `TEXTO_BOTAO` varchar(244) DEFAULT NULL,
  `PLACEHOLDER_NOME` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_EMAIL` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_TELEFONE` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_ASSUNTO` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_TEXTO` varchar(255) DEFAULT NULL,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FW_UID_LANG` (`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__CONTATO__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  `TOP_TITLE` varchar(244) DEFAULT NULL,
  `TITULO_FORM` varchar(255) DEFAULT NULL,
  `ADRESS_TITLE` varchar(255) DEFAULT NULL,
  `ADRESS_TEXT` varchar(255) DEFAULT NULL,
  `HORARIOS_TITLE` varchar(255) DEFAULT NULL,
  `HORARIOS_TEXT` varchar(255) DEFAULT NULL,
  `EMAILS_TITLE` varchar(255) DEFAULT NULL,
  `EMAILS_TEXT` varchar(255) DEFAULT NULL,
  `TEXTO_BOTAO` varchar(244) DEFAULT NULL,
  `PLACEHOLDER_NOME` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_EMAIL` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_TELEFONE` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_ASSUNTO` varchar(255) DEFAULT NULL,
  `PLACEHOLDER_TEXTO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_FW_LANG` (`FW_LANG`,`FW_UID_LANG`),
  KEY `FW_UID_LANG` (`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__HOME` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `OUTRAS_SOLUCOES` varchar(256) DEFAULT NULL,
  `OUTRAS_SOLUCOES_TXT` text DEFAULT NULL,
  `ANOS_EXP_NUM` int(11) DEFAULT 0,
  `ANOS_EXP_TXT` varchar(256) DEFAULT NULL,
  `ANOS_EXP_DESC` text DEFAULT NULL,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FW_UID_LANG` (`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__HOME__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  `OUTRAS_SOLUCOES` varchar(256) DEFAULT NULL,
  `OUTRAS_SOLUCOES_TXT` text DEFAULT NULL,
  `ANOS_EXP_NUM` int(11) DEFAULT NULL,
  `ANOS_EXP_TXT` varchar(256) DEFAULT NULL,
  `ANOS_EXP_DESC` text DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_FW_LANG` (`FW_LANG`,`FW_UID_LANG`),
  KEY `FW_UID_LANG` (`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__SOBRE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SESSAO` varchar(255) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `CONTEUDO` text DEFAULT NULL,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__SOBRE__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` varchar(5) DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `SESSAO` varchar(255) DEFAULT NULL,
  `TITULO` varchar(255) DEFAULT NULL,
  `CONTEUDO` text DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__STATIC` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MENU_LABEL_HOME` varchar(100) DEFAULT NULL,
  `MENU_LABEL_EMPRESA` varchar(100) DEFAULT NULL,
  `MENU_LABEL_ATUACAO` varchar(100) DEFAULT NULL,
  `MENU_LABEL_DOC` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CLIENTES` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CASES` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CONTATO` varchar(100) DEFAULT NULL,
  `MENU_LINK_HOME` varchar(250) DEFAULT NULL,
  `MENU_LINK_EMPRESA` varchar(250) DEFAULT NULL,
  `MENU_LINK_ATUACAO` varchar(250) DEFAULT NULL,
  `MENU_LINK_DOC` varchar(250) DEFAULT NULL,
  `MENU_LINK_CLIENTES` varchar(250) DEFAULT NULL,
  `MENU_LINK_CASES` varchar(250) DEFAULT NULL,
  `MENU_LINK_CONTATO` varchar(250) DEFAULT NULL,
  `MENU_LABEL_ATUACAO_DOC` varchar(255) DEFAULT NULL,
  `MENU_LINK_ATUACAO_DOC` varchar(255) DEFAULT NULL,
  `MENU_LABEL_ATUACAO_PROD` varchar(255) DEFAULT NULL,
  `MENU_LINK_ATUACAO_PROD` varchar(255) DEFAULT NULL,
  `MENU_LABEL_ATUACAO_CONS` varchar(255) DEFAULT NULL,
  `MENU_LINK_ATUACAO_CONS` varchar(255) DEFAULT NULL,
  `HEADER_NEWSLETTER_TITULO` varchar(250) DEFAULT NULL,
  `HEADER_NEWSLETTER_DESC` varchar(250) DEFAULT NULL,
  `HEADER_PLACEHOLDER` varchar(250) DEFAULT NULL,
  `HEADER_ABOUT_TITULO` varchar(250) DEFAULT NULL,
  `HEADER_ABOUT_DESC` varchar(250) DEFAULT NULL,
  `HEADER_TELEFONE` varchar(250) DEFAULT NULL,
  `HEADER_ENDERECO` varchar(250) DEFAULT NULL,
  `HEADER_NEWSLETTER_BUTTON` varchar(250) DEFAULT NULL,
  `HEADER_COPYRIGHT` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_TITULO` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_DESC` varchar(250) DEFAULT NULL,
  `FOOTER_PLACEHOLDER` varchar(250) DEFAULT NULL,
  `FOOTER_ABOUT_TITULO` varchar(250) DEFAULT NULL,
  `FOOTER_ABOUT_DESC` varchar(250) DEFAULT NULL,
  `FOOTER_TELEFONE` varchar(250) DEFAULT NULL,
  `FOOTER_ENDERECO` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_BUTTON` varchar(250) DEFAULT NULL,
  `FOOTER_COPYRIGHT` varchar(250) DEFAULT NULL,
  `FOOTER_LINK_COPYRIGHT` varchar(250) DEFAULT NULL,
  `TITULO_AREAS` varchar(255) DEFAULT NULL,
  `TITULO_CLIENTES` varchar(255) DEFAULT NULL,
  `TITULO_ATUACAO_CONSULT` varchar(255) DEFAULT NULL,
  `TITULO_ATUACAO_DOC` varchar(255) DEFAULT NULL,
  `TITULO_ATUACAO_PROD` varchar(255) DEFAULT NULL,
  `TITULO_SOBRE_NOS` varchar(255) DEFAULT NULL,
  `TITULO_CONTATOS` varchar(255) DEFAULT NULL,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FW_UID_LANG` (`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TEMPLATE__STATIC__TRANSLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_LANG` enum('pt','en','es') DEFAULT 'pt',
  `ID_FW_PAI` int(11) DEFAULT NULL,
  `FW_UID_LANG` bigint(25) DEFAULT NULL,
  `MENU_LABEL_HOME` varchar(100) DEFAULT NULL,
  `MENU_LABEL_EMPRESA` varchar(100) DEFAULT NULL,
  `MENU_LABEL_ATUACAO` varchar(100) DEFAULT NULL,
  `MENU_LABEL_DOC` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CLIENTES` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CASES` varchar(100) DEFAULT NULL,
  `MENU_LABEL_CONTATO` varchar(100) DEFAULT NULL,
  `MENU_LINK_HOME` varchar(250) DEFAULT NULL,
  `MENU_LINK_EMPRESA` varchar(250) DEFAULT NULL,
  `MENU_LINK_ATUACAO` varchar(250) DEFAULT NULL,
  `MENU_LINK_DOC` varchar(250) DEFAULT NULL,
  `MENU_LINK_CLIENTES` varchar(250) DEFAULT NULL,
  `MENU_LINK_CASES` varchar(250) DEFAULT NULL,
  `MENU_LINK_CONTATO` varchar(250) DEFAULT NULL,
  `MENU_LABEL_ATUACAO_DOC` varchar(255) DEFAULT NULL,
  `MENU_LINK_ATUACAO_DOC` varchar(255) DEFAULT NULL,
  `MENU_LABEL_ATUACAO_PROD` varchar(255) DEFAULT NULL,
  `MENU_LINK_ATUACAO_PROD` varchar(255) DEFAULT NULL,
  `MENU_LABEL_ATUACAO_CONS` varchar(255) DEFAULT NULL,
  `MENU_LINK_ATUACAO_CONS` varchar(255) DEFAULT NULL,
  `HEADER_NEWSLETTER_TITULO` varchar(250) DEFAULT NULL,
  `HEADER_NEWSLETTER_DESC` varchar(250) DEFAULT NULL,
  `HEADER_PLACEHOLDER` varchar(250) DEFAULT NULL,
  `HEADER_ABOUT_TITULO` varchar(250) DEFAULT NULL,
  `HEADER_ABOUT_DESC` varchar(250) DEFAULT NULL,
  `HEADER_TELEFONE` varchar(250) DEFAULT NULL,
  `HEADER_ENDERECO` varchar(250) DEFAULT NULL,
  `HEADER_NEWSLETTER_BUTTON` varchar(250) DEFAULT NULL,
  `HEADER_COPYRIGHT` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_TITULO` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_DESC` varchar(250) DEFAULT NULL,
  `FOOTER_PLACEHOLDER` varchar(250) DEFAULT NULL,
  `FOOTER_ABOUT_TITULO` varchar(250) DEFAULT NULL,
  `FOOTER_ABOUT_DESC` varchar(250) DEFAULT NULL,
  `FOOTER_TELEFONE` varchar(250) DEFAULT NULL,
  `FOOTER_ENDERECO` varchar(250) DEFAULT NULL,
  `FOOTER_NEWSLETTER_BUTTON` varchar(250) DEFAULT NULL,
  `FOOTER_COPYRIGHT` varchar(250) DEFAULT NULL,
  `FOOTER_LINK_COPYRIGHT` varchar(250) DEFAULT NULL,
  `TITULO_AREAS` varchar(255) DEFAULT NULL,
  `TITULO_CLIENTES` varchar(255) DEFAULT NULL,
  `TITULO_ATUACAO_CONSULT` varchar(255) DEFAULT NULL,
  `TITULO_ATUACAO_DOC` varchar(255) DEFAULT NULL,
  `TITULO_ATUACAO_PROD` varchar(255) DEFAULT NULL,
  `TITULO_SOBRE_NOS` varchar(255) DEFAULT NULL,
  `TITULO_CONTATOS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_FW_LANG` (`FW_LANG`,`FW_UID_LANG`),
  KEY `FW_UID_LANG` (`FW_UID_LANG`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID` bigint(25) DEFAULT NULL,
  `TIPO_PROFILE` int(11) DEFAULT 0,
  `LEVEL_PERMISSION` int(11) DEFAULT NULL,
  `FIRSTACCESS` tinyint(1) NOT NULL DEFAULT 1,
  `UID_EMPRESA` int(11) DEFAULT NULL,
  `STATUS` int(10) DEFAULT 0,
  `BLACKLIST` tinyint(1) NOT NULL DEFAULT 0,
  `NOME` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `LOGIN` varchar(50) DEFAULT NULL,
  `SENHA` varchar(256) DEFAULT NULL,
  `SALT` varchar(100) NOT NULL,
  `NOVA_SENHA` varchar(300) DEFAULT NULL,
  `PIN` varchar(255) DEFAULT '',
  `TIPO_DOCUMENTO` int(11) DEFAULT NULL,
  `TIPO_PESSOA` int(11) DEFAULT NULL,
  `2FA` varchar(256) DEFAULT NULL,
  `2FA_ACTIVE` tinyint(1) NOT NULL DEFAULT 0,
  `EMAIL_VALIDADO` tinyint(1) NOT NULL DEFAULT 0,
  `CRIADO_EM` timestamp NOT NULL DEFAULT current_timestamp(),
  `EXCLUIDO` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `UID` (`UID`),
  KEY `REL_TIPO_PESSOA` (`TIPO_PESSOA`),
  KEY `REL_TIPO_DOC` (`TIPO_DOCUMENTO`),
  KEY `REL_USER_STATUS` (`STATUS`),
  KEY `REL_USER_TIPO_PROFILE` (`TIPO_PROFILE`),
  CONSTRAINT `REL_TIPO_DOC` FOREIGN KEY (`TIPO_DOCUMENTO`) REFERENCES `USUARIOS__TIPO_DOCUMENTO` (`CODE`),
  CONSTRAINT `REL_TIPO_PESSOA` FOREIGN KEY (`TIPO_PESSOA`) REFERENCES `USUARIOS__TIPO_PESSOA` (`CODE`),
  CONSTRAINT `REL_USER_STATUS` FOREIGN KEY (`STATUS`) REFERENCES `USUARIOS__STATUS` (`CODE`),
  CONSTRAINT `REL_USER_TIPO_PROFILE` FOREIGN KEY (`TIPO_PROFILE`) REFERENCES `USUARIOS__TIPO_PROFILE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=248 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__DADOS_PROJETO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) DEFAULT NULL,
  `CPF` varchar(50) DEFAULT NULL,
  `RG` varchar(50) DEFAULT NULL,
  `LISTA_UPLOAD` text DEFAULT NULL,
  `DESCRICAO` varchar(300) DEFAULT NULL,
  `ATENDIDO_IMOBILIARIA` varchar(300) DEFAULT NULL,
  `CORRETOR_NOME` varchar(300) DEFAULT NULL,
  `INSTAGRAM` varchar(300) DEFAULT NULL,
  `NACIONALIDADE` varchar(50) DEFAULT NULL,
  `PERFIL_INVESTIDOR` varchar(50) DEFAULT NULL,
  `PROFISSAO` varchar(100) DEFAULT NULL,
  `REGIME_BENS` varchar(50) DEFAULT NULL,
  `RENDA_ATE` varchar(50) DEFAULT NULL,
  `RENDA_DE` varchar(50) DEFAULT NULL,
  `TIPO_CONTA_TRADICIONAL` int(1) DEFAULT 0,
  `TIPO_CONTA_DIGITAL` int(1) DEFAULT 0,
  `TIPO_CONTA_EXCHANGE` int(1) DEFAULT 0,
  `UNIDADE` varchar(200) DEFAULT NULL,
  `VEICULO_REPASSE` varchar(5) DEFAULT NULL,
  `TELEFONE` varchar(50) DEFAULT NULL,
  `WHATSAPP` varchar(50) DEFAULT NULL,
  `DATA_INSERT` timestamp NOT NULL DEFAULT current_timestamp(),
  `OBS` text DEFAULT NULL,
  `LOGRADOURO` varchar(300) DEFAULT NULL,
  `CIDADE` varchar(100) DEFAULT NULL,
  `ESTADO` varchar(50) DEFAULT NULL,
  `CEP` varchar(50) DEFAULT NULL,
  `NUMERO` varchar(50) DEFAULT NULL,
  `COMPLEMENTO` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `REL_UUSER_DATA_ID_USER` (`UID_USER`),
  CONSTRAINT `REL_UUSER_DATA_ID_USER` FOREIGN KEY (`UID_USER`) REFERENCES `USUARIOS` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=702 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__DISPOSITIVOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UID_USER` bigint(25) NOT NULL,
  `NAME` varchar(250) NOT NULL,
  `AUTHN` varchar(256) DEFAULT NULL,
  `ASSINATURA` varchar(300) DEFAULT NULL,
  `JSON_RESPONSE` text DEFAULT NULL,
  `AUTORIZADO` int(1) NOT NULL DEFAULT 0,
  `CONGELA_ATE` datetime DEFAULT NULL,
  `MODO_SEGURO` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=174 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(10) NOT NULL,
  `TITULO` varchar(100) NOT NULL,
  `DESCRICAO` varchar(300) NOT NULL,
  `COR` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__TIPO_DOCUMENTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__TIPO_PESSOA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__TIPO_PROFILE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) DEFAULT NULL,
  `NOME` varchar(300) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__VINCULO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USUARIO_A` bigint(25) DEFAULT NULL COMMENT 'segue | de quem | paga | pai',
  `USUARIO_B` bigint(25) DEFAULT NULL COMMENT 'seguido | pra quem | recebe | filho',
  `REFERENCIA` varchar(100) DEFAULT NULL,
  `TIPO` int(11) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `INDICE_REFERENCIA` (`REFERENCIA`),
  KEY `USUARIO_A` (`USUARIO_A`),
  KEY `USUARIO_B` (`USUARIO_B`),
  KEY `REL-USER-VINCULO__TIPO` (`TIPO`),
  CONSTRAINT `REL-USER-VINCULO__TIPO` FOREIGN KEY (`TIPO`) REFERENCES `USUARIOS__VINCULO_TIPO` (`CODE`),
  CONSTRAINT `REL-USER-VINCULO__USER-A` FOREIGN KEY (`USUARIO_A`) REFERENCES `USUARIOS` (`UID`),
  CONSTRAINT `REL-USER-VINCULO__USER-B` FOREIGN KEY (`USUARIO_B`) REFERENCES `USUARIOS` (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `USUARIOS__VINCULO_TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` int(11) NOT NULL,
  `TIPO` varchar(200) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

SET foreign_key_checks = 1;