-- EVENTO: EXPIRA_TOKEN_ACCESS

CREATE DEFINER=`root`@`localhost` EVENT `EXPIRA_TOKEN_ACCESS` ON SCHEDULE EVERY 10 SECOND STARTS '2024-02-18 14:02:53' ON COMPLETION NOT PRESERVE ENABLE DO DELETE FROM SYSTEM__TOKEN_ACCESS WHERE EXPIRE < NOW() OR EXPIRE IS NULL


-- EVENTO: LIMPA_SYSTEM__LIMIT_ACCESS

CREATE DEFINER=`root`@`localhost` EVENT `LIMPA_SYSTEM__LIMIT_ACCESS` ON SCHEDULE EVERY 30 SECOND STARTS '2024-02-18 14:02:53' ON COMPLETION NOT PRESERVE ENABLE DO DELETE FROM SYSTEM__LIMIT_ACCESS 
WHERE ((DATA_HORA < DATE_SUB(NOW(), INTERVAL 2 HOUR) AND CONGELA_ATE IS NULL) OR(CONGELA_ATE < DATE_SUB(NOW(), INTERVAL 2 HOUR)))


-- EVENTO: DELETE_TOKEN_SMS

CREATE DEFINER=`root`@`localhost` EVENT `DELETE_TOKEN_SMS` ON SCHEDULE EVERY 1 HOUR STARTS '2024-02-18 14:02:53' ON COMPLETION NOT PRESERVE ENABLE DO DELETE FROM SYSTEM__SMS_TOKEN WHERE EXPIREDATA < NOW()

