-- FUNCTION: FN_GET_CATEGORIAS_FRONT;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_CATEGORIAS_FRONT`(`P_ID` BIGINT) RETURNS text CHARSET utf8mb4
RETURN (
	SELECT 
	CONCAT(' categoria_',	GROUP_CONCAT(DISTINCT CAT.ID SEPARATOR	' categoria_'))	AS CATEGORIA
	FROM	PRODUTO__CATEGORIAS AS CAT
	INNER	JOIN PRODUTO__LINK_CAT AS LINK ON CAT.ID=LINK.UID_CAT
	WHERE	LINK.UID_PROD=P_ID
);

-- FUNCTION: FN_GET_INFO_PRODUTO_FRANQUIA;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_INFO_PRODUTO_FRANQUIA`(`P_CODE_PRODUTO` INT) RETURNS text CHARSET utf8mb4
BEGIN
    DECLARE v_json TEXT;
    
    SELECT JSON_OBJECT(
        'UID', FRANQUIAS.UID,
        'NOME', FRANQUIAS.NOME,
        'QTDD', COALESCE(SUM(FRANQUIAS__ESTOQUE.QUANTIDADE), 0)
    )
    INTO v_json
    FROM FRANQUIAS
    LEFT JOIN FRANQUIAS__ESTOQUE ON FRANQUIAS__ESTOQUE.ID_PRODUTO = P_CODE_PRODUTO
    WHERE FRANQUIAS.UID IS NOT NULL;

    RETURN v_json;
END;

-- FUNCTION: FN_GET_JSON_ADICIONAIS_CARRINHO;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_ADICIONAIS_CARRINHO`(`P_CARRINHO` INT) RETURNS text CHARSET utf8mb4
RETURN (
		SELECT CONCAT("[",GROUP_CONCAT(
				'{',
						'"ID":',DETALHES.ID,
						',"ADICIONAL":"',DETALHES.ADICIONAL,'"',
						',"VALOR":',DETALHES.VALOR,
						',"QTDD":',ADICIONAL.QTDD,
				'}'
),']')
		AS JSON
		FROM    PRODUTO__CARRINHO_ADICIONAIS ADICIONAL
		JOIN    PRODUTO__ADICIONAIS DETALHES ON  DETALHES.ID=ADICIONAL.ID_ADICIONAL
		WHERE   ID_ITEM_CARRINHO=P_CARRINHO
);

-- FUNCTION: FN_GET_JSON_ALL_IMG_PRODUTO;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_ALL_IMG_PRODUTO`(`P_ID` BIGINT) RETURNS text CHARSET utf8mb4
RETURN (
    SELECT CONCAT(
        '{',
        '"low":',FN_GET_JSON_IMG_PRODUTO(P_ID,"low"),',',
        '"lazy":',FN_GET_JSON_IMG_PRODUTO(P_ID,"lazy"),',',
        '"0":',FN_GET_JSON_IMG_PRODUTO(P_ID,0),',',
        '"50":',FN_GET_JSON_IMG_PRODUTO(P_ID,50),',',
        '"100":',FN_GET_JSON_IMG_PRODUTO(P_ID,100),',',
        '"500":',FN_GET_JSON_IMG_PRODUTO(P_ID,500),',',
        '"750":',FN_GET_JSON_IMG_PRODUTO(P_ID,750),'}'
    )
);

-- FUNCTION: FN_GET_JSON_BANNERS_BY_PLUGIN;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_BANNERS_BY_PLUGIN`(`P_ID` BIGINT) RETURNS text CHARSET utf8mb4
RETURN (
    SELECT CONCAT("[",GROUP_CONCAT('{
        "LINK":"',LINK,'",
        "TARGET":"',TARGET,'",
        "ANALITYCS":"',ANALITYCS,'",
        "CLICKTAG":"',CLICKTAG,'",
        "TITULO":"',TITULO,'",
        "DESCRICAO":"',DESCRICAO,'",
        "STATUS":"',STATUS,'"
    }'),']')
    AS JSON
    FROM MIDIA__BANNER
    WHERE	ID_PLUGIN=P_ID 
);

-- FUNCTION: FN_GET_JSON_CATEGORIAS_FRONT;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_CATEGORIAS_FRONT`(`P_ID` BIGINT) RETURNS text CHARSET utf8mb4
RETURN (
SELECT CONCAT("[",GROUP_CONCAT(
        '{',
            '"ID":',CAT.ID,
            ',"CATEGORIA":"',CAT.CATEGORIA,'"'
        '}'
),']')
	AS CATEGORIA
	FROM	PRODUTO__CATEGORIAS AS CAT
	INNER	JOIN PRODUTO__LINK_CAT AS LINK ON CAT.ID=LINK.UID_CAT
	WHERE	LINK.UID_PROD=P_ID
);

-- FUNCTION: FN_GET_JSON_FILES_BY_BANNERS;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_FILES_BY_BANNERS`(`P_ID` BIGINT) RETURNS text CHARSET utf8mb4
RETURN (
    SELECT CONCAT("[{",GROUP_CONCAT(
        '"',MEDIA_QUERY,'":{
            "ID_BANNER":"',ID_BANNER,'",
            "ID_PLUGIN":"',ID_PLUGIN,'",
            "NOME_ORIGINAL":"',NOME_ORIGINAL,'",
            "PATH":"',PATH,'",
            "FILENAME":"',FILENAME,'",
            "SIZE":"',SIZE,'",
            "TYPE":"',TYPE,'",
            "MEDIA_QUERY":"',MEDIA_QUERY,'"
        }'  
    ),'}]') 
    AS JSON
    FROM        MIDIA__FILES
    WHERE	    ID_BANNER   =   P_ID 
    ORDER BY    MEDIA_QUERY     ASC
)


-- SELECT FN_GET_JSON_FILES_BY_BANNERS(4);

-- FUNCTION: FN_GET_JSON_IMG_PRODUTO;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_IMG_PRODUTO`(`P_ID` BIGINT,`P_SIZE` VARCHAR(255)) RETURNS text CHARSET utf8mb4
RETURN (
    SELECT CONCAT("[",GROUP_CONCAT('"',PATH,'"'),']')
    AS JSON
    FROM PRODUTO__IMAGENS
    WHERE	ID_PROD=P_ID AND SIZE=P_SIZE
);

-- FUNCTION: FN_GET_JSON_PRODUTOS_ESTOQUE;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_PRODUTOS_ESTOQUE`(P_CODE_PRODUTO BIGINT) RETURNS text CHARSET utf8mb4
RETURN ( 
SELECT
    CONCAT(
        '[',
        GROUP_CONCAT(
            '{"UID":', UID, ',"NOME":"', NOME, '","QTDD":"', TOTAL, '"}'
            -- SEPARATOR ','
        ),']'
    ) AS JSON_RESULT
FROM (
    SELECT FRANQ.UID, FRANQ.NOME, COALESCE(SUM(ESTOQUE.QUANTIDADE), 0) AS TOTAL
    FROM FRANQUIAS__ESTOQUE AS ESTOQUE
    JOIN FRANQUIAS AS FRANQ ON ESTOQUE.ID_FRANQUIA = FRANQ.UID
    WHERE ESTOQUE.ID_PRODUTO = P_CODE_PRODUTO
    GROUP BY FRANQ.UID, FRANQ.NOME
) AS Subquery

);

-- FUNCTION: FN_GET_JSON_PRODUTOS_Q_SOU_VINC;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_PRODUTOS_Q_SOU_VINC`(`P_ID_PRODUTO` BIGINT) RETURNS text CHARSET utf8mb4
RETURN (
	SELECT COALESCE(
		CONCAT("[",GROUP_CONCAT(
			'{',
				'"CODE":',PRODUTO.CODE,
				',"NOME":"',PRODUTO.NOME,'"',
				',"DESCRICAO":"',PRODUTO.DESCRICAO,'"',
				',"DESCONTO_PCT":"',PRODUTO.OLD_VALOR,'"',
				',"VALOR_FECHADO":"',PRODUTO.VALOR,'"',
			'}'
		),']'),
		'[]'
	) AS JSON
	FROM PRODUTO
	INNER JOIN PRODUTO__VINCULO_PRODUTOS VINCULO
	ON PRODUTO.CODE = VINCULO.CODE_PROD_A 
	WHERE VINCULO.CODE_PROD_B = P_ID_PRODUTO
);

-- FUNCTION: FN_GET_JSON_PRODUTOS_VINC_A_MIM;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_PRODUTOS_VINC_A_MIM`(`P_ID_PRODUTO` BIGINT) RETURNS text CHARSET utf8mb4
RETURN (
	SELECT COALESCE(
		CONCAT("[",GROUP_CONCAT(
			'{',
				'"CODE":',PRODUTO.CODE,
				',"NOME":"',PRODUTO.NOME,'"',
				',"DESCRICAO":"',PRODUTO.DESCRICAO,'"',
				',"DESCONTO_PCT":"',PRODUTO.OLD_VALOR,'"',
				',"VALOR_FECHADO":"',PRODUTO.VALOR,'"',
			'}'
		),']'),
		'[]'
	) AS JSON
	FROM PRODUTO
	INNER JOIN PRODUTO__VINCULO_PRODUTOS VINCULO
	ON PRODUTO.CODE = VINCULO.CODE_PROD_B 
	WHERE VINCULO.CODE_PROD_A = P_ID_PRODUTO
);

-- FUNCTION: FN_GET_JSON_KITS;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_KITS`(`P_ID_PRODUTO` INT) RETURNS text CHARSET utf8mb4
RETURN (
     SELECT CONCAT("[",GROUP_CONCAT(
        '{',
            '"ID":',VINCULO.ID,
            ',"NOME":"',PRODUTO__KITS.NOME,'"',
            ',"DESCRICAO":"',PRODUTO__KITS.DESCRICAO,'"',
            ',"DESCONTO_PCT":"',PRODUTO__KITS.DESCONTO_PCT,'"',
            ',"VALOR_FECHADO":"',PRODUTO__KITS.VALOR_FECHADO,'"',
        '}'
    ),']')
    AS JSON
    FROM    PRODUTO__KITS
    JOIN    PRODUTO__VINCULO_KITS VINCULO
    ON      VINCULO.UID_KIT=PRODUTO__KITS.ID 
    WHERE   VINCULO.ID_PRODUTO=P_ID_PRODUTO
);

-- FUNCTION: FN_GET_JSON_VARIACOES;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_VARIACOES`(`P_ID` BIGINT) RETURNS text CHARSET utf8mb4
RETURN (
	SELECT
        CONCAT("[",
            GROUP_CONCAT(
                '{',
                    CONCAT('"ID":',ID,','),
                    CONCAT('"VARIACAO":"',VARIACAO,'",'),
                    CONCAT('"DESCRICAO":"',DESCRICAO,'",'),
                    CONCAT('"VALOR":',VALOR),
                '}'
            )
        ,"]") 
    AS JSON
    FROM PRODUTO__VARIACOES
    WHERE	UID_PRODUTO=P_ID
);

-- FUNCTION: FN_GET_JSON_BANNERS_BY_PLUGIN;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_BANNERS_BY_PLUGIN`(`P_ID` BIGINT) RETURNS text CHARSET utf8mb4
RETURN (
    SELECT CONCAT("[",GROUP_CONCAT('{
        "LINK":"',LINK,'",
        "TARGET":"',TARGET,'",
        "ANALITYCS":"',ANALITYCS,'",
        "CLICKTAG":"',CLICKTAG,'",
        "TITULO":"',TITULO,'",
        "DESCRICAO":"',DESCRICAO,'",
        "STATUS":"',STATUS,'"
    }'),']')
    AS JSON
    FROM MIDIA__BANNER
    WHERE	ID_PLUGIN=P_ID 
);

-- FUNCTION: FN_GET_JSON_FILES_BY_BANNERS;
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_JSON_FILES_BY_BANNERS`(`P_ID` BIGINT) RETURNS text CHARSET utf8mb4
RETURN (
    SELECT CONCAT("[{",GROUP_CONCAT(
        '"',MEDIA_QUERY,'":{
            "ID_BANNER":"',ID_BANNER,'",
            "ID_PLUGIN":"',ID_PLUGIN,'",
            "NOME_ORIGINAL":"',NOME_ORIGINAL,'",
            "PATH":"',PATH,'",
            "FILENAME":"',FILENAME,'",
            "SIZE":"',SIZE,'",
            "TYPE":"',TYPE,'",
            "MEDIA_QUERY":"',MEDIA_QUERY,'"
        }'  
    ),'}]') 
    AS JSON
    FROM        MIDIA__FILES
    WHERE	    ID_BANNER   =   P_ID 
    ORDER BY    MEDIA_QUERY     ASC
)


-- SELECT FN_GET_JSON_FILES_BY_BANNERS(4);
