-- TRIGGER: INSERT__BLOG;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__BLOG BEFORE INSERT ON BLOG
		FOR EACH ROW BEGIN
		SET @permitir_atualizacao= 1;
		SET new.FW_UID_LANG=UUID_SHORT();
			INSERT INTO BLOG__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'pt');
			INSERT INTO BLOG__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'en');
			INSERT INTO BLOG__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'es');

			UPDATE BLOG__TRANSLATE SET UID=NEW.UID,TITULO=NEW.TITULO,PREVIA=NEW.PREVIA,DESCRICAO=NEW.DESCRICAO,IMAGEM=NEW.IMAGEM WHERE FW_UID_LANG = new.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			SET NEW.UID=DEFAULT;
			SET NEW.TITULO=DEFAULT;
			SET NEW.PREVIA=DEFAULT;
			SET NEW.DESCRICAO=DEFAULT;
			SET NEW.IMAGEM=DEFAULT;
	END;

-- TRIGGER: INSERT_PRIMARY__BLOG;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT_PRIMARY__BLOG AFTER INSERT ON BLOG FOR EACH ROW	BEGIN
		SET @permitir_atualizacao = 1;
		SET @atualiza_id = 1;
		UPDATE BLOG__TRANSLATE SET ID_FW_PAI=NEW.ID WHERE(FW_UID_LANG=NEW.FW_UID_LANG);
	END;

-- TRIGGER: UPDATE__BLOG;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__BLOG BEFORE UPDATE ON BLOG FOR EACH ROW		BEGIN
			DECLARE record_count INT;
		IF @atualiza_id = 1 THEN
			SET @atualiza_id = 0;
		ELSE

				SET @permitir_atualizacao = 1;
				SELECT COUNT(*) INTO @record_count FROM BLOG__TRANSLATE WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG;
				IF @record_count > 0 THEN
					UPDATE BLOG__TRANSLATE SET 
UID=IF(NEW.UID IS NULL , UID, NEW.UID)
,TITULO=IF(NEW.TITULO IS NULL , TITULO, NEW.TITULO)
,PREVIA=IF(NEW.PREVIA IS NULL , PREVIA, NEW.PREVIA)
,DESCRICAO=IF(NEW.DESCRICAO IS NULL , DESCRICAO, NEW.DESCRICAO)
,IMAGEM=IF(NEW.IMAGEM IS NULL , IMAGEM, NEW.IMAGEM)
 WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			ELSE
				INSERT INTO BLOG__TRANSLATE ( ID,UID,TITULO,PREVIA,DESCRICAO,IMAGEM, FW_UID_LANG, FW_LANG) VALUES ( NEW.ID,NEW.UID,NEW.TITULO,NEW.PREVIA,NEW.DESCRICAO,NEW.IMAGEM,NEW.FW_UID_LANG, NEW.FW_LANG);
			END IF;
			SET NEW.UID=NULL;
			SET NEW.TITULO=NULL;
			SET NEW.PREVIA=NULL;
			SET NEW.DESCRICAO=NULL;
			SET NEW.IMAGEM=NULL;
			END IF;

		END;

-- TRIGGER: DELETE__BLOG;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__BLOG AFTER DELETE ON BLOG FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM BLOG__TRANSLATE WHERE FW_UID_LANG=OLD.FW_UID_LANG; 
	END;

-- TRIGGER: BLOG__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER BLOG__SECURITY_INSERT BEFORE INSERT ON BLOG__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: BLOG__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER BLOG__SECURITY_UPDATE BEFORE UPDATE ON BLOG__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: BLOG__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER BLOG__SECURITY_DELETE BEFORE DELETE ON BLOG__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: CODE CURSOS__AULAS;
CREATE DEFINER=`root`@`localhost` TRIGGER `CODE CURSOS__AULAS` BEFORE INSERT ON `CURSOS__AULAS` FOR EACH ROW SET new.CODE=UUID_SHORT();

-- TRIGGER: UID CURSOS_AULAS;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID CURSOS_AULAS` BEFORE INSERT ON `CURSOS__AULAS` FOR EACH ROW SET new.CODE=UUID_SHORT();

-- TRIGGER: CODE CURSOS__MATERIAL;
CREATE DEFINER=`root`@`localhost` TRIGGER `CODE CURSOS__MATERIAL` BEFORE INSERT ON `CURSOS__MATERIAL` FOR EACH ROW SET new.CODE=UUID_SHORT();

-- TRIGGER: CODE CURSOS__MATRICULA;
CREATE DEFINER=`root`@`localhost` TRIGGER `CODE CURSOS__MATRICULA` BEFORE INSERT ON `CURSOS__MATRICULA` FOR EACH ROW SET new.CODE=UUID_SHORT();

-- TRIGGER: UID CURSOS__MATRICULA;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID CURSOS__MATRICULA` BEFORE INSERT ON `CURSOS__MATRICULA` FOR EACH ROW SET new.CODE=UUID_SHORT();

-- TRIGGER: CODE CURSOS__MODULOS;
CREATE DEFINER=`root`@`localhost` TRIGGER `CODE CURSOS__MODULOS` BEFORE INSERT ON `CURSOS__MODULOS` FOR EACH ROW SET new.CODE=UUID_SHORT();

-- TRIGGER: UID CURSOS__MODULOS;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID CURSOS__MODULOS` BEFORE INSERT ON `CURSOS__MODULOS` FOR EACH ROW SET new.CODE=UUID_SHORT();

-- TRIGGER: UID_GALERIAS;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID_GALERIAS` BEFORE INSERT ON `GALERIAS__GALERIAS` FOR EACH ROW SET new.UID=FLOOR(RAND()*9007199254740991)+1;

-- TRIGGER: UID_GALERIAS_IMAGES;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID_GALERIAS_IMAGES` BEFORE INSERT ON `GALERIAS__IMAGENS` FOR EACH ROW SET new.UID=FLOOR(RAND()*9007199254740991)+1;

-- TRIGGER: UID_PLUGIN_GALERIAS;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID_PLUGIN_GALERIAS` BEFORE INSERT ON `GALERIAS__PLUGIN`
FOR EACH ROW SET new.UID=FLOOR(RAND()*9007199254740991)+1;

-- TRIGGER: TGR_CODE_PRODUTO;
CREATE DEFINER=`root`@`localhost` TRIGGER `TGR_CODE_PRODUTO` BEFORE INSERT ON `PRODUTO`
FOR EACH ROW SET new.CODE=FLOOR(RAND()*9007199254740991)+1;

-- TRIGGER: UPDATE__QUEMSOMOS;
CREATE DEFINER=`root`@`localhost` TRIGGER `UPDATE__QUEMSOMOS` AFTER UPDATE ON `QUEMSOMOS` FOR EACH ROW BEGIN
		    DECLARE record_count INT;
			SET @permitir_atualizacao = 1;
			SET @record_count = ( SELECT COUNT(*) FROM QUEMSOMOS__TRANSLATE WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG );
			IF  @record_count > 0 THEN 
				UPDATE QUEMSOMOS__TRANSLATE SET 
						SESSAO=IF(OLD.SESSAO!=NEW.SESSAO, NEW.SESSAO, SESSAO),
                        TITULO=IF(OLD.TITULO!=NEW.TITULO, NEW.TITULO, TITULO),
					 	TEXTO=IF(OLD.TEXTO!=NEW.TEXTO, NEW.TEXTO, TEXTO)
				WHERE ID_FW_PAI = NEW.ID AND FW_LANG = NEW.FW_LANG; 
			ELSE
				INSERT INTO QUEMSOMOS__TRANSLATE ( SESSAO,TITULO,TEXTO, ID_FW_PAI, FW_LANG) VALUES (NEW.SESSAO, NEW.TITULO,NEW.TEXTO,NEW.ID, NEW.FW_LANG);
			END IF; 

		END;

-- TRIGGER: TRG_UUID_SIGNAL_TRADER;
CREATE DEFINER=`root`@`localhost` TRIGGER `TRG_UUID_SIGNAL_TRADER` BEFORE INSERT ON `SIGNALS__COPYTRADER`
    FOR EACH ROW SET new.UID=FLOOR(RAND()*9007199254740991)+1;

-- TRIGGER: DELETE_SIGNALS_COPYTRADER_GRID;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE_SIGNALS_COPYTRADER_GRID AFTER DELETE ON SIGNALS__COPYTRADER
FOR EACH ROW  DELETE FROM SIGNALS__COPYTRADER_GRID WHERE CODE_SIGNAL = OLD.UID;

-- TRIGGER: UPDATE_SIGNALS_COPYTRADER_GRID;
CREATE DEFINER=`root`@`localhost` TRIGGER `UPDATE_SIGNALS_COPYTRADER_GRID` AFTER UPDATE ON `SIGNALS__COPYTRADER_GRID`
        FOR EACH ROW
        BEGIN
        DECLARE TOTAL_FINALIZADO    INT;
        DECLARE TOTAL_GRID          INT;

        SELECT COUNT(*) INTO TOTAL_GRID         FROM `SIGNALS__COPYTRADER_GRID` WHERE CODE_SIGNAL = NEW.CODE_SIGNAL;
        SELECT COUNT(*) INTO TOTAL_FINALIZADO   FROM `SIGNALS__COPYTRADER_GRID` WHERE CODE_SIGNAL = NEW.CODE_SIGNAL AND STATUS = 1;

        IF (TOTAL_FINALIZADO = TOTAL_GRID) THEN
            UPDATE SIGNALS__COPYTRADER SET STATUS=1 WHERE UID=NEW.CODE_SIGNAL;
        END IF;

    END;

-- TRIGGER: UID_SUPORTE;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID_SUPORTE` BEFORE INSERT ON `SUPORTE__CHAMADOS`
FOR EACH ROW SET new.UID=UUID_SHORT();

-- TRIGGER: EXPIRE_TOKEN_SMS;
CREATE DEFINER=`root`@`localhost` TRIGGER `EXPIRE_TOKEN_SMS` BEFORE INSERT ON `SYSTEM__SMS_TOKEN`
FOR EACH ROW SET NEW.EXPIREDATA=DATE_ADD(NOW(), INTERVAL 1 HOUR);

-- TRIGGER: TRG_UUID_BIOMETRY;
CREATE DEFINER=`root`@`localhost` TRIGGER `TRG_UUID_BIOMETRY` BEFORE INSERT ON `SYSTEM__VERSION` FOR EACH ROW SET new.CHALLENGE=UUID();

-- TRIGGER: INSERT__TEMPLATE__AREAS_ATUACAO;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__AREAS_ATUACAO BEFORE INSERT ON TEMPLATE__AREAS_ATUACAO
		FOR EACH ROW BEGIN
		SET @permitir_atualizacao= 1;
		SET new.FW_UID_LANG=UUID_SHORT();
			INSERT INTO TEMPLATE__AREAS_ATUACAO__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'pt');
			INSERT INTO TEMPLATE__AREAS_ATUACAO__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'en');
			INSERT INTO TEMPLATE__AREAS_ATUACAO__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'es');

			UPDATE TEMPLATE__AREAS_ATUACAO__TRANSLATE SET TITULO=NEW.TITULO,DESCRICAO=NEW.DESCRICAO,TIPO_ATUACAO=NEW.TIPO_ATUACAO WHERE FW_UID_LANG = new.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			SET NEW.TITULO=DEFAULT;
			SET NEW.DESCRICAO=DEFAULT;
			SET NEW.TIPO_ATUACAO=DEFAULT;
	END;

-- TRIGGER: INSERT_PRIMARY__TEMPLATE__AREAS_ATUACAO;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT_PRIMARY__TEMPLATE__AREAS_ATUACAO AFTER INSERT ON TEMPLATE__AREAS_ATUACAO FOR EACH ROW	BEGIN
		SET @permitir_atualizacao = 1;
		SET @atualiza_id = 1;
		UPDATE TEMPLATE__AREAS_ATUACAO__TRANSLATE SET ID_FW_PAI=NEW.ID WHERE(FW_UID_LANG=NEW.FW_UID_LANG);
	END;

-- TRIGGER: UPDATE__TEMPLATE__AREAS_ATUACAO;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__AREAS_ATUACAO BEFORE UPDATE ON TEMPLATE__AREAS_ATUACAO FOR EACH ROW		BEGIN
			DECLARE record_count INT;
		IF @atualiza_id = 1 THEN
			SET @atualiza_id = 0;
		ELSE

				SET @permitir_atualizacao = 1;
				SELECT COUNT(*) INTO @record_count FROM TEMPLATE__AREAS_ATUACAO__TRANSLATE WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG;
				IF @record_count > 0 THEN
					UPDATE TEMPLATE__AREAS_ATUACAO__TRANSLATE SET 
TITULO=IF(NEW.TITULO IS NULL , TITULO, NEW.TITULO)
,DESCRICAO=IF(NEW.DESCRICAO IS NULL , DESCRICAO, NEW.DESCRICAO)
,TIPO_ATUACAO=IF(NEW.TIPO_ATUACAO IS NULL , TIPO_ATUACAO, NEW.TIPO_ATUACAO)
 WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__AREAS_ATUACAO__TRANSLATE ( ID,TITULO,DESCRICAO,TIPO_ATUACAO,FW_LANG, FW_UID_LANG, FW_LANG) VALUES ( NEW.ID,NEW.TITULO,NEW.DESCRICAO,NEW.TIPO_ATUACAO,NEW.FW_LANG,NEW.FW_UID_LANG, NEW.FW_LANG);
			END IF;
			SET NEW.TITULO=NULL;
			SET NEW.DESCRICAO=NULL;
			SET NEW.TIPO_ATUACAO=NULL;
			END IF;

		END;

-- TRIGGER: DELETE__TEMPLATE__AREAS_ATUACAO;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__AREAS_ATUACAO AFTER DELETE ON TEMPLATE__AREAS_ATUACAO FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__AREAS_ATUACAO__TRANSLATE WHERE FW_UID_LANG=OLD.FW_UID_LANG; 
	END;

-- TRIGGER: INSERT__TEMPLATE__AREAS_ATUACAO_CONSULTORIA;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__AREAS_ATUACAO_CONSULTORIA BEFORE INSERT ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA
		FOR EACH ROW BEGIN
		SET @permitir_atualizacao= 1;
		SET new.FW_UID_LANG=UUID_SHORT();
			INSERT INTO TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'pt');
			INSERT INTO TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'en');
			INSERT INTO TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'es');

			UPDATE TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE SET TITULO=NEW.TITULO,DESCRICAO=NEW.DESCRICAO WHERE FW_UID_LANG = new.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			SET NEW.TITULO=DEFAULT;
			SET NEW.DESCRICAO=DEFAULT;
	END;

-- TRIGGER: INSERT_PRIMARY__TEMPLATE__AREAS_ATUACAO_CONSULTORIA;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT_PRIMARY__TEMPLATE__AREAS_ATUACAO_CONSULTORIA AFTER INSERT ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA FOR EACH ROW	BEGIN
		SET @permitir_atualizacao = 1;
		SET @atualiza_id = 1;
		UPDATE TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE SET ID_FW_PAI=NEW.ID WHERE(FW_UID_LANG=NEW.FW_UID_LANG);
	END;

-- TRIGGER: UPDATE__TEMPLATE__AREAS_ATUACAO_CONSULTORIA;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__AREAS_ATUACAO_CONSULTORIA BEFORE UPDATE ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA FOR EACH ROW		BEGIN
			DECLARE record_count INT;
		IF @atualiza_id = 1 THEN
			SET @atualiza_id = 0;
		ELSE

				SET @permitir_atualizacao = 1;
				SELECT COUNT(*) INTO @record_count FROM TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG;
				IF @record_count > 0 THEN
					UPDATE TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE SET 
TITULO=IF(NEW.TITULO IS NULL , TITULO, NEW.TITULO)
,DESCRICAO=IF(NEW.DESCRICAO IS NULL , DESCRICAO, NEW.DESCRICAO)
 WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE ( ID,TITULO,DESCRICAO,FW_LANG, FW_UID_LANG, FW_LANG) VALUES ( NEW.ID,NEW.TITULO,NEW.DESCRICAO,NEW.FW_LANG,NEW.FW_UID_LANG, NEW.FW_LANG);
			END IF;
			SET NEW.TITULO=NULL;
			SET NEW.DESCRICAO=NULL;
			END IF;

		END;

-- TRIGGER: DELETE__TEMPLATE__AREAS_ATUACAO_CONSULTORIA;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__AREAS_ATUACAO_CONSULTORIA AFTER DELETE ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE WHERE FW_UID_LANG=OLD.FW_UID_LANG; 
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_CONSULTORIA__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__AREAS_ATUACAO_CONSULTORIA__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: INSERT__TEMPLATE__AREAS_ATUACAO_PRODUTOS;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__AREAS_ATUACAO_PRODUTOS BEFORE INSERT ON TEMPLATE__AREAS_ATUACAO_PRODUTOS
		FOR EACH ROW BEGIN
		SET @permitir_atualizacao= 1;
		SET new.FW_UID_LANG=UUID_SHORT();
			INSERT INTO TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'pt');
			INSERT INTO TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'en');
			INSERT INTO TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'es');

			UPDATE TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE SET TITULO=NEW.TITULO,DESCRICAO=NEW.DESCRICAO WHERE FW_UID_LANG = new.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			SET NEW.TITULO=DEFAULT;
			SET NEW.DESCRICAO=DEFAULT;
	END;

-- TRIGGER: INSERT_PRIMARY__TEMPLATE__AREAS_ATUACAO_PRODUTOS;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT_PRIMARY__TEMPLATE__AREAS_ATUACAO_PRODUTOS AFTER INSERT ON TEMPLATE__AREAS_ATUACAO_PRODUTOS FOR EACH ROW	BEGIN
		SET @permitir_atualizacao = 1;
		SET @atualiza_id = 1;
		UPDATE TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE SET ID_FW_PAI=NEW.ID WHERE(FW_UID_LANG=NEW.FW_UID_LANG);
	END;

-- TRIGGER: UPDATE__TEMPLATE__AREAS_ATUACAO_PRODUTOS;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__AREAS_ATUACAO_PRODUTOS BEFORE UPDATE ON TEMPLATE__AREAS_ATUACAO_PRODUTOS FOR EACH ROW		BEGIN
			DECLARE record_count INT;
		IF @atualiza_id = 1 THEN
			SET @atualiza_id = 0;
		ELSE

				SET @permitir_atualizacao = 1;
				SELECT COUNT(*) INTO @record_count FROM TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG;
				IF @record_count > 0 THEN
					UPDATE TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE SET 
TITULO=IF(NEW.TITULO IS NULL , TITULO, NEW.TITULO)
,DESCRICAO=IF(NEW.DESCRICAO IS NULL , DESCRICAO, NEW.DESCRICAO)
 WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE ( ID,TITULO,DESCRICAO,FW_LANG, FW_UID_LANG, FW_LANG) VALUES ( NEW.ID,NEW.TITULO,NEW.DESCRICAO,NEW.FW_LANG,NEW.FW_UID_LANG, NEW.FW_LANG);
			END IF;
			SET NEW.TITULO=NULL;
			SET NEW.DESCRICAO=NULL;
			END IF;

		END;

-- TRIGGER: DELETE__TEMPLATE__AREAS_ATUACAO_PRODUTOS;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__AREAS_ATUACAO_PRODUTOS AFTER DELETE ON TEMPLATE__AREAS_ATUACAO_PRODUTOS FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE WHERE FW_UID_LANG=OLD.FW_UID_LANG; 
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO_PRODUTOS__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__AREAS_ATUACAO_PRODUTOS__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__AREAS_ATUACAO__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__AREAS_ATUACAO__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__AREAS_ATUACAO__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__AREAS_ATUACAO__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__AREAS_ATUACAO__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: INSERT__TEMPLATE__CONTATO;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__CONTATO BEFORE INSERT ON TEMPLATE__CONTATO
		FOR EACH ROW BEGIN
		SET @permitir_atualizacao= 1;
		SET new.FW_UID_LANG=UUID_SHORT();
			INSERT INTO TEMPLATE__CONTATO__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'pt');
			INSERT INTO TEMPLATE__CONTATO__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'en');
			INSERT INTO TEMPLATE__CONTATO__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'es');

			UPDATE TEMPLATE__CONTATO__TRANSLATE SET TOP_TITLE=NEW.TOP_TITLE,TITULO_FORM=NEW.TITULO_FORM,ADRESS_TITLE=NEW.ADRESS_TITLE,ADRESS_TEXT=NEW.ADRESS_TEXT,HORARIOS_TITLE=NEW.HORARIOS_TITLE,HORARIOS_TEXT=NEW.HORARIOS_TEXT,EMAILS_TITLE=NEW.EMAILS_TITLE,EMAILS_TEXT=NEW.EMAILS_TEXT,TEXTO_BOTAO=NEW.TEXTO_BOTAO,PLACEHOLDER_NOME=NEW.PLACEHOLDER_NOME,PLACEHOLDER_EMAIL=NEW.PLACEHOLDER_EMAIL,PLACEHOLDER_TELEFONE=NEW.PLACEHOLDER_TELEFONE,PLACEHOLDER_ASSUNTO=NEW.PLACEHOLDER_ASSUNTO,PLACEHOLDER_TEXTO=NEW.PLACEHOLDER_TEXTO WHERE FW_UID_LANG = new.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			SET NEW.TOP_TITLE=DEFAULT;
			SET NEW.TITULO_FORM=DEFAULT;
			SET NEW.ADRESS_TITLE=DEFAULT;
			SET NEW.ADRESS_TEXT=DEFAULT;
			SET NEW.HORARIOS_TITLE=DEFAULT;
			SET NEW.HORARIOS_TEXT=DEFAULT;
			SET NEW.EMAILS_TITLE=DEFAULT;
			SET NEW.EMAILS_TEXT=DEFAULT;
			SET NEW.TEXTO_BOTAO=DEFAULT;
			SET NEW.PLACEHOLDER_NOME=DEFAULT;
			SET NEW.PLACEHOLDER_EMAIL=DEFAULT;
			SET NEW.PLACEHOLDER_TELEFONE=DEFAULT;
			SET NEW.PLACEHOLDER_ASSUNTO=DEFAULT;
			SET NEW.PLACEHOLDER_TEXTO=DEFAULT;
	END;

-- TRIGGER: INSERT_PRIMARY__TEMPLATE__CONTATO;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT_PRIMARY__TEMPLATE__CONTATO AFTER INSERT ON TEMPLATE__CONTATO FOR EACH ROW	BEGIN
		SET @permitir_atualizacao = 1;
		SET @atualiza_id = 1;
		UPDATE TEMPLATE__CONTATO__TRANSLATE SET ID_FW_PAI=NEW.ID WHERE(FW_UID_LANG=NEW.FW_UID_LANG);
	END;

-- TRIGGER: UPDATE__TEMPLATE__CONTATO;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__CONTATO BEFORE UPDATE ON TEMPLATE__CONTATO FOR EACH ROW		BEGIN
			DECLARE record_count INT;
		IF @atualiza_id = 1 THEN
			SET @atualiza_id = 0;
		ELSE

				SET @permitir_atualizacao = 1;
				SELECT COUNT(*) INTO @record_count FROM TEMPLATE__CONTATO__TRANSLATE WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG;
				IF @record_count > 0 THEN
					UPDATE TEMPLATE__CONTATO__TRANSLATE SET 
TOP_TITLE=IF(NEW.TOP_TITLE IS NULL , TOP_TITLE, NEW.TOP_TITLE)
,TITULO_FORM=IF(NEW.TITULO_FORM IS NULL , TITULO_FORM, NEW.TITULO_FORM)
,ADRESS_TITLE=IF(NEW.ADRESS_TITLE IS NULL , ADRESS_TITLE, NEW.ADRESS_TITLE)
,ADRESS_TEXT=IF(NEW.ADRESS_TEXT IS NULL , ADRESS_TEXT, NEW.ADRESS_TEXT)
,HORARIOS_TITLE=IF(NEW.HORARIOS_TITLE IS NULL , HORARIOS_TITLE, NEW.HORARIOS_TITLE)
,HORARIOS_TEXT=IF(NEW.HORARIOS_TEXT IS NULL , HORARIOS_TEXT, NEW.HORARIOS_TEXT)
,EMAILS_TITLE=IF(NEW.EMAILS_TITLE IS NULL , EMAILS_TITLE, NEW.EMAILS_TITLE)
,EMAILS_TEXT=IF(NEW.EMAILS_TEXT IS NULL , EMAILS_TEXT, NEW.EMAILS_TEXT)
,TEXTO_BOTAO=IF(NEW.TEXTO_BOTAO IS NULL , TEXTO_BOTAO, NEW.TEXTO_BOTAO)
,PLACEHOLDER_NOME=IF(NEW.PLACEHOLDER_NOME IS NULL , PLACEHOLDER_NOME, NEW.PLACEHOLDER_NOME)
,PLACEHOLDER_EMAIL=IF(NEW.PLACEHOLDER_EMAIL IS NULL , PLACEHOLDER_EMAIL, NEW.PLACEHOLDER_EMAIL)
,PLACEHOLDER_TELEFONE=IF(NEW.PLACEHOLDER_TELEFONE IS NULL , PLACEHOLDER_TELEFONE, NEW.PLACEHOLDER_TELEFONE)
,PLACEHOLDER_ASSUNTO=IF(NEW.PLACEHOLDER_ASSUNTO IS NULL , PLACEHOLDER_ASSUNTO, NEW.PLACEHOLDER_ASSUNTO)
,PLACEHOLDER_TEXTO=IF(NEW.PLACEHOLDER_TEXTO IS NULL , PLACEHOLDER_TEXTO, NEW.PLACEHOLDER_TEXTO)
 WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__CONTATO__TRANSLATE ( ID,TOP_TITLE,TITULO_FORM,ADRESS_TITLE,ADRESS_TEXT,HORARIOS_TITLE,HORARIOS_TEXT,EMAILS_TITLE,EMAILS_TEXT,TEXTO_BOTAO,PLACEHOLDER_NOME,PLACEHOLDER_EMAIL,PLACEHOLDER_TELEFONE,PLACEHOLDER_ASSUNTO,PLACEHOLDER_TEXTO,FW_LANG,FW_UID_LANG, FW_UID_LANG, FW_LANG) VALUES ( NEW.ID,NEW.TOP_TITLE,NEW.TITULO_FORM,NEW.ADRESS_TITLE,NEW.ADRESS_TEXT,NEW.HORARIOS_TITLE,NEW.HORARIOS_TEXT,NEW.EMAILS_TITLE,NEW.EMAILS_TEXT,NEW.TEXTO_BOTAO,NEW.PLACEHOLDER_NOME,NEW.PLACEHOLDER_EMAIL,NEW.PLACEHOLDER_TELEFONE,NEW.PLACEHOLDER_ASSUNTO,NEW.PLACEHOLDER_TEXTO,NEW.FW_LANG,NEW.FW_UID_LANG,NEW.FW_UID_LANG, NEW.FW_LANG);
			END IF;
			SET NEW.TOP_TITLE=NULL;
			SET NEW.TITULO_FORM=NULL;
			SET NEW.ADRESS_TITLE=NULL;
			SET NEW.ADRESS_TEXT=NULL;
			SET NEW.HORARIOS_TITLE=NULL;
			SET NEW.HORARIOS_TEXT=NULL;
			SET NEW.EMAILS_TITLE=NULL;
			SET NEW.EMAILS_TEXT=NULL;
			SET NEW.TEXTO_BOTAO=NULL;
			SET NEW.PLACEHOLDER_NOME=NULL;
			SET NEW.PLACEHOLDER_EMAIL=NULL;
			SET NEW.PLACEHOLDER_TELEFONE=NULL;
			SET NEW.PLACEHOLDER_ASSUNTO=NULL;
			SET NEW.PLACEHOLDER_TEXTO=NULL;
			END IF;

		END;

-- TRIGGER: DELETE__TEMPLATE__CONTATO;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__CONTATO AFTER DELETE ON TEMPLATE__CONTATO FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__CONTATO__TRANSLATE WHERE FW_UID_LANG=OLD.FW_UID_LANG; 
	END;

-- TRIGGER: TEMPLATE__CONTATO__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__CONTATO__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__CONTATO__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__CONTATO__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__CONTATO__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__CONTATO__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__CONTATO__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__CONTATO__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__CONTATO__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: INSERT__TEMPLATE__HOME;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__HOME BEFORE INSERT ON TEMPLATE__HOME
		FOR EACH ROW BEGIN
		SET @permitir_atualizacao= 1;
		SET new.FW_UID_LANG=UUID_SHORT();
			INSERT INTO TEMPLATE__HOME__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'pt');
			INSERT INTO TEMPLATE__HOME__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'en');
			INSERT INTO TEMPLATE__HOME__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'es');

			UPDATE TEMPLATE__HOME__TRANSLATE SET OUTRAS_SOLUCOES=NEW.OUTRAS_SOLUCOES,OUTRAS_SOLUCOES_TXT=NEW.OUTRAS_SOLUCOES_TXT,ANOS_EXP_NUM=NEW.ANOS_EXP_NUM,ANOS_EXP_TXT=NEW.ANOS_EXP_TXT,ANOS_EXP_DESC=NEW.ANOS_EXP_DESC WHERE FW_UID_LANG = new.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			SET NEW.OUTRAS_SOLUCOES=DEFAULT;
			SET NEW.OUTRAS_SOLUCOES_TXT=DEFAULT;
			SET NEW.ANOS_EXP_NUM=DEFAULT;
			SET NEW.ANOS_EXP_TXT=DEFAULT;
			SET NEW.ANOS_EXP_DESC=DEFAULT;
	END;

-- TRIGGER: INSERT_PRIMARY__TEMPLATE__HOME;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT_PRIMARY__TEMPLATE__HOME AFTER INSERT ON TEMPLATE__HOME FOR EACH ROW	BEGIN
		SET @permitir_atualizacao = 1;
		SET @atualiza_id = 1;
		UPDATE TEMPLATE__HOME__TRANSLATE SET ID_FW_PAI=NEW.ID WHERE(FW_UID_LANG=NEW.FW_UID_LANG);
	END;

-- TRIGGER: UPDATE__TEMPLATE__HOME;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__HOME BEFORE UPDATE ON TEMPLATE__HOME FOR EACH ROW		BEGIN
			DECLARE record_count INT;
		IF @atualiza_id = 1 THEN
			SET @atualiza_id = 0;
		ELSE

				SET @permitir_atualizacao = 1;
				SELECT COUNT(*) INTO @record_count FROM TEMPLATE__HOME__TRANSLATE WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG;
				IF @record_count > 0 THEN
					UPDATE TEMPLATE__HOME__TRANSLATE SET 
OUTRAS_SOLUCOES=IF(NEW.OUTRAS_SOLUCOES IS NULL , OUTRAS_SOLUCOES, NEW.OUTRAS_SOLUCOES)
,OUTRAS_SOLUCOES_TXT=IF(NEW.OUTRAS_SOLUCOES_TXT IS NULL , OUTRAS_SOLUCOES_TXT, NEW.OUTRAS_SOLUCOES_TXT)
,ANOS_EXP_NUM=IF(NEW.ANOS_EXP_NUM IS NULL , ANOS_EXP_NUM, NEW.ANOS_EXP_NUM)
,ANOS_EXP_TXT=IF(NEW.ANOS_EXP_TXT IS NULL , ANOS_EXP_TXT, NEW.ANOS_EXP_TXT)
,ANOS_EXP_DESC=IF(NEW.ANOS_EXP_DESC IS NULL , ANOS_EXP_DESC, NEW.ANOS_EXP_DESC)
 WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__HOME__TRANSLATE ( ID,OUTRAS_SOLUCOES,OUTRAS_SOLUCOES_TXT,ANOS_EXP_NUM,ANOS_EXP_TXT,ANOS_EXP_DESC,FW_LANG,FW_UID_LANG, FW_UID_LANG, FW_LANG) VALUES ( NEW.ID,NEW.OUTRAS_SOLUCOES,NEW.OUTRAS_SOLUCOES_TXT,NEW.ANOS_EXP_NUM,NEW.ANOS_EXP_TXT,NEW.ANOS_EXP_DESC,NEW.FW_LANG,NEW.FW_UID_LANG,NEW.FW_UID_LANG, NEW.FW_LANG);
			END IF;
			SET NEW.OUTRAS_SOLUCOES=NULL;
			SET NEW.OUTRAS_SOLUCOES_TXT=NULL;
			SET NEW.ANOS_EXP_NUM=NULL;
			SET NEW.ANOS_EXP_TXT=NULL;
			SET NEW.ANOS_EXP_DESC=NULL;
			END IF;

		END;

-- TRIGGER: DELETE__TEMPLATE__HOME;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__HOME AFTER DELETE ON TEMPLATE__HOME FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__HOME__TRANSLATE WHERE FW_UID_LANG=OLD.FW_UID_LANG; 
	END;

-- TRIGGER: TEMPLATE__HOME__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__HOME__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__HOME__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__HOME__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__HOME__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__HOME__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__HOME__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__HOME__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__HOME__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: INSERT__TEMPLATE__STATIC;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT__TEMPLATE__STATIC BEFORE INSERT ON TEMPLATE__STATIC
		FOR EACH ROW BEGIN
		SET @permitir_atualizacao= 1;
		SET new.FW_UID_LANG=UUID_SHORT();
			INSERT INTO TEMPLATE__STATIC__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'pt');
			INSERT INTO TEMPLATE__STATIC__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'en');
			INSERT INTO TEMPLATE__STATIC__TRANSLATE (FW_UID_LANG, FW_LANG) VALUES (NEW.FW_UID_LANG, 'es');

			UPDATE TEMPLATE__STATIC__TRANSLATE SET MENU_LABEL_HOME=NEW.MENU_LABEL_HOME,MENU_LABEL_EMPRESA=NEW.MENU_LABEL_EMPRESA,MENU_LABEL_ATUACAO=NEW.MENU_LABEL_ATUACAO,MENU_LABEL_DOC=NEW.MENU_LABEL_DOC,MENU_LABEL_CLIENTES=NEW.MENU_LABEL_CLIENTES,MENU_LABEL_CASES=NEW.MENU_LABEL_CASES,MENU_LABEL_CONTATO=NEW.MENU_LABEL_CONTATO,MENU_LINK_HOME=NEW.MENU_LINK_HOME,MENU_LINK_EMPRESA=NEW.MENU_LINK_EMPRESA,MENU_LINK_ATUACAO=NEW.MENU_LINK_ATUACAO,MENU_LINK_DOC=NEW.MENU_LINK_DOC,MENU_LINK_CLIENTES=NEW.MENU_LINK_CLIENTES,MENU_LINK_CASES=NEW.MENU_LINK_CASES,MENU_LINK_CONTATO=NEW.MENU_LINK_CONTATO,MENU_LABEL_ATUACAO_DOC=NEW.MENU_LABEL_ATUACAO_DOC,MENU_LINK_ATUACAO_DOC=NEW.MENU_LINK_ATUACAO_DOC,MENU_LABEL_ATUACAO_PROD=NEW.MENU_LABEL_ATUACAO_PROD,MENU_LINK_ATUACAO_PROD=NEW.MENU_LINK_ATUACAO_PROD,MENU_LABEL_ATUACAO_CONS=NEW.MENU_LABEL_ATUACAO_CONS,MENU_LINK_ATUACAO_CONS=NEW.MENU_LINK_ATUACAO_CONS,HEADER_NEWSLETTER_TITULO=NEW.HEADER_NEWSLETTER_TITULO,HEADER_NEWSLETTER_DESC=NEW.HEADER_NEWSLETTER_DESC,HEADER_PLACEHOLDER=NEW.HEADER_PLACEHOLDER,HEADER_ABOUT_TITULO=NEW.HEADER_ABOUT_TITULO,HEADER_ABOUT_DESC=NEW.HEADER_ABOUT_DESC,HEADER_TELEFONE=NEW.HEADER_TELEFONE,HEADER_ENDERECO=NEW.HEADER_ENDERECO,HEADER_NEWSLETTER_BUTTON=NEW.HEADER_NEWSLETTER_BUTTON,HEADER_COPYRIGHT=NEW.HEADER_COPYRIGHT,FOOTER_NEWSLETTER_TITULO=NEW.FOOTER_NEWSLETTER_TITULO,FOOTER_NEWSLETTER_DESC=NEW.FOOTER_NEWSLETTER_DESC,FOOTER_PLACEHOLDER=NEW.FOOTER_PLACEHOLDER,FOOTER_ABOUT_TITULO=NEW.FOOTER_ABOUT_TITULO,FOOTER_ABOUT_DESC=NEW.FOOTER_ABOUT_DESC,FOOTER_TELEFONE=NEW.FOOTER_TELEFONE,FOOTER_ENDERECO=NEW.FOOTER_ENDERECO,FOOTER_NEWSLETTER_BUTTON=NEW.FOOTER_NEWSLETTER_BUTTON,FOOTER_COPYRIGHT=NEW.FOOTER_COPYRIGHT,FOOTER_LINK_COPYRIGHT=NEW.FOOTER_LINK_COPYRIGHT,TITULO_AREAS=NEW.TITULO_AREAS,TITULO_CLIENTES=NEW.TITULO_CLIENTES,TITULO_ATUACAO_CONSULT=NEW.TITULO_ATUACAO_CONSULT,TITULO_ATUACAO_DOC=NEW.TITULO_ATUACAO_DOC,TITULO_ATUACAO_PROD=NEW.TITULO_ATUACAO_PROD,TITULO_SOBRE_NOS=NEW.TITULO_SOBRE_NOS,TITULO_CONTATOS=NEW.TITULO_CONTATOS WHERE FW_UID_LANG = new.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			SET NEW.MENU_LABEL_HOME=DEFAULT;
			SET NEW.MENU_LABEL_EMPRESA=DEFAULT;
			SET NEW.MENU_LABEL_ATUACAO=DEFAULT;
			SET NEW.MENU_LABEL_DOC=DEFAULT;
			SET NEW.MENU_LABEL_CLIENTES=DEFAULT;
			SET NEW.MENU_LABEL_CASES=DEFAULT;
			SET NEW.MENU_LABEL_CONTATO=DEFAULT;
			SET NEW.MENU_LINK_HOME=DEFAULT;
			SET NEW.MENU_LINK_EMPRESA=DEFAULT;
			SET NEW.MENU_LINK_ATUACAO=DEFAULT;
			SET NEW.MENU_LINK_DOC=DEFAULT;
			SET NEW.MENU_LINK_CLIENTES=DEFAULT;
			SET NEW.MENU_LINK_CASES=DEFAULT;
			SET NEW.MENU_LINK_CONTATO=DEFAULT;
			SET NEW.MENU_LABEL_ATUACAO_DOC=DEFAULT;
			SET NEW.MENU_LINK_ATUACAO_DOC=DEFAULT;
			SET NEW.MENU_LABEL_ATUACAO_PROD=DEFAULT;
			SET NEW.MENU_LINK_ATUACAO_PROD=DEFAULT;
			SET NEW.MENU_LABEL_ATUACAO_CONS=DEFAULT;
			SET NEW.MENU_LINK_ATUACAO_CONS=DEFAULT;
			SET NEW.HEADER_NEWSLETTER_TITULO=DEFAULT;
			SET NEW.HEADER_NEWSLETTER_DESC=DEFAULT;
			SET NEW.HEADER_PLACEHOLDER=DEFAULT;
			SET NEW.HEADER_ABOUT_TITULO=DEFAULT;
			SET NEW.HEADER_ABOUT_DESC=DEFAULT;
			SET NEW.HEADER_TELEFONE=DEFAULT;
			SET NEW.HEADER_ENDERECO=DEFAULT;
			SET NEW.HEADER_NEWSLETTER_BUTTON=DEFAULT;
			SET NEW.HEADER_COPYRIGHT=DEFAULT;
			SET NEW.FOOTER_NEWSLETTER_TITULO=DEFAULT;
			SET NEW.FOOTER_NEWSLETTER_DESC=DEFAULT;
			SET NEW.FOOTER_PLACEHOLDER=DEFAULT;
			SET NEW.FOOTER_ABOUT_TITULO=DEFAULT;
			SET NEW.FOOTER_ABOUT_DESC=DEFAULT;
			SET NEW.FOOTER_TELEFONE=DEFAULT;
			SET NEW.FOOTER_ENDERECO=DEFAULT;
			SET NEW.FOOTER_NEWSLETTER_BUTTON=DEFAULT;
			SET NEW.FOOTER_COPYRIGHT=DEFAULT;
			SET NEW.FOOTER_LINK_COPYRIGHT=DEFAULT;
			SET NEW.TITULO_AREAS=DEFAULT;
			SET NEW.TITULO_CLIENTES=DEFAULT;
			SET NEW.TITULO_ATUACAO_CONSULT=DEFAULT;
			SET NEW.TITULO_ATUACAO_DOC=DEFAULT;
			SET NEW.TITULO_ATUACAO_PROD=DEFAULT;
			SET NEW.TITULO_SOBRE_NOS=DEFAULT;
			SET NEW.TITULO_CONTATOS=DEFAULT;
	END;

-- TRIGGER: INSERT_PRIMARY__TEMPLATE__STATIC;
CREATE DEFINER=`root`@`localhost` TRIGGER INSERT_PRIMARY__TEMPLATE__STATIC AFTER INSERT ON TEMPLATE__STATIC FOR EACH ROW	BEGIN
		SET @permitir_atualizacao = 1;
		SET @atualiza_id = 1;
		UPDATE TEMPLATE__STATIC__TRANSLATE SET ID_FW_PAI=NEW.ID WHERE(FW_UID_LANG=NEW.FW_UID_LANG);
	END;

-- TRIGGER: UPDATE__TEMPLATE__STATIC;
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE__TEMPLATE__STATIC BEFORE UPDATE ON TEMPLATE__STATIC FOR EACH ROW		BEGIN
			DECLARE record_count INT;
		IF @atualiza_id = 1 THEN
			SET @atualiza_id = 0;
		ELSE

				SET @permitir_atualizacao = 1;
				SELECT COUNT(*) INTO @record_count FROM TEMPLATE__STATIC__TRANSLATE WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG;
				IF @record_count > 0 THEN
					UPDATE TEMPLATE__STATIC__TRANSLATE SET 
MENU_LABEL_HOME=IF(NEW.MENU_LABEL_HOME IS NULL , MENU_LABEL_HOME, NEW.MENU_LABEL_HOME)
,MENU_LABEL_EMPRESA=IF(NEW.MENU_LABEL_EMPRESA IS NULL , MENU_LABEL_EMPRESA, NEW.MENU_LABEL_EMPRESA)
,MENU_LABEL_ATUACAO=IF(NEW.MENU_LABEL_ATUACAO IS NULL , MENU_LABEL_ATUACAO, NEW.MENU_LABEL_ATUACAO)
,MENU_LABEL_DOC=IF(NEW.MENU_LABEL_DOC IS NULL , MENU_LABEL_DOC, NEW.MENU_LABEL_DOC)
,MENU_LABEL_CLIENTES=IF(NEW.MENU_LABEL_CLIENTES IS NULL , MENU_LABEL_CLIENTES, NEW.MENU_LABEL_CLIENTES)
,MENU_LABEL_CASES=IF(NEW.MENU_LABEL_CASES IS NULL , MENU_LABEL_CASES, NEW.MENU_LABEL_CASES)
,MENU_LABEL_CONTATO=IF(NEW.MENU_LABEL_CONTATO IS NULL , MENU_LABEL_CONTATO, NEW.MENU_LABEL_CONTATO)
,MENU_LINK_HOME=IF(NEW.MENU_LINK_HOME IS NULL , MENU_LINK_HOME, NEW.MENU_LINK_HOME)
,MENU_LINK_EMPRESA=IF(NEW.MENU_LINK_EMPRESA IS NULL , MENU_LINK_EMPRESA, NEW.MENU_LINK_EMPRESA)
,MENU_LINK_ATUACAO=IF(NEW.MENU_LINK_ATUACAO IS NULL , MENU_LINK_ATUACAO, NEW.MENU_LINK_ATUACAO)
,MENU_LINK_DOC=IF(NEW.MENU_LINK_DOC IS NULL , MENU_LINK_DOC, NEW.MENU_LINK_DOC)
,MENU_LINK_CLIENTES=IF(NEW.MENU_LINK_CLIENTES IS NULL , MENU_LINK_CLIENTES, NEW.MENU_LINK_CLIENTES)
,MENU_LINK_CASES=IF(NEW.MENU_LINK_CASES IS NULL , MENU_LINK_CASES, NEW.MENU_LINK_CASES)
,MENU_LINK_CONTATO=IF(NEW.MENU_LINK_CONTATO IS NULL , MENU_LINK_CONTATO, NEW.MENU_LINK_CONTATO)
,MENU_LABEL_ATUACAO_DOC=IF(NEW.MENU_LABEL_ATUACAO_DOC IS NULL , MENU_LABEL_ATUACAO_DOC, NEW.MENU_LABEL_ATUACAO_DOC)
,MENU_LINK_ATUACAO_DOC=IF(NEW.MENU_LINK_ATUACAO_DOC IS NULL , MENU_LINK_ATUACAO_DOC, NEW.MENU_LINK_ATUACAO_DOC)
,MENU_LABEL_ATUACAO_PROD=IF(NEW.MENU_LABEL_ATUACAO_PROD IS NULL , MENU_LABEL_ATUACAO_PROD, NEW.MENU_LABEL_ATUACAO_PROD)
,MENU_LINK_ATUACAO_PROD=IF(NEW.MENU_LINK_ATUACAO_PROD IS NULL , MENU_LINK_ATUACAO_PROD, NEW.MENU_LINK_ATUACAO_PROD)
,MENU_LABEL_ATUACAO_CONS=IF(NEW.MENU_LABEL_ATUACAO_CONS IS NULL , MENU_LABEL_ATUACAO_CONS, NEW.MENU_LABEL_ATUACAO_CONS)
,MENU_LINK_ATUACAO_CONS=IF(NEW.MENU_LINK_ATUACAO_CONS IS NULL , MENU_LINK_ATUACAO_CONS, NEW.MENU_LINK_ATUACAO_CONS)
,HEADER_NEWSLETTER_TITULO=IF(NEW.HEADER_NEWSLETTER_TITULO IS NULL , HEADER_NEWSLETTER_TITULO, NEW.HEADER_NEWSLETTER_TITULO)
,HEADER_NEWSLETTER_DESC=IF(NEW.HEADER_NEWSLETTER_DESC IS NULL , HEADER_NEWSLETTER_DESC, NEW.HEADER_NEWSLETTER_DESC)
,HEADER_PLACEHOLDER=IF(NEW.HEADER_PLACEHOLDER IS NULL , HEADER_PLACEHOLDER, NEW.HEADER_PLACEHOLDER)
,HEADER_ABOUT_TITULO=IF(NEW.HEADER_ABOUT_TITULO IS NULL , HEADER_ABOUT_TITULO, NEW.HEADER_ABOUT_TITULO)
,HEADER_ABOUT_DESC=IF(NEW.HEADER_ABOUT_DESC IS NULL , HEADER_ABOUT_DESC, NEW.HEADER_ABOUT_DESC)
,HEADER_TELEFONE=IF(NEW.HEADER_TELEFONE IS NULL , HEADER_TELEFONE, NEW.HEADER_TELEFONE)
,HEADER_ENDERECO=IF(NEW.HEADER_ENDERECO IS NULL , HEADER_ENDERECO, NEW.HEADER_ENDERECO)
,HEADER_NEWSLETTER_BUTTON=IF(NEW.HEADER_NEWSLETTER_BUTTON IS NULL , HEADER_NEWSLETTER_BUTTON, NEW.HEADER_NEWSLETTER_BUTTON)
,HEADER_COPYRIGHT=IF(NEW.HEADER_COPYRIGHT IS NULL , HEADER_COPYRIGHT, NEW.HEADER_COPYRIGHT)
,FOOTER_NEWSLETTER_TITULO=IF(NEW.FOOTER_NEWSLETTER_TITULO IS NULL , FOOTER_NEWSLETTER_TITULO, NEW.FOOTER_NEWSLETTER_TITULO)
,FOOTER_NEWSLETTER_DESC=IF(NEW.FOOTER_NEWSLETTER_DESC IS NULL , FOOTER_NEWSLETTER_DESC, NEW.FOOTER_NEWSLETTER_DESC)
,FOOTER_PLACEHOLDER=IF(NEW.FOOTER_PLACEHOLDER IS NULL , FOOTER_PLACEHOLDER, NEW.FOOTER_PLACEHOLDER)
,FOOTER_ABOUT_TITULO=IF(NEW.FOOTER_ABOUT_TITULO IS NULL , FOOTER_ABOUT_TITULO, NEW.FOOTER_ABOUT_TITULO)
,FOOTER_ABOUT_DESC=IF(NEW.FOOTER_ABOUT_DESC IS NULL , FOOTER_ABOUT_DESC, NEW.FOOTER_ABOUT_DESC)
,FOOTER_TELEFONE=IF(NEW.FOOTER_TELEFONE IS NULL , FOOTER_TELEFONE, NEW.FOOTER_TELEFONE)
,FOOTER_ENDERECO=IF(NEW.FOOTER_ENDERECO IS NULL , FOOTER_ENDERECO, NEW.FOOTER_ENDERECO)
,FOOTER_NEWSLETTER_BUTTON=IF(NEW.FOOTER_NEWSLETTER_BUTTON IS NULL , FOOTER_NEWSLETTER_BUTTON, NEW.FOOTER_NEWSLETTER_BUTTON)
,FOOTER_COPYRIGHT=IF(NEW.FOOTER_COPYRIGHT IS NULL , FOOTER_COPYRIGHT, NEW.FOOTER_COPYRIGHT)
,FOOTER_LINK_COPYRIGHT=IF(NEW.FOOTER_LINK_COPYRIGHT IS NULL , FOOTER_LINK_COPYRIGHT, NEW.FOOTER_LINK_COPYRIGHT)
,TITULO_AREAS=IF(NEW.TITULO_AREAS IS NULL , TITULO_AREAS, NEW.TITULO_AREAS)
,TITULO_CLIENTES=IF(NEW.TITULO_CLIENTES IS NULL , TITULO_CLIENTES, NEW.TITULO_CLIENTES)
,TITULO_ATUACAO_CONSULT=IF(NEW.TITULO_ATUACAO_CONSULT IS NULL , TITULO_ATUACAO_CONSULT, NEW.TITULO_ATUACAO_CONSULT)
,TITULO_ATUACAO_DOC=IF(NEW.TITULO_ATUACAO_DOC IS NULL , TITULO_ATUACAO_DOC, NEW.TITULO_ATUACAO_DOC)
,TITULO_ATUACAO_PROD=IF(NEW.TITULO_ATUACAO_PROD IS NULL , TITULO_ATUACAO_PROD, NEW.TITULO_ATUACAO_PROD)
,TITULO_SOBRE_NOS=IF(NEW.TITULO_SOBRE_NOS IS NULL , TITULO_SOBRE_NOS, NEW.TITULO_SOBRE_NOS)
,TITULO_CONTATOS=IF(NEW.TITULO_CONTATOS IS NULL , TITULO_CONTATOS, NEW.TITULO_CONTATOS)
 WHERE FW_UID_LANG=NEW.FW_UID_LANG AND FW_LANG=NEW.FW_LANG; 
			ELSE
				INSERT INTO TEMPLATE__STATIC__TRANSLATE ( ID,MENU_LABEL_HOME,MENU_LABEL_EMPRESA,MENU_LABEL_ATUACAO,MENU_LABEL_DOC,MENU_LABEL_CLIENTES,MENU_LABEL_CASES,MENU_LABEL_CONTATO,MENU_LINK_HOME,MENU_LINK_EMPRESA,MENU_LINK_ATUACAO,MENU_LINK_DOC,MENU_LINK_CLIENTES,MENU_LINK_CASES,MENU_LINK_CONTATO,MENU_LABEL_ATUACAO_DOC,MENU_LINK_ATUACAO_DOC,MENU_LABEL_ATUACAO_PROD,MENU_LINK_ATUACAO_PROD,MENU_LABEL_ATUACAO_CONS,MENU_LINK_ATUACAO_CONS,HEADER_NEWSLETTER_TITULO,HEADER_NEWSLETTER_DESC,HEADER_PLACEHOLDER,HEADER_ABOUT_TITULO,HEADER_ABOUT_DESC,HEADER_TELEFONE,HEADER_ENDERECO,HEADER_NEWSLETTER_BUTTON,HEADER_COPYRIGHT,FOOTER_NEWSLETTER_TITULO,FOOTER_NEWSLETTER_DESC,FOOTER_PLACEHOLDER,FOOTER_ABOUT_TITULO,FOOTER_ABOUT_DESC,FOOTER_TELEFONE,FOOTER_ENDERECO,FOOTER_NEWSLETTER_BUTTON,FOOTER_COPYRIGHT,FOOTER_LINK_COPYRIGHT,TITULO_AREAS,TITULO_CLIENTES,TITULO_ATUACAO_CONSULT,TITULO_ATUACAO_DOC,TITULO_ATUACAO_PROD,TITULO_SOBRE_NOS,TITULO_CONTATOS,FW_LANG,FW_UID_LANG, FW_UID_LANG, FW_LANG) VALUES ( NEW.ID,NEW.MENU_LABEL_HOME,NEW.MENU_LABEL_EMPRESA,NEW.MENU_LABEL_ATUACAO,NEW.MENU_LABEL_DOC,NEW.MENU_LABEL_CLIENTES,NEW.MENU_LABEL_CASES,NEW.MENU_LABEL_CONTATO,NEW.MENU_LINK_HOME,NEW.MENU_LINK_EMPRESA,NEW.MENU_LINK_ATUACAO,NEW.MENU_LINK_DOC,NEW.MENU_LINK_CLIENTES,NEW.MENU_LINK_CASES,NEW.MENU_LINK_CONTATO,NEW.MENU_LABEL_ATUACAO_DOC,NEW.MENU_LINK_ATUACAO_DOC,NEW.MENU_LABEL_ATUACAO_PROD,NEW.MENU_LINK_ATUACAO_PROD,NEW.MENU_LABEL_ATUACAO_CONS,NEW.MENU_LINK_ATUACAO_CONS,NEW.HEADER_NEWSLETTER_TITULO,NEW.HEADER_NEWSLETTER_DESC,NEW.HEADER_PLACEHOLDER,NEW.HEADER_ABOUT_TITULO,NEW.HEADER_ABOUT_DESC,NEW.HEADER_TELEFONE,NEW.HEADER_ENDERECO,NEW.HEADER_NEWSLETTER_BUTTON,NEW.HEADER_COPYRIGHT,NEW.FOOTER_NEWSLETTER_TITULO,NEW.FOOTER_NEWSLETTER_DESC,NEW.FOOTER_PLACEHOLDER,NEW.FOOTER_ABOUT_TITULO,NEW.FOOTER_ABOUT_DESC,NEW.FOOTER_TELEFONE,NEW.FOOTER_ENDERECO,NEW.FOOTER_NEWSLETTER_BUTTON,NEW.FOOTER_COPYRIGHT,NEW.FOOTER_LINK_COPYRIGHT,NEW.TITULO_AREAS,NEW.TITULO_CLIENTES,NEW.TITULO_ATUACAO_CONSULT,NEW.TITULO_ATUACAO_DOC,NEW.TITULO_ATUACAO_PROD,NEW.TITULO_SOBRE_NOS,NEW.TITULO_CONTATOS,NEW.FW_LANG,NEW.FW_UID_LANG,NEW.FW_UID_LANG, NEW.FW_LANG);
			END IF;
			SET NEW.MENU_LABEL_HOME=NULL;
			SET NEW.MENU_LABEL_EMPRESA=NULL;
			SET NEW.MENU_LABEL_ATUACAO=NULL;
			SET NEW.MENU_LABEL_DOC=NULL;
			SET NEW.MENU_LABEL_CLIENTES=NULL;
			SET NEW.MENU_LABEL_CASES=NULL;
			SET NEW.MENU_LABEL_CONTATO=NULL;
			SET NEW.MENU_LINK_HOME=NULL;
			SET NEW.MENU_LINK_EMPRESA=NULL;
			SET NEW.MENU_LINK_ATUACAO=NULL;
			SET NEW.MENU_LINK_DOC=NULL;
			SET NEW.MENU_LINK_CLIENTES=NULL;
			SET NEW.MENU_LINK_CASES=NULL;
			SET NEW.MENU_LINK_CONTATO=NULL;
			SET NEW.MENU_LABEL_ATUACAO_DOC=NULL;
			SET NEW.MENU_LINK_ATUACAO_DOC=NULL;
			SET NEW.MENU_LABEL_ATUACAO_PROD=NULL;
			SET NEW.MENU_LINK_ATUACAO_PROD=NULL;
			SET NEW.MENU_LABEL_ATUACAO_CONS=NULL;
			SET NEW.MENU_LINK_ATUACAO_CONS=NULL;
			SET NEW.HEADER_NEWSLETTER_TITULO=NULL;
			SET NEW.HEADER_NEWSLETTER_DESC=NULL;
			SET NEW.HEADER_PLACEHOLDER=NULL;
			SET NEW.HEADER_ABOUT_TITULO=NULL;
			SET NEW.HEADER_ABOUT_DESC=NULL;
			SET NEW.HEADER_TELEFONE=NULL;
			SET NEW.HEADER_ENDERECO=NULL;
			SET NEW.HEADER_NEWSLETTER_BUTTON=NULL;
			SET NEW.HEADER_COPYRIGHT=NULL;
			SET NEW.FOOTER_NEWSLETTER_TITULO=NULL;
			SET NEW.FOOTER_NEWSLETTER_DESC=NULL;
			SET NEW.FOOTER_PLACEHOLDER=NULL;
			SET NEW.FOOTER_ABOUT_TITULO=NULL;
			SET NEW.FOOTER_ABOUT_DESC=NULL;
			SET NEW.FOOTER_TELEFONE=NULL;
			SET NEW.FOOTER_ENDERECO=NULL;
			SET NEW.FOOTER_NEWSLETTER_BUTTON=NULL;
			SET NEW.FOOTER_COPYRIGHT=NULL;
			SET NEW.FOOTER_LINK_COPYRIGHT=NULL;
			SET NEW.TITULO_AREAS=NULL;
			SET NEW.TITULO_CLIENTES=NULL;
			SET NEW.TITULO_ATUACAO_CONSULT=NULL;
			SET NEW.TITULO_ATUACAO_DOC=NULL;
			SET NEW.TITULO_ATUACAO_PROD=NULL;
			SET NEW.TITULO_SOBRE_NOS=NULL;
			SET NEW.TITULO_CONTATOS=NULL;
			END IF;

		END;

-- TRIGGER: DELETE__TEMPLATE__STATIC;
CREATE DEFINER=`root`@`localhost` TRIGGER DELETE__TEMPLATE__STATIC AFTER DELETE ON TEMPLATE__STATIC FOR EACH ROW BEGIN 
	SET @permitir_atualizacao=1;
	DELETE FROM TEMPLATE__STATIC__TRANSLATE WHERE FW_UID_LANG=OLD.FW_UID_LANG; 
	END;

-- TRIGGER: TEMPLATE__STATIC__SECURITY_INSERT;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__STATIC__SECURITY_INSERT BEFORE INSERT ON TEMPLATE__STATIC__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__STATIC__SECURITY_UPDATE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__STATIC__SECURITY_UPDATE BEFORE UPDATE ON TEMPLATE__STATIC__TRANSLATE	FOR EACH ROW	BEGIN		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: TEMPLATE__STATIC__SECURITY_DELETE;
CREATE DEFINER=`root`@`localhost` TRIGGER TEMPLATE__STATIC__SECURITY_DELETE BEFORE DELETE ON TEMPLATE__STATIC__TRANSLATE
	FOR EACH ROW
	BEGIN
		DECLARE mensagem_erro VARCHAR(255);
		SET mensagem_erro = '0';
		IF @permitir_atualizacao=1 THEN 
			SET mensagem_erro = '';
		ELSE
			SET mensagem_erro = 'ATENÇÃO! Faça alterações APENAS pela tabela principal.';
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = mensagem_erro;
		END IF;
	END;

-- TRIGGER: UID_USUARIOS;
CREATE DEFINER=`root`@`localhost` TRIGGER `UID_USUARIOS` BEFORE INSERT ON `USUARIOS`
FOR EACH ROW SET new.UID=FLOOR(RAND()*9007199254740991)+1;

-- TRIGGER: INSERE_USUARIO_DADOS_PROJETO;
CREATE DEFINER=`root`@`localhost` TRIGGER `INSERE_USUARIO_DADOS_PROJETO` AFTER INSERT ON `USUARIOS`
FOR EACH ROW INSERT INTO USUARIOS__DADOS_PROJETO (UID_USER) VALUES (new.UID);

-- TRIGGER: DELETE_USUARIO_DADOS_PROJETO;
CREATE DEFINER=`root`@`localhost` TRIGGER `DELETE_USUARIO_DADOS_PROJETO` AFTER DELETE ON `USUARIOS`
FOR EACH ROW  DELETE FROM USUARIOS__DADOS_PROJETO WHERE UID_USER = OLD.UID;
